{
  "hash": "e015d6aceab16d6a5de71215b19326fa",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 08: Predicting Election Outcomes \"\nauthor: \"Your Group Members Names Here\"\ndate: \"Last Updated 2024-01-30\"\nformat:\n  html:\n    toc: true\n    toc-float: true\n    toc-depth: 2\n    number-sections: true\n---\n\n\n\n\n# Overview {.unnumbered}\n\nToday we'll work through exercise *6.6.2 A Probability Model for Betting Market Election Prediction* from QSS (pp. 309-310). We will use the daily data from the Intrade betting market to derive probabilities from degenerate gamblers about the likelihood that Obama would win the 2008 presidential election. We will use these probabilities to simulate possible elections and the summarize outcomes of these simulations graphically.\n\nPlan to spend the following amount of time\n\n1.  Get set up to work (5 minutes)\n\n2.  Calculate Obama's expected electoral vote share on November 3, 2008 (the day before the election) (10 minutes)\n\n3.  Simulate a 1000 elections for November 3, 2008 using the betting market prices a measure of the probability that Obama wins or loses a state (10 minutes)\n\n4.  Display the results of your simulation with a histogram. (5 minutes)\n\n5.  Transform these probabilities to reduce the likelihood that Obama wins states like Alabama and increase the likelihood that Obama wins states like California (5 minutes)\n\n6.  Simulate another 1000 elections using these transformed probabilities. Compare the results to your initial simulation. (10)\n\n7.  Calculate Obama's expected total number of votes for each day in the 120 days before the 2008 election (15 minutes)\n\n8.  Simulate 100 elections for each of the 120 days before the election, plot the results of your simulation. (20 minutes)\n\n9.  Take the class survey for Donuts.\n\n## Goals {.unnumbered}\n\nConceptually, the main goal of this lab is to give you some practice working with probabilities in an application to the real world (predicting elections)\n\nTechnically, you learn how to\n\n-   use `for()` loops, which a useful programming skill when you need to do something repeatedly\n\n-   work with `R`'s built in probability functions. Specifically, we'll use the:\n\n    -   `rbernoulli()` function to simulate \"coin flips\" for each state and on each date, will the betting market data will define the probability that Obama wins that state.\n    -   `pnorm()` and `qnorm()` functions to transform these probabilities, giving more probability to places where Obama is likely to win, and less probability to states Obama is unlikely to win.\n\n-   You'll also get practice wrangling and visualizing data (today using R's base graphics functions)\n\n## Workflow {.unnumbered}\n\n### Please knit this .Rmd file {.unnumbered}\n\nAs with every lab, you should:\n\n-   Download the file\n-   Save it in your course folder\n-   **Update the `author:` section of the YAML header to include the names of your group members in attendance.**\n-   Knit the document\n-   Open the html file in your browser (Easier to read)\n-   Write yourcode in the chunks provided\n-   Comment out or delete any test code you do not need\n-   **Knit the document again after completing a section or chunk** (Error checking)\n-   Upload the final lab to [Canvas](https://canvas.brown.edu/courses/1087979/assignments/7870531?module_item_id=10762404){target=\"_blank\"}.\n\n# Get setup to work\n\n## Load Packages\n\nFirst we'll load the pacakges we need for today:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(qss)\n```\n:::\n\n\nNow we'll load two data sets from the `qss` package: `pres08` and `intrade08`\n\n-   `pres08` contains the 2008 US presidential election outcomes by state.\n-   `intrade08` contains from Intrade, an online prediction market, in days leading up to the 2008 United States Presidential Election.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Results from 2008 election\ndata(\"pres08\")\n\n# Daily betting market data\ndata(\"intrade08\")\n```\n:::\n\n\n## Provide a high level overview each data set\n\nIn the code chunk below, please write some code to provide a high level overview of each data set.\n\nWe will primarily work with the `EV` variable from `pres08` which contains the electoral votes for each state, and the `PriceD` variable from `intrade08` from which we will construct a probability that Obama wins that state.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# HLO\n# pres08\nglimpse(pres08)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 51\nColumns: 5\n$ state.name <chr> \"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"…\n$ state      <chr> \"AL\", \"AK\", \"AZ\", \"AR\", \"CA\", \"CO\", \"CT\", \"DC\", \"DE\", \"FL\",…\n$ Obama      <int> 39, 38, 45, 39, 61, 54, 61, 92, 62, 51, 47, 72, 36, 62, 50,…\n$ McCain     <int> 60, 59, 54, 59, 37, 45, 38, 7, 37, 48, 52, 27, 62, 37, 49, …\n$ EV         <int> 9, 3, 10, 6, 55, 9, 7, 3, 3, 27, 15, 4, 4, 21, 11, 7, 6, 8,…\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(pres08)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  state.name           state               Obama           McCain     \n Length:51          Length:51          Min.   :33.00   Min.   : 7.00  \n Class :character   Class :character   1st Qu.:43.00   1st Qu.:40.00  \n Mode  :character   Mode  :character   Median :51.00   Median :47.00  \n                                       Mean   :51.37   Mean   :47.06  \n                                       3rd Qu.:57.50   3rd Qu.:56.00  \n                                       Max.   :92.00   Max.   :66.00  \n       EV       \n Min.   : 3.00  \n 1st Qu.: 4.50  \n Median : 8.00  \n Mean   :10.55  \n 3rd Qu.:11.50  \n Max.   :55.00  \n```\n\n\n:::\n\n```{.r .cell-code}\n# intrade08\nglimpse(intrade08)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 36,891\nColumns: 10\n$ .row      <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 1…\n$ day       <date> 2006-11-12, 2006-11-12, 2006-11-12, 2006-11-12, 2006-11-12,…\n$ statename <chr> \"Alabama\", \"Alaska\", \"Arizona\", \"Arkansas\", \"California\", \"C…\n$ MarketD   <chr> \"Democratic Party Nominee to win Alabama's Electoral College…\n$ PriceD    <dbl> 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 33.3, 40.0, …\n$ VolumeD   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ MarketR   <chr> \"Republican Party Nominee to win Alabama's Electoral College…\n$ PriceR    <dbl> 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 33.3, 40.0, …\n$ VolumeR   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ state     <chr> \"AL\", \"AK\", \"AZ\", \"AR\", \"CA\", \"CO\", \"CT\", \"DE\", \"DC\", \"GA\", …\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(intrade08)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      .row            day              statename           MarketD         \n Min.   :    1   Min.   :2006-11-12   Length:36891       Length:36891      \n 1st Qu.: 9224   1st Qu.:2007-05-12   Class :character   Class :character  \n Median :18446   Median :2007-11-09   Mode  :character   Mode  :character  \n Mean   :18446   Mean   :2007-11-09                                        \n 3rd Qu.:27668   3rd Qu.:2008-05-08                                        \n Max.   :36891   Max.   :2008-11-19                                        \n     PriceD         VolumeD          MarketR              PriceR     \n Min.   : 0.00   Min.   :    0.0   Length:36891       Min.   : 0.00  \n 1st Qu.:12.50   1st Qu.:    0.0   Class :character   1st Qu.:15.20  \n Median :43.00   Median :    0.0   Mode  :character   Median :51.00  \n Mean   :46.78   Mean   :    6.4                      Mean   :51.27  \n 3rd Qu.:82.50   3rd Qu.:    0.0                      3rd Qu.:85.00  \n Max.   :99.90   Max.   :17353.0                      Max.   :99.50  \n    VolumeR             state          \n Min.   :    0.000   Length:36891      \n 1st Qu.:    0.000   Class :character  \n Median :    0.000   Mode  :character  \n Mean   :    5.583                     \n 3rd Qu.:    0.000                     \n Max.   :14885.000                     \n```\n\n\n:::\n\n```{.r .cell-code}\nsum(table(intrade08$state)>723)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3\n```\n\n\n:::\n\n```{.r .cell-code}\nwhich(table(intrade08$state)>723)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nIN MO NC \n16 25 28 \n```\n\n\n:::\n:::\n\n\n**Briefly describe each data set**\n\n-   The `pres08` data set contains the 51 observations corresponding the 50 states plus the District of Columbia. Two variables describe the state name (`state.name`) and postal abbreviation (`state`). The `Obama` and `McCain` variables correspond to the vote share of each candidate in the each state in 2008 and the `EV` variable corresponds the Electoral College votes for each state.\n\n-   The `intrade08` data contain 36,891 observations. Each observation corresponds to a \"state-day\" and in total there are about just under two years of observations (Most states have 723 observations, Indiana, Missouri, and North Carolina have more than 723 observations, for some reason). That data contain information on the price of \"bets \" that the Democratic or Republican candidates will win that state in the election (`PriceD` and `PriceR`), as well was descriptions of the volume of trading (`VolumeD` and `VolumeR`) and the specific market.\n\n## Re-Arrange the Intrade\n\nIf you look closely at the data, you'd see that both are arranged alphabetically by state name, but in the `pres08` data, the District of Columbia is named \"D.C.\", while in the `intrade08` data it is called \"District of Columbia\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\npres08$state.name[8]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"D.C.\"\n```\n\n\n:::\n\n```{.r .cell-code}\nintrade08$statename[9]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"District of Columbia\"\n```\n\n\n:::\n:::\n\n\nAs a result, D.C. comes before Delaware in `pres08` but after Delaware in `intrade08`. It will be useful below, for the states to be in the same order in both data sets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# DC and DE are reversed\npres08$state[1:9]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"AL\" \"AK\" \"AZ\" \"AR\" \"CA\" \"CO\" \"CT\" \"DC\" \"DE\"\n```\n\n\n:::\n\n```{.r .cell-code}\nintrade08$state[1:9]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"AL\" \"AK\" \"AZ\" \"AR\" \"CA\" \"CO\" \"CT\" \"DE\" \"DC\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Same abbrevs\nsum(pres08$state %in% intrade08$state)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 51\n```\n\n\n:::\n\n```{.r .cell-code}\n# Different namings of DC\nsum(pres08$state.name %in% intrade08$statename)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 50\n```\n\n\n:::\n:::\n\n\nPlease use the `arrange()` function to re-arrange both data sets using the `state` variable which is the postal abbreviation code for each state and is the same in both data sets.\n\nFor the `pres08` data `arrange()` by `state` and `intrade08` by `day` and then by `state`\n\n-   Remember to save the output of `arrange()` back into each respective data frame\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# arrange pres08\npres08 <- pres08 %>%\n  arrange(state)\n\n# arrange intrade08\nintrade08 <- intrade08 %>%\n  arrange(day,state)\n```\n:::\n\n\nIf your code was correct, DC should now come before DE in `intrade08`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# pres08$state[1:9]\n# intrade08$state[1:9]\n```\n:::\n\n\nAnd the following code should return `TRUE`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# all.equal(pres08$state[1:51], intrade08$state[intrade08$day==\"2008-11-03\"])\n```\n:::\n\n\n## Convert the `PriceD` variable in `intrade08` to a probability\n\nThe `intrade08` data contain a variable called `PriceD` which we will treat as the probability that Obama will win the presidential election.\n\nRecall that probabilities must be between 0 and 1. Please create a variable called `prob_obama_win` in `intrade08` by dividing `PriceD` by 100.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create variable prob_obama_win from PriceD in intrade08\nintrade08 %>%\n  mutate(\n    prob_obama_win = PriceD/100\n  ) -> intrade08\n```\n:::\n\n\n## Create a subset of intrade08, called `df_nov3`\n\nNext we'll create a subset of the data, called `df_nov3` that contains just the data from the day before the election (that is Monday, November 3, 2008)\n\n-   Hint: try `filter()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_nov3 <- intrade08 %>%\n  filter(day == \"2008-11-03\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n# Calculate Obama's expected electoral votes on November 3, 2008\n\nUsing the data from `pres08` and `df_nov3`, calculate the expected number of electoral votes Obama is predicted to win in the Intrade data by summing up the states where `prob_obama_win` is greater than 0.5\n\nHints:\n\n-   Because `pres08` and `df_nov3` have the same number of rows, and the rows are ordered in the same way (alphabetically by postal abbreviation), we can select variables from `pres08` using a logical index (`[]`) on variables from `df_nov3`\n\n-   The you can just sum up the `EV` where `prob_obama_win` is greater than 0.5\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobama_ev <- sum(pres08$EV[df_nov3$prob_obama_win > 0.5])\nobama_ev\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 364\n```\n\n\n:::\n:::\n\n\n**Please fill in the `???` below:**\n\nUsing the Intrade data from November 3, 2008, Obama is expected to win **???** electoral votes\n\n------------------------------------------------------------------------\n\nSo it looks like the betting markets are pretty good. From the previous question, we saw that the Intrade data for November 3, 2008 predicted Obama will win 364 votes, which taking into account the fact that Nebraska divides its electoral votes, is pretty close to the 365 he actually won\n\n# Use the probabilities from the day before the election to simulate the total number of electoral votes Obama is predicted to win.\n\nNow let's use the probabilities from `prob_obama_win` in `df_nov3` to simulate an the idea of running repeated elections.\n\nOur variable `prob_obama_win` represents a probability that Obama win's a given state. It's relatively low for a Red state like Alabama, high for blue state like California and more uncertain for a swing state like North Carolina\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prob(Obama Win on Nov 3, 2008)\ndf_nov3$prob_obama_win[df_nov3$state == \"AL\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.033\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_nov3$prob_obama_win[df_nov3$state == \"NC\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.614\n```\n\n\n:::\n\n```{.r .cell-code}\ndf_nov3$prob_obama_win[df_nov3$state == \"CA\"]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.979\n```\n\n\n:::\n:::\n\n\nTo simulate the outcome of the election, we'll treat whether Obama won as the result of a [Bernoulli trial](https://pols1600.paultesta.org/slides/08-slides.html#92){target=\"_blank\"} where the probability of success (Obama winning) is $p_{ij}$ (that is, the value of `prob_obama_win`) for each state.\n\nIn most of these simulations, Obama will lose Alabama and win California. However, in each simulation, these probabilities suggest there's a chance he wins Alabama (3 percent) or loses California (2 percent)[^1]\n\n[^1]: Here we're assuming these probabilities are independent. Actual forecasting models like 538 or the NYT generally assume the probabilities of winning some states correlate with the probability of winning other neighboring states.\n\nTo simulate repeated elections, we'll do the following:\n\n-   set the random seed using `set.seed(123)` (This makes random simulations reproducible)\n\n-   define `sims` the number of simulations we want to to do. Let's set `sims` equal to 1,000\n\n-   define the number of states as `n_states` in our simulation, which corresponds to the number of *Bernoulli trials* (coinflips)\n\n-   define the probability `p_obama_win` (probability of Obama winning) corresponding to `prob_obama_win` in `df_nov3` for each state.\n\n-   create an *empty* vector called `obama_ev_1` to store the results of each simulation\n\n-   use a `for()` loop to simulate these hypothetical elections, where for each `i` in 1 to `sims`,\n\n    -   we take a random draw of size n (equal to the number of states) with corresponding probabilities `p` (equal to `prob_obama_win`) using `rbernoulli`\n    -   use the outcome of this random draw (a series of 0s and 1s of length `n_states`) to select the electoral votes for the states Obama one in simulation `i`\n    -   sum up the electoral votes for states Obama one in simulation `i` and save them to `obama_ev_1[i]`\n\nI've written some code to get you started in the code chunk below.\n\nPlease **uncomment the code** and replace the `???` with the correct values.\n\nWe'll interpret the results of our simulation in the next question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set random seed\nset.seed(123)\n\n# Define number of simulations\nsims <- 1000\n\n# Define number of states for each simulation\nn_states <- 51\n\n# Define the probability of Obama winning for each state\np_obama_win <- df_nov3$prob_obama_win\n\n\n# Create empty container for results of simulation\nobama_ev_1 <- c()\n\n# Use for loop to conduct simulations\n\nfor(i in 1:1000){\n  obama_ev_1[i] <- sum(\n    pres08$EV[rbernoulli(\n      n = n_states,\n      p = p_obama_win)\n      ]\n    )\n}\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: `rbernoulli()` was deprecated in purrr 1.0.0.\n```\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Display the distribution of predicted number of electoral votes in a histogram\n\nPlease do the following with `obama_ev_1`\n\n-   use the `hist()` function to create a histogram\n\n-   use the `abline()` function to plot a vertical line at 365\n\n    -   try running `?graphics::abline` to see the help page for `abline()` to see how to draw a vertical line on a plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(obama_ev_1)\nabline(v=365,col=\"blue\")\n```\n\n::: {.cell-output-display}\n![](08-lab-comments_files/figure-html/hist1-1.png){width=672}\n:::\n:::\n\n\n**Answer:** So the predictions seem a bit off. The most frequent value is a bit below Obama's actual vote share, and in some cases, the simulations actually have Obama losing. Part of this reflects the fact that model assumes the probability of winning or losing is independent across states, while models like 538 allow for some correlation across states (and adjust for other factors like the economy etc.)\n\n------------------------------------------------------------------------\n\nInteresting. So the typical electoral vote share from the simulations is a bit lower than Obama's actual vote share and in a small number of simulations, Obama is predicted to actually lose the election (e.g. had simulated vote shares below 270).\n\nPrediction markets tend to exaggerate the chances of long shots winning a campaign.\n\nLet's adjust the probabilities used above using the following formula:\n\n$$p_{ij}^* = \\Phi(1.64 \\times \\Phi^{-1}(p_{ij}))$$\n\nWhere $\\Phi$ is the PDF of the [normal distribution](https://pols1600.paultesta.org/slides/08-slides.html#102) (`prnorm()` in R) and $\\Phi^{-1}$ is the CDF (`qnorm()` in R) of the normal distribution.\n\n# Compute $p_{ij}^*$, plot the transformed probabilities and explain the transformation.\n\nUsing the formula above and the `pnorm()` and `qnorm()` functions in R transform `prob_obama_win` in `df_nov3` to `p_star`.\n\nThen plot the results.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_star <- pnorm(1.64*qnorm(df_nov3$prob_obama_win))\n\nplot(x= df_nov3$prob_obama_win, y = p_star)\n# Add line showing p_star function\ncurve(pnorm(1.64*qnorm(x)),add=T,col=\"grey\")\n\n# Add 45 degree line showing \n# Points below = lower prob\n# Point above = higher prob\nabline(a=0,b=1, lty=2)\n```\n\n::: {.cell-output-display}\n![](08-lab-comments_files/figure-html/pstar-1.png){width=672}\n:::\n:::\n\n\n**Please interpret the results of this transformation** Our transformation decreases the probability for low values of the original $p_{ij}$ and increases the probabilities of high $p_{ij}$. Substantively, this reduces the probability that Obama loses a state like California, or wins a state like Alabama.\n\n------------------------------------------------------------------------\n\nSo our transformation decreases the probability for low values of the original $p_{ij}$ and increases the probabilities of high $p_{ij}$\n\n# Using $p_{ij}^*$ repeat the simulations from above and compare the results\n\n-   Uncomment the code below and replace the `???` with the appropriate code.\n\n    -   Hint Use the code from the question 3, but replace `p_obama_win` with `p_star`\n\n-   Then plot the distribution of the old and new simulations with two histograms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nobama_ev_2 <- c() # Container to hold results of each simulation\n\n#Simulation using\nfor(i in 1:sims){\n  obama_ev_2[i] <- sum(pres08$EV[rbernoulli(n = n_states, p = p_star)])\n}\n# Plot distributions\nhist(obama_ev_1)\nhist(obama_ev_2, add=T, col=\"red\")\nabline(v=365,col=\"blue\")\n```\n\n::: {.cell-output-display}\n![](08-lab-comments_files/figure-html/sim2-1.png){width=672}\n:::\n:::\n\n\n**Answer:** So the transformation seems to have improved the predictions from the simulation.The center of the distribution is closer to Obama's actual vote share. Furthermore, whereas the original probability had Obama losing in some cases, all of the predictions from the transformed probability are above the 270.\n\n------------------------------------------------------------------------\n\nInteresting, so the transformation seemed to improve the predictions in that none of the simulated values were below the 270 electoral vote threshold.\n\n# Compute the expected number of electoral votes for Obama for the 120 days before November 4. Display the results in a time series plot and interpret the predictions.\n\nHere's some code to get the 120 days before the election\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get dates\ndates <- unique(sort(intrade08$day[intrade08$day < \"2008-11-04\" & intrade08$day >= \"2008-07-07\"]))\nsummary(dates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. \n\"2008-07-07\" \"2008-08-05\" \"2008-09-04\" \"2008-09-04\" \"2008-10-04\" \"2008-11-03\" \n```\n\n\n:::\n\n```{.r .cell-code}\nlength(dates)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 120\n```\n\n\n:::\n:::\n\n\nNow create a container to hold 120 predictions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create containers to hold the values you want to calculate for each day\nobama_ev_120 <- c()\n```\n:::\n\n\nAnd write code that:\n\n-   That loops through all 120 dates, and extracts the date for day i\n\n-   Calculates p_star from the `prob_obama_win` for that day\n\n-   Sums the electoral votes for states in which `p_star` is greater than 0.5\n\n-   Plots dates on the x axis and obama_ev_120 on the y\n\nUse the code below as a template and fill in the ???\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfor(i in 1:120){\n  # Extract day i from dates\n  day <- dates[i]\n  \n  # Calculate p_star for that day\n  p_star <- pnorm(1.64*qnorm(intrade08$prob_obama_win[intrade08$day == day]))\n    \n  # Sum expected EV for day \n  obama_ev_120[i] <- sum(pres08$EV[p_star > 0.5])\n}\n\n# Plot\nplot(x=dates, obama_ev_120,\n     ylim=c(0,538)\n     )\nabline(h=365)\n```\n\n::: {.cell-output-display}\n![](08-lab-comments_files/figure-html/ev120-1.png){width=672}\n:::\n:::\n\n\n**Answer:** So by October, the prediction markets seem to be pretty close to the actual electoral votes Obama received.\n\n# For each of the 120 days before the campaign conduct 100 simulation usings the $p_{ij}^*$ probabilities and do the following:\n\n-   Calculate the expected (mean) number of votes for the simulation for each day\n\n-   Compute the 2.5% and 97.5% percentiles of the simulated Electoral Votes from the simulation for each day using the `quantile()` function\n\n-   Plot the mean number of votes from the simulations for each day and add\n\n    -   a vertical segment that goes from the 2.5% percentile to 97.5% percentile for each day's simulation.\n    -   a solid blue horizontal line at 365 corresponding to Obama's actual electoral votes\n    -   a dashed red line at 270 corresponding to number of electoral votes need to win a presidential election.\n\n-   Interpret the results.\n\nYou need to use **two** `for()` loops for this.\n\nThe first for loop will loop through dates and calculate p_star for each date ($i$).\n\nThen, within that for loop, R will do a second loop, where: for each date and p_star, the second loop will generate $j$ simulations of the predicted number of electoral votes.\n\nAfter the $j$ simulations are complete, the code will calculate the quantities you want for that date, $i$, and then the code will move to the next date and repeat the process.\n\nUse your code from the previous questions to help you fill in the `???` in the code below\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create containers to hold the values you want to calculate for each day\n# Average predicted value\nev_mean <- c()\n# 97.5 percentile\nev_ul <- c()\n# 2.5 percentile\nev_ll <- c()\n\n# Simulation\n\nfor(i in 1:120){\n # 1. Extract day i from dates object\nday <- dates[i]\n\n # 2. Calculate p_star for day i\np_star <-  pnorm(1.64*qnorm(intrade08$prob_obama_win[intrade08$day == day]))\n\n # 3. create container for simulations for day i\nobama_ev_sim <- c()\n\n #. 4 Conduct 100 simulations\n  for(j in 1:100){\n   # For simulation j, calculate expected EV and save in container\nobama_ev_sim[j] <- sum(pres08$EV[rbernoulli(n_states,p_star)])\n\n }\n # 5.After 100 simulations, calculate\n\n# Average predicted EV for day i\nev_mean[i] <- mean(obama_ev_sim)\n\n# 97.5 percentile\nev_ul[i] <- quantile(obama_ev_sim, p = 0.975)\n\n# 2.5 percentile\nev_ll[i] <- quantile(obama_ev_sim, p = 0.025)\n\n # Repeat for next i until all 120 dates have been simulate.\n}\n\n# Plot values\n\nplot(x= dates,\n     y = ev_mean,\n    ylim=c(0,538)\n    )\n# Add vertical segment for 95% coverage interval\nsegments(x0=dates, x1 = dates, y0= ev_ll, y1 = ev_ul)\n\n# Add horizontal lines at 365 and 270\nabline(h=270,lty=2, col =\"red\")\nabline(h=365,lty=1, col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](08-lab-comments_files/figure-html/sim3-1.png){width=672}\n:::\n:::\n\n\n**Answer:** For most of the the 120 days before the election the majority of the simulations have Obama winning (with the exception of a brief period around the Republican Convention).\n\nBy October, 95 percent of the simulations have Obama with a electoral vote share above 270.\n\nThe width of the coverage intervals declines slightly over time, suggesting the betting markets are more certain of an Obama victory closer to the election.\n\n# Take the Class Survey {.unnumbered}\n\nPlease take a few moments to complete the [class survey](https://brown.co1.qualtrics.com/jfe/form/SV_cOnvgqXGJ9ybOvk){target=\"_blank\"} for this week.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}