<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.545">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Paul Testa">

<title>POLS 1600 - Week 06:</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">POLS 1600</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../class/index.html"> 
<span class="menu-text">Class</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.qmd"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="06-slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 06:</h1>
<p class="subtitle lead">Linear Regression with Multiple Predictors</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Paul Testa </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>Overview</h1>
<section id="general-plan" class="level2">
<h2 class="anchored" data-anchor-id="general-plan">General Plan</h2>
<ul>
<li>Group Assignment 2: Data</li>
<li>Setup
<ul>
<li>Packages</li>
<li>Data</li>
</ul></li>
<li>Feedback</li>
<li>Review
<ul>
<li>Causal Inference in Observational Designs</li>
<li>Simple Linear Regression</li>
</ul></li>
<li>Multiple Regression
<ul>
<li>Overview</li>
<li>Estimating and Interpreting Multiple Regression</li>
<li>Reading Regression Tables</li>
</ul></li>
</ul>
<p>class: inverse, center, middle # Research Questions</p>
</section>
<section id="assignment-1-research-questions" class="level2">
<h2 class="anchored" data-anchor-id="assignment-1-research-questions">Assignment 1 Research Questions:</h2>
<ul>
<li><p>Feedback posted to Canvas.</p></li>
<li><p>General Comments:</p>
<ul>
<li><p>Really great questions!</p></li>
<li><p>Feedback tries to balance interest/feasibility/data availability</p></li>
<li><p>“Not an experiment” <span class="math inline">\(\to\)</span> What would you have to randomize to answer your question</p></li>
<li><p>Not every question need to be causal</p></li>
<li><p>“Make your theories elaborate” - R.A. Fisher to <a href="https://www.jstor.org/stable/2344179">William Cochran</a></p>
<ul>
<li>But keep your models simple - Testa to POLS 1600</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="assignment-2-data-explorations" class="level2">
<h2 class="anchored" data-anchor-id="assignment-2-data-explorations">Assignment 2: Data Explorations</h2>
<ul>
<li><p>Prompt posted <a href="https://pols1600.paultesta.org/files/assignments/A1_research_questions.docx">here</a></p></li>
<li><p>Upload to <a href="https://canvas.brown.edu/courses/1087979/assignments/7870539">Canvas</a> next Sunday March 19</p></li>
</ul>
<ol type="1">
<li>A revised description of your group’s research project</li>
<li>A description of a linear model implied by your question</li>
<li>R code that loads some potentially relevant data to your question and at least one descriptive summary of that data.</li>
<li>Some information about your group such as:
<ul>
<li>A group name<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></li>
<li>A group color or color scheme</li>
<li>A group motto, mascot, crest, etc.</li>
<li>Your group’s theme song</li>
<li>Your group’s astrological sign</li>
<li>Anything else that you think well help you form strong ingroup bounds that facilitate collaboration</li>
</ul></li>
</ol>
<p>class:inverse, middle, center # 💪 ## Get set up to work</p>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>Hopefully, you were all able to install the following packages</p>
<ul>
<li><code>dataverse</code> (necessary for this week)</li>
<li><code>tidycensus</code> (necessary for this week)</li>
<li><code>easystats</code> (useful later)</li>
<li><code>DeclareDesign</code> (useful later)</li>
</ul>
</section>
<section id="census-api" class="level2">
<h2 class="anchored" data-anchor-id="census-api">Census API:</h2>
<p>Additionally, I hope you have all followed the steps <a href="https://pols1600.paultesta.org/slides/04-packages.html#3_Install_a_Census_API_tidycensus_package">here</a>:</p>
<ol type="1">
<li>Install the <code>tidycensus</code> package</li>
<li>Load the installed package</li>
<li>Request an API key from the Census</li>
<li>Check your email</li>
<li>Activate your key</li>
<li>Install your API key in R</li>
<li>Check that everything worked</li>
</ol>
<p>To install the an API key so we can download data directly from the US Census</p>
</section>
<section id="packages-for-today" class="level2">
<h2 class="anchored" data-anchor-id="packages-for-today">Packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>the_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## R Markdown</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"kableExtra"</span>,<span class="st">"DT"</span>,<span class="st">"texreg"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Tidyverse</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyverse"</span>, <span class="st">"lubridate"</span>, <span class="st">"forcats"</span>, <span class="st">"haven"</span>, <span class="st">"labelled"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Extensions for ggplot</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ggmap"</span>,<span class="st">"ggrepel"</span>, <span class="st">"ggridges"</span>, <span class="st">"ggthemes"</span>, <span class="st">"ggpubr"</span>, </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"GGally"</span>, <span class="st">"scales"</span>, <span class="st">"dagitty"</span>, <span class="st">"ggdag"</span>, <span class="st">"ggforce"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Graphics:</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"scatterplot3d"</span>, <span class="co">#&lt;&lt;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Data </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"COVID19"</span>,<span class="st">"maps"</span>,<span class="st">"mapdata"</span>,<span class="st">"qss"</span>,<span class="st">"tidycensus"</span>, <span class="st">"dataverse"</span>, </span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Analysis</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DeclareDesign"</span>, <span class="st">"easystats"</span>, <span class="st">"zoo"</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="define-a-function-to-load-and-if-needed-install-packages" class="level2">
<h2 class="anchored" data-anchor-id="define-a-function-to-load-and-if-needed-install-packages">Define a function to load (and if needed install) packages</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>ipak <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(new.pkg)) </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-packages-for-today" class="level2">
<h2 class="anchored" data-anchor-id="load-packages-for-today">Load packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ipak</span>(the_packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   kableExtra            DT        texreg     tidyverse     lubridate 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      forcats         haven      labelled         ggmap       ggrepel 
         TRUE          TRUE          TRUE          TRUE          TRUE 
     ggridges      ggthemes        ggpubr        GGally        scales 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      dagitty         ggdag       ggforce scatterplot3d       COVID19 
         TRUE          TRUE          TRUE          TRUE          TRUE 
         maps       mapdata           qss    tidycensus     dataverse 
         TRUE          TRUE          TRUE          TRUE          TRUE 
DeclareDesign     easystats           zoo 
         TRUE          TRUE          TRUE </code></pre>
</div>
</div>
<p>class:inverse, center, middle # 💪 ## Load Data for Thursday’s Lab</p>
</section>
<section id="load-the-covid-19-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-covid-19-data">Load the Covid-19 Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># covid &lt;- COVID19::covid19(</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   country = "US",</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   level = 2,</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   verbose = F</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># )</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://pols1600.paultesta.org/files/data/covid.rda"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="filter-covid-19-data-to-us-states-now-excluding-d.c.-as-well" class="level2">
<h2 class="anchored" data-anchor-id="filter-covid-19-data-to-us-states-now-excluding-d.c.-as-well">Filter Covid-19 Data to US States (Now Excluding D.C. as well)</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vector containing of US territories</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>territories <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"American Samoa"</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Guam"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Northern Mariana Islands"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Puerto Rico"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Virgin Islands"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"District of Columbia"</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out Territories and create state variable</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>covid_us <span class="ot">&lt;-</span> covid <span class="sc">%&gt;%</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>administrative_area_level_2 <span class="sc">%in%</span> territories)<span class="sc">%&gt;%</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> administrative_area_level_2</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mutate-calculate-new-deaths-per-capita-and-percent-vaccinated" class="level2">
<h2 class="anchored" data-anchor-id="mutate-calculate-new-deaths-per-capita-and-percent-vaccinated">Mutate: Calculate New Deaths Per Capita and Percent Vaccinated</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">new_deaths =</span> deaths <span class="sc">-</span> <span class="fu">lag</span>(deaths),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">new_deaths_pc =</span> new_deaths <span class="sc">/</span> population <span class="sc">*</span><span class="dv">100000</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">new_deaths_pc_14da =</span> zoo<span class="sc">::</span><span class="fu">rollmean</span>(new_deaths_pc, <span class="at">k =</span> <span class="dv">14</span>, <span class="at">align =</span> <span class="st">"right"</span>, <span class="at">fill=</span><span class="cn">NA</span> ),</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent_vaccinated =</span> people_fully_vaccinated<span class="sc">/</span>population<span class="sc">*</span><span class="dv">100</span>  </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    ) <span class="ot">-&gt;</span> covid_us</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data-on-presidential-elections" class="level2">
<h2 class="anchored" data-anchor-id="load-data-on-presidential-elections">Load Data on Presidential Elections</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this code first</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="st">"DATAVERSE_SERVER"</span> <span class="ot">=</span> <span class="st">"dataverse.harvard.edu"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>pres_df <span class="ot">&lt;-</span> <span class="fu">get_dataframe_by_name</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"1976-2020-president.tab"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"doi:10.7910/DVN/42MVDX"</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="co"># If the code above fails, comment out and uncomment the code below:</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># load(url("https://pols1600.paultesta.org/files/data/pres_df.rda"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hlo-of-presidential-elections-data" class="level2">
<h2 class="anchored" data-anchor-id="hlo-of-presidential-elections-data">HLO of Presidential Elections Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pres_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 15
   year state   state_po state_fips state_cen state_ic office       candidate   
  &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;       
1  1976 ALABAMA AL                1        63       41 US PRESIDENT "CARTER, JI…
2  1976 ALABAMA AL                1        63       41 US PRESIDENT "FORD, GERA…
3  1976 ALABAMA AL                1        63       41 US PRESIDENT "MADDOX, LE…
4  1976 ALABAMA AL                1        63       41 US PRESIDENT "BUBAR, BEN…
5  1976 ALABAMA AL                1        63       41 US PRESIDENT "HALL, GUS" 
6  1976 ALABAMA AL                1        63       41 US PRESIDENT "MACBRIDE, …
# ℹ 7 more variables: party_detailed &lt;chr&gt;, writein &lt;lgl&gt;,
#   candidatevotes &lt;dbl&gt;, totalvotes &lt;dbl&gt;, version &lt;dbl&gt;, notes &lt;lgl&gt;,
#   party_simplified &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="transform-data-to-get-just-2020-election" class="level2">
<h2 class="anchored" data-anchor-id="transform-data-to-get-just-2020-election">Transform Data to get just 2020 Election</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>pres_df <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">year_election =</span> year,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">str_to_title</span>(state),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Fix DC</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">ifelse</span>(state <span class="sc">==</span> <span class="st">"District Of Columbia"</span>, <span class="st">"District of Columbia"</span>, state)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(party_simplified <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"DEMOCRAT"</span>,<span class="st">"REPUBLICAN"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2020</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, state_po, year_election, party_simplified, candidatevotes, totalvotes</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> party_simplified,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> candidatevotes) <span class="sc">%&gt;%</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">dem_voteshare =</span> DEMOCRAT<span class="sc">/</span>totalvotes <span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">rep_voteshare =</span> REPUBLICAN<span class="sc">/</span>totalvotes<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">winner =</span> forcats<span class="sc">::</span><span class="fu">fct_rev</span>(<span class="fu">factor</span>(<span class="fu">ifelse</span>(rep_voteshare <span class="sc">&gt;</span> dem_voteshare,<span class="st">"Trump"</span>,<span class="st">"Biden"</span>)))</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> pres2020_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="transform-data-to-get-just-2020-election-1" class="level2">
<h2 class="anchored" data-anchor-id="transform-data-to-get-just-2020-election-1">Transform Data to get just 2020 Election</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pres2020_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  state      state_po year_election totalvotes DEMOCRAT REPUBLICAN dem_voteshare
  &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 Alabama    AL                2020    2323282   849624    1441170          36.6
2 Alaska     AK                2020     359530   153778     189951          42.8
3 Arizona    AZ                2020    3387326  1672143    1661686          49.4
4 Arkansas   AR                2020    1219069   423932     760647          34.8
5 California CA                2020   17500881 11110250    6006429          63.5
6 Colorado   CO                2020    3279980  1804352    1364607          55.0
# ℹ 2 more variables: rep_voteshare &lt;dbl&gt;, winner &lt;fct&gt;</code></pre>
</div>
</div>
</section>
<section id="load-data-on-median-state-income-from-the-census" class="level2">
<h2 class="anchored" data-anchor-id="load-data-on-median-state-income-from-the-census">Load Data on Median State Income from the Census</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>acs_df <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">"state"</span>, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">variables =</span> <span class="fu">c</span>(<span class="at">med_income =</span> <span class="st">"B19013_001"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">med_age =</span> <span class="st">"B01002_001"</span>), </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">year =</span> <span class="dv">2019</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Uncomment if get_acs() doesn't work:</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># load(url("https://pols1600.paultesta.org/files/data/acs_df.rda"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hlo-census-data" class="level2">
<h2 class="anchored" data-anchor-id="hlo-census-data">HLO: Census Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(acs_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  GEOID NAME    variable   estimate    moe
  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt;
1 01    Alabama med_age        39      0.2
2 01    Alabama med_income  50536    304  
3 02    Alaska  med_age        34.3    0.1
4 02    Alaska  med_income  77640   1015  
5 04    Arizona med_age        37.7    0.2
6 04    Arizona med_income  58945    266  </code></pre>
</div>
</div>
</section>
<section id="tidy-census-data" class="level2">
<h2 class="anchored" data-anchor-id="tidy-census-data">Tidy Census Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>acs_df <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> NAME,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, variable, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> variable,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> estimate) <span class="ot">-&gt;</span> acs_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tidy-census-data-1" class="level2">
<h2 class="anchored" data-anchor-id="tidy-census-data-1">Tidy Census Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(acs_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  state      med_age med_income
  &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;
1 Alabama       39        50536
2 Alaska        34.3      77640
3 Arizona       37.7      58945
4 Arkansas      38.1      47597
5 California    36.5      75235
6 Colorado      36.7      72331</code></pre>
</div>
</div>
</section>
<section id="merge-election-data-into-covid-data" class="level2">
<h2 class="anchored" data-anchor-id="merge-election-data-into-covid-data">Merge election data into Covid data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Always check dimensions before and after merging</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(covid_us)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54246    52</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(pres2020_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51  9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge covid_us with pres2020_df and save as tmp file</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">&lt;-</span> covid_us <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  pres2020_df,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"state"</span> <span class="ot">=</span> <span class="st">"state"</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(tmp) <span class="co"># Same number of rows as covid_us w/ 8 additional columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54246    60</code></pre>
</div>
</div>
</section>
<section id="merge-census-data-into-covid-data" class="level2">
<h2 class="anchored" data-anchor-id="merge-census-data-into-covid-data">Merge Census data into Covid data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(tmp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54246    60</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(acs_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52  3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge tmp with acs_df and save as final covid_df file</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>covid_df <span class="ot">&lt;-</span> tmp <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  acs_df,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"state"</span> <span class="ot">=</span> <span class="st">"state"</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(covid_df)  <span class="co"># Same number of rows as tmp w/ 2 additional columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54246    62</code></pre>
</div>
</div>
</section>
<section id="subset-merged-data-to-include-only-the-variables-and-observations-we-want" class="level2">
<h2 class="anchored" data-anchor-id="subset-merged-data-to-include-only-the-variables-and-observations-we-want">Subset Merged data to include only the variables and observations we want</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>the_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Covid variables</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"state"</span>,<span class="st">"state_po"</span>,<span class="st">"date"</span>,<span class="st">"new_deaths_pc_14da"</span>, <span class="st">"percent_vaccinated"</span>,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Election variables</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"winner"</span>,<span class="st">"rep_voteshare"</span>,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Demographic variables</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"med_age"</span>,<span class="st">"med_income"</span>,<span class="st">"population"</span>)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>covid_lab <span class="ot">&lt;-</span> covid_df <span class="sc">%&gt;%</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>( date <span class="sc">==</span> <span class="st">"2021-09-23"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(the_vars))<span class="sc">%&gt;%</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(the_vars)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(covid_lab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 50 10</code></pre>
</div>
</div>
</section>
<section id="a-preview-of-where-were-headed" class="level2">
<h2 class="anchored" data-anchor-id="a-preview-of-where-were-headed">A Preview of Where We’re Headed:</h2>
<p>Consider the following <strong>multiple regression</strong> (which we will on Thursday):</p>
<p><span class="math display">\[\text{New Covid Deaths} = \beta_0 +\beta_1 \text{Rep. Vote Share} +\beta_2 \text{Median Age} +\beta_3 \text{Median Income} + \epsilon\]</span> - The tell us how the outcome, <em>New Covid Deaths</em>, is expected to change with a <strong>unit change</strong> in a given predictor, controlling for/holding constant the other predictors in the model (more on “controlling for” shortly). - In the model above, <span class="math inline">\(\beta_2\)</span> tells us how <em>New Covid Deaths</em> is predicted to change, if the <em>Median Age</em> of a state increased by one year (i.e.&nbsp;a unit change). - Similarly, <span class="math inline">\(\beta_3\)</span> tells us how <em>New Covid Deaths</em> is predicted to change, if the <em>Median Income</em> of a state increased by one dollar (i.e.&nbsp;a unit change).<br>
- Since vote share, median income and age are measured on very different scales, interpreting these coefficients in the same model can be cumbersome.</p>
</section>
<section id="standardizing-variables." class="level2">
<h2 class="anchored" data-anchor-id="standardizing-variables.">Standardizing variables.</h2>
<ul>
<li><p>When variables are measured in different units multiple regression coefficients can be hard to interpret</p>
<ul>
<li>Coefficients, <span class="math inline">\(\beta\)</span>, tell us about the predicted change in <span class="math inline">\(y\)</span> for a unit change in <span class="math inline">\(x\)</span> or <span class="math inline">\(z\)</span></li>
<li>For example <span class="math inline">\(\beta_{age}\)</span></li>
</ul></li>
<li><p><em>z-scores</em> standardize variables so that their unit of measurement no longer matters (QSS p.&nbsp;103).</p></li>
<li><p>To calculate the <em>z-score</em> of a variable <span class="math inline">\(x\)</span>, we simply, substract off the mean and divide by the standard deviaton</p></li>
</ul>
<p><span class="math display">\[z\text{-score of x} = \frac{x_i - \mu_{x}}{\sigma_x}\]</span></p>
<ul>
<li>The <em>z-score</em> of Age is</li>
</ul>
<p><span class="math display">\[z\text{-score of Age} = \frac{\text{Age}_i - \mu_{Age}}{\sigma_{Age}}\]</span></p>
</section>
<section id="standardizing-predictors-in-r" class="level2">
<h2 class="anchored" data-anchor-id="standardizing-predictors-in-r">Standardizing Predictors in R</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>covid_lab <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">rep_voteshare_std =</span> (rep_voteshare <span class="sc">-</span> <span class="fu">mean</span>(rep_voteshare))<span class="sc">/</span><span class="fu">sd</span>(rep_voteshare),</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">med_age_std =</span> ( med_age <span class="sc">-</span> <span class="fu">mean</span>( med_age))<span class="sc">/</span><span class="fu">sd</span>( med_age),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">med_income_std =</span> (med_income <span class="sc">-</span> <span class="fu">mean</span>(med_income))<span class="sc">/</span><span class="fu">sd</span>(med_income),</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent_vaccinated_std =</span> (percent_vaccinated <span class="sc">-</span> <span class="fu">mean</span>(percent_vaccinated))<span class="sc">/</span><span class="fu">sd</span>(percent_vaccinated)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> covid_lab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="multiple-regression-with-standardized-predictors" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression-with-standardized-predictors">Multiple Regression with Standardized Predictors</h2>
<p>If we were to estimate a model with standardized predictors:</p>
<p><span class="math display">\[\text{New Covid Deaths} = \beta_0 +\beta_1 \text{Rep. Vote Share}_{std} +\beta_2 \text{Median Age}_{std} +\beta_3 \text{Median Income}_{std} + \epsilon\]</span> The coefficients still tell us predicted change in New Covid Deaths for a unit change in a predictor, but now a unit change corresponds to a 1-standard deviation increase of each predictor:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>covid_lab <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_rep_vote =</span> <span class="fu">sd</span>(rep_voteshare),</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_med_age =</span> <span class="fu">sd</span>(med_age),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_med_income =</span> <span class="fu">sd</span>(med_income),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_rep_vote_std =</span> <span class="fu">sd</span>(rep_voteshare_std),</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_med_age_std =</span> <span class="fu">sd</span>(med_age_std),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_med_income_std =</span> <span class="fu">sd</span>(med_income_std)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  sd_rep_vote sd_med_age sd_med_income sd_rep_vote_std sd_med_age_std
        &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;           &lt;dbl&gt;          &lt;dbl&gt;
1        10.4       2.36        10288.               1              1
# ℹ 1 more variable: sd_med_income_std &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="saving-data" class="level2">
<h2 class="anchored" data-anchor-id="saving-data">Saving Data</h2>
<p>Finally, I’ll save the data for Thursday’s lab</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Don't run this code</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(covid_lab, <span class="at">file =</span> <span class="st">"../files/data/06_lab.rda"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And on Thursday, we’ll be able to load the <code>covid_lab</code> just by running:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://pols1600.paultesta.org/files/data/06_lab.rda"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>class:inverse, middle, center # 🔍 ## Review</p>
</section>
<section id="review" class="level2">
<h2 class="anchored" data-anchor-id="review">Review</h2>
<ul>
<li>Casual Inference in Observational Designs
<ul>
<li>Difference-in-Differences</li>
<li>Regression Discontinuity Design</li>
<li>Instrumental Variables</li>
</ul></li>
<li>Simple Linear Regression</li>
</ul>
</section>
<section id="review-1" class="level2">
<h2 class="anchored" data-anchor-id="review-1">Review</h2>
<ul>
<li>Casual Inference in Observational Designs
<ul>
<li><strong>Difference-in-Differences</strong></li>
<li>Regression Discontinuity Design</li>
<li>Instrumental Variables</li>
</ul></li>
<li>Simple Linear Regression</li>
</ul>
<p>class:inverse, middle, center # 🔍 ## Casual Inference in Observational Designs</p>
</section>
<section id="review-casual-inference-in-observational-designs" class="level2">
<h2 class="anchored" data-anchor-id="review-casual-inference-in-observational-designs">Review: Casual Inference in Observational Designs</h2>
<ul>
<li>Observational designs that try to estimate causal effects need to justify assumptions about conditional independence:</li>
</ul>
<p><span class="math display">\[
Y_i(1),Y_i(0), Y_i, U_i \perp D_i |X_i
\]</span></p>
<p>–</p>
<ul>
<li>This assumption goes by many, jargony names: Selection on Observables, Conditional Independence, No unmeasured confounders.</li>
</ul>
<p>–</p>
<ul>
<li>Credibility of this assumption depends less on having a lot of data, and more on how your data were generated.</li>
</ul>
<p>–</p>
<ul>
<li><p><span class="math inline">\(Y_i(1),Y_i(0) \perp D_i \mid X_i\)</span> doesn’t mean that D has no effect on <span class="math inline">\(Y\)</span></p></li>
<li><p>Instead it means, that what we can estimate <span class="math inline">\(E[Y_i|D_i=1,X_i]\)</span> and treat this as a good (unbiased) estimate of <span class="math inline">\(E[Y_i(1)]\)</span> and similarly <span class="math inline">\(E[Y_i|D_i=0,X_i]\)</span> is a good estimate of <span class="math inline">\(E[Y_i(0)]\)</span></p></li>
</ul>
</section>
<section id="observational-designs-for-causal-inference" class="level2">
<h2 class="anchored" data-anchor-id="observational-designs-for-causal-inference">Observational Designs for Causal Inference</h2>
<ul>
<li><p>Three common research designs:</p>
<ul>
<li><p>Difference in Difference Design</p></li>
<li><p>Regression Discontinuity Designs</p></li>
<li><p>Instrumental Variable Designs</p></li>
</ul></li>
</ul>
<p>class: inverse, center, middle # 💡 Difference in Differences</p>
<p>class: inverse, center, middle background-image:url(https://www.finebooksmagazine.com/sites/default/files/styles/gallery_item/public/media-images/2020-11/map-lead-4.jpg?h=2ded5a3f&amp;itok=Mn-K5rQc) background-size: cover ## London in the Time of Cholera</p>
</section>
<section id="motivating-example-what-causes-cholera" class="level2">
<h2 class="anchored" data-anchor-id="motivating-example-what-causes-cholera">Motivating Example: What causes Cholera?</h2>
<ul>
<li><p>In the 1800s, cholera was thought to be transmitted through the air.</p></li>
<li><p>John Snow (the physician, not the snack), to explore the origins eventunally concluding that cholera was transmitted through living organisms in water.</p></li>
<li><p>Leveraged a <strong>natural experiment</strong> in which one water company in London moved its pipes further upstream (reducing contamination for Lambeth), while other companies kept their pumps serving Southwark and Vauxhall in the same location.</p></li>
</ul>
</section>
<section id="notation" class="level2">
<h2 class="anchored" data-anchor-id="notation">Notation</h2>
<p>Let’s adopt a little notation to help us think about the logic of Snow’s design:</p>
<ul>
<li><p><span class="math inline">\(D\)</span>: treatment indicator, 1 for treated neighborhoods (Lambeth), 0 for control neighborhoods (Southwark and Vauxhall)</p></li>
<li><p><span class="math inline">\(T\)</span>: period indicator, 1 if post treatment (1854), 0 if pre-treatment (1849).</p></li>
<li><p><span class="math inline">\(Y_{di}(t)\)</span> the potential outcome of unit <span class="math inline">\(i\)</span></p>
<ul>
<li><p><span class="math inline">\(Y_{1i}(t)\)</span> the potential outcome of unit <span class="math inline">\(i\)</span> when treated between the two periods</p></li>
<li><p><span class="math inline">\(Y_{0i}(t)\)</span> the potential outcome of unit <span class="math inline">\(i\)</span> when control between the two periods</p></li>
</ul></li>
</ul>
</section>
<section id="causal-effects" class="level2">
<h2 class="anchored" data-anchor-id="causal-effects">Causal Effects</h2>
<p>The individual causal effect for unit i at time t is:</p>
<p><span class="math display">\[\tau_{it} = Y_{1i}(t) − Y_{0i}(t)\]</span></p>
<p>What we observe is</p>
<p><span class="math display">\[Y_i(t) = Y_{0i}(t)\cdot(1 − D_i(t)) + Y_{1i}(t)\cdot D_i(t)\]</span></p>
<p><span class="math inline">\(D\)</span> only equals 1, when <span class="math inline">\(T\)</span> equals 1, so we never observe <span class="math inline">\(Y_0i(1)\)</span> for the treated units.</p>
<p>In words, we don’t know what Lambeth’s outcome would have been in the second period, had they not been treated.</p>
</section>
<section id="average-treatment-on-treated" class="level2">
<h2 class="anchored" data-anchor-id="average-treatment-on-treated">Average Treatment on Treated</h2>
<p>Our goal is to estimate the average effect of treatment on treated (ATT):</p>
<p><span class="math display">\[\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]\]</span></p>
<p>That is, what would have happened in Lambeth, had their water company not moved their pipes</p>
</section>
<section id="average-treatment-on-treated-1" class="level2">
<h2 class="anchored" data-anchor-id="average-treatment-on-treated-1">Average Treatment on Treated</h2>
<p>Our goal is to estimate the average effect of treatment on treated (ATT):</p>
<p>We we can observe is:</p>
<div class="line-block">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| Post-Period (T=1) | Pre-Period (T=0) |</div>
<p>||–|-| | Treated <span class="math inline">\(D_{i}=1\)</span> | <span class="math inline">\(E[Y_{1i}(1)\vert D_i = 1]\)</span> | <span class="math inline">\(E[Y_{0i}(0)\vert D_i = 1]\)</span> | | Control <span class="math inline">\(D_i=0\)</span> | <span class="math inline">\(E[Y_{0i}(1)\vert D_i = 0]\)</span> | <span class="math inline">\(E[Y_{0i}(0)\vert D_i = 0]\)</span> |</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Because potential outcomes notation is abstract, let’s consider a modified description of the Snow’s cholera death data from <a href="https://mixtape.scunning.com/difference-in-differences.html">Scott Cunningham</a>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Company</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1854 (T=1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1849 (T=0)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lambeth (D=1)</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southwark and Vauxhall (D=0</td>
<td style="text-align: right;">147</td>
<td style="text-align: right;">135</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="how-can-we-estimate-the-effect-of-moving-pumps-upstream" class="level2">
<h2 class="anchored" data-anchor-id="how-can-we-estimate-the-effect-of-moving-pumps-upstream">How can we estimate the effect of moving pumps upstream?</h2>
<p>Recall, our goal is to estimate the effect of the the treatment on the treated:</p>
<p><span class="math display">\[\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]\]</span></p>
<p>Let’s conisder some strategies Snow could take to estimate this quantity:</p>
</section>
<section id="before-vs-after-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="before-vs-after-comparisons">Before vs after comparisons:</h2>
<ul>
<li><p>Snow could have compared Labmeth in 1854 <span class="math inline">\((E[Y_i(1)|D_i = 1] = 19)\)</span> to Lambeth in 1849 <span class="math inline">\((E[Y_i(0)|D_i = 1]=85)\)</span>, and claimed that moving the pumps upstream led to 66 fewer cholera deaths.</p></li>
<li><p>This comparison assumes Lambeth’s pre-treatment outcomes in 1849 are a good proxy for what its outcomes would have been in 1954 if the pumps hadn’t moved <span class="math inline">\((E[Y_{0i}(1)|D_i = 1])\)</span>.</p></li>
<li><p>A skeptic might argue that Lambeth in 1849 <span class="math inline">\(\neq\)</span> Lambeth in 1854</p></li>
</ul>
</section>
<section id="treatment-control-comparisons-in-the-post-period." class="level2">
<h2 class="anchored" data-anchor-id="treatment-control-comparisons-in-the-post-period.">Treatment-Control comparisons in the Post Period.</h2>
<ul>
<li><p>Snow could have compared outcomes between Lambeth and S&amp;V in 1954 (<span class="math inline">\(E[Yi(1)|Di = 1] − E[Yi(1)|Di = 0]\)</span>), concluding that the change in pump locations led to 128 fewer deaths.</p></li>
<li><p>Here the assumption is that the outcomes in S&amp;V and in 1854 provide a good proxy for what would have happened in Lambeth in 1954 had the pumps not been moved <span class="math inline">\((E[Y_{0i}(1)|D_i = 1])\)</span></p></li>
<li><p>Again, our skeptic could argue Lambeth <span class="math inline">\(\neq\)</span> S&amp;V</p></li>
</ul>
</section>
<section id="difference-in-differences" class="level2">
<h2 class="anchored" data-anchor-id="difference-in-differences">Difference in Differences</h2>
<p>To address these concerns, Snow employed what we now call a difference-in-differences design,</p>
<p>There are two, equivalent ways to view this design.</p>
<p><span class="math display">\[\underbrace{\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\}}_{\text{1. Treat-Control |Post }}− \overbrace{\{E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}=0 ]\}}^{\text{Treated-Control|Pre}}\]</span></p>
<ul>
<li>Difference 1: Average change between Treated and Control in Post Period</li>
<li>Difference 2: Average change between Treated and Control in Pre Period</li>
</ul>
<p>Which is equivalent to:</p>
<p><span class="math display">\[\underbrace{\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(0)|D_{i} = 1]\}}_{\text{Post - Pre |Treated }}− \overbrace{\{E[Y_{i}(1)|D_{i} = 0] − E[Y_{i}(0)|D_{i}=0 ]\}}^{\text{Post-Pre|Control}}\]</span></p>
<ul>
<li>Difference 1: Average change between Treated over time</li>
<li>Difference 2: Average change between Control over time</li>
</ul>
</section>
<section id="difference-in-differences-1" class="level2">
<h2 class="anchored" data-anchor-id="difference-in-differences-1">Difference in Differences</h2>
<p>You’ll see the DiD design represented both ways, but they produce the same result:</p>
<p><span class="math display">\[
\tau_{ATT} = (19-147) - (85-135) = -78
\]</span></p>
<p><span class="math display">\[
\tau_{ATT} = (19-85) - (147-135) = -78
\]</span></p>
</section>
<section id="identifying-assumption-of-a-difference-in-differences-design" class="level2">
<h2 class="anchored" data-anchor-id="identifying-assumption-of-a-difference-in-differences-design">Identifying Assumption of a Difference in Differences Design</h2>
<p>The key assumption in this design is what’s known as the parallel trends assumption: <span class="math inline">\(E[Y_{0i}(1) − Y_{0i}(0)|D_i = 1] = E[Y_{0i}(1) − Y_{0i}(0)|D_i = 0]\)</span></p>
<ul>
<li>In words: If Lambeth hadn’t moved its pumps, it would have followed a similar path as S&amp;V</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/paralleltrends-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Where:</p>
<ol type="1">
<li><span class="math inline">\(E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\)</span></li>
<li><span class="math inline">\(E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}\} = 0]\)</span></li>
<li><span class="math inline">\(E[Y_{1i}(1) − Y_{0i}(1)|D_{i} = 1]\)</span></li>
</ol>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li><p>A Difference in Differences (DiD, or diff-in-diff) design combines a pre-post comparison, with a treated-control comparison</p>
<ul>
<li><p>Taking the pre-post difference removes any fixed differences between the units</p></li>
<li><p>Then taking the difference between treated and control differences removes any common differences over time</p></li>
</ul></li>
<li><p>The key identifying assumption of a DiD design is the “assumption of parallel trends”</p>
<ul>
<li>Absent treatment, treated and control groups would see the same changes over time.</li>
<li>Hard to prove, possible to test</li>
</ul></li>
</ul>
</section>
<section id="extensions-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="extensions-and-limitations">Extensions and limitations</h2>
<ul>
<li>DiD easy to estimate with linear regression</li>
<li>Generalizes to multiple periods and treatment interventions
<ul>
<li>More pre-treatment periods allow you assess “parallel trends” assumption</li>
</ul></li>
<li>Alternative methods
<ul>
<li>Synthetic control</li>
<li>Event Study Designs</li>
</ul></li>
<li>What if you have multiple treatments or treatments that come and go?
<ul>
<li>Panel Matching</li>
<li>Generalized Synthetic control</li>
</ul></li>
</ul>
</section>
<section id="applications" class="level2">
<h2 class="anchored" data-anchor-id="applications">Applications</h2>
<ul>
<li><p><a href="https://www.nber.org/papers/w4509">Card and Krueger (1994)</a> What effect did raising the minimum wage in NJ have on employment</p></li>
<li><p><a href="https://onlinelibrary.wiley.com/doi/full/10.1111/ajps.12116?casa_token=_ceCu4SwzTEAAAAA%3AP9aeaZpT_Zh1VdWKXx_tEmzaJTtMJ1n0eG7EaYlvJZYN000re33cfMAI2O8N8htFJjOsln2GyVeQql4">Abadie, Diamond, &amp; Hainmueller (2014)</a> What effect did German Unification have on economic development in West Germany</p></li>
<li><p><a href="https://www.cambridge.org/core/journals/american-political-science-review/article/impact-of-recentralization-on-public-services-a-differenceindifferences-analysis-of-the-abolition-of-elected-councils-in-vietnam/3477854BAAFE152DC93C594169D64F58">Malesky, Nguyen and Tran (2014)</a> How does decentralization influence public services?</p></li>
</ul>
<p>class:inverse, middle, center # 🔍 # Simple Linear Regression ### Linear regression provides a linear estimate of the CEF</p>
</section>
<section id="review-simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="review-simple-linear-regression">Review: Simple Linear Regression</h2>
<ul>
<li><strong>Conceptual</strong>
<ul>
<li>Simple linear regression estimates a line of best fit that summarizes relationships between two variables</li>
</ul></li>
</ul>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1x_i + \epsilon_i
\]</span></p>
<ul>
<li><strong>Practical</strong>
<ul>
<li>We estimate linear models in R using the <code>lm()</code> function</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><em>Technical/Definitional</em>
<ul>
<li>Linear regression chooses <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> to minimize the Sum of Squared Residuals (SSR):</li>
</ul></li>
</ul>
<p><span class="math display">\[\textrm{Find }\hat{\beta_0},\,\hat{\beta_1} \text{ arg min}_{\beta_0, \beta_1} \sum (y_i-(\beta_0+\beta_1x_i))^2\]</span></p>
<ul>
<li><em>Theoretical</em>
<ul>
<li>Linear regression provides a <strong>linear</strong> estimate of the conditional expectation function (CEF): <span class="math inline">\(E[Y|X]\)</span></li>
</ul></li>
</ul>
</section>
<section id="linear-regression-and-the-cef" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-and-the-cef">Linear Regression and the CEF</h2>
<p>Recall the first model we fit in last week’s lab</p>
<p><span class="math display">\[\text{new_deaths} = \beta_0 + \beta_1 \text{winner} + \epsilon\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(new_deaths <span class="sc">~</span> winner, covid_df)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = new_deaths ~ winner, data = covid_df)

Coefficients:
(Intercept)  winnerBiden  
      18.99         3.57  </code></pre>
</div>
</div>
<p><code>m1</code> is the equation for a very simple line defined by two points:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> = E[new_deaths|winner = Trump]</li>
<li><span class="math inline">\(\beta_0 + \beta_1\)</span> = E[new_deaths|winner = Biden]</li>
</ul>
</section>
<section id="linear-regression-and-the-cef-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-and-the-cef-1">Linear Regression and the CEF</h2>
<p>It’s helpful to take a look at what’s going on under the hood in <code>lm()</code></p>
<p>We gave it the following data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(m1<span class="sc">$</span>model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   new_deaths winner
67          0  Biden
68          0  Biden
69          0  Biden
70          0  Biden
71          0  Biden
72          0  Biden</code></pre>
</div>
</div>
</section>
<section id="linear-regression-and-the-cef-2" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-and-the-cef-2">Linear Regression and the CEF</h2>
<ul>
<li>R doesn’t know how to calculate the mean of <code>Biden</code> (or any character or factor data).</li>
<li>Instead it creates an indicator variable <code>winnerBiden</code> which equals 1 when <code>winner</code> equals <code>Biden</code> and 0 otherwise.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(m1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) winnerBiden
67           1           1
68           1           1
69           1           1
70           1           1
71           1           1
72           1           1</code></pre>
</div>
</div>
</section>
<section id="linear-regression-and-the-cef-3" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-and-the-cef-3">Linear Regression and the CEF</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(m1<span class="sc">$</span>model<span class="sc">$</span>winner)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Trump Biden 
26538 26788 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">model.matrix</span>(m1)[,<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
26538 26788 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>covid_df<span class="sc">%&gt;%</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">winner01 =</span> <span class="fu">ifelse</span>(winner<span class="sc">==</span><span class="st">"Biden"</span>,<span class="dv">1</span>,<span class="dv">0</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(winner01, new_deaths))<span class="sc">+</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"point"</span>,<span class="at">fun=</span>mean,<span class="at">col=</span> <span class="st">"red"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="dv">0</span>,<span class="at">xend =</span><span class="dv">1</span>, </span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>                   <span class="at">y=</span><span class="fu">coef</span>(m1)[<span class="dv">1</span>],</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">yend =</span> <span class="fu">coef</span>(m1)[<span class="dv">1</span>]<span class="sc">+</span><span class="fu">coef</span>(m1)[<span class="dv">2</span>]<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>                   ),</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">col=</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="linear-regression-and-the-cef-4" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-and-the-cef-4">Linear Regression and the CEF</h2>
<ul>
<li>When the CEF function is linear, <code>lm()</code> provides you coefficients that give you conditional means like in <code>m1</code>
<ul>
<li>The CEF is linear for <em>saturated models</em> in like <code>m1</code> where the coefficients define every possible category of comparison.</li>
</ul></li>
<li>For continuous variables, like <code>m3</code> from the lab below, <code>lm()</code> provides a linear approximation to the CEF</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(new_deaths_pc_14da <span class="sc">~</span> percent_vaccinated, covid_df,</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">subset =</span> date <span class="sc">==</span> <span class="st">"2021-09-23"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = new_deaths_pc_14da ~ percent_vaccinated, data = covid_df, 
    subset = date == "2021-09-23")

Coefficients:
       (Intercept)  percent_vaccinated  
           2.41854            -0.03301  </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>covid_df <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(date <span class="sc">==</span> <span class="st">"2021-09-23"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(percent_vaccinated, new_deaths_pc_14da))<span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span>.<span class="dv">5</span>,<span class="at">alpha=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary_bin</span>(<span class="at">fun =</span> <span class="st">"mean"</span>, </span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>                   <span class="at">geom =</span> <span class="st">"point"</span>, </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">col=</span><span class="st">"red"</span>,</span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bins =</span><span class="dv">10</span></span>
<span id="cb55-9"><a href="#cb55-9" aria-hidden="true" tabindex="-1"></a>                   )<span class="sc">+</span></span>
<span id="cb55-10"><a href="#cb55-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span><span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>class: inverse, middle, center # 💡 ## Multiple Regression</p>
</section>
<section id="overiew-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="overiew-multiple-regression">Overiew: Multiple Regression</h2>
<ul>
<li><strong>Conceptual</strong>
<ul>
<li>Multiple linear regression generalizes simple regression to models with multiple predictors</li>
</ul></li>
</ul>
<p><span class="math display">\[y_i = \beta_0 + \beta_1x_{1,i} +\beta_2x_{2,i} + \epsilon_i\]</span></p>
<p><span class="math display">\[y_i = X\beta + \epsilon_i\]</span></p>
<ul>
<li><strong>Practical</strong>
<ul>
<li>We estimate linear models in R using the <code>lm()</code> function using the <code>+</code> to add predictors</li>
<li>We use the <code>*</code> to include the main effects <span class="math inline">\((\beta_1 x, \beta_2z)\)</span> and interactions <span class="math inline">\((\beta_3 (x\cdot z))\)</span>of two predictors</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> z, <span class="at">data =</span> df)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x<span class="sc">*</span>z, <span class="at">data =</span> df) <span class="co"># Is a shortcut for:</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> z <span class="sc">+</span> x<span class="sc">:</span>z, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="overiew-multiple-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="overiew-multiple-regression-1">Overiew: Multiple Regression</h2>
<ul>
<li><em>Technical/Definitional</em>
<ul>
<li>Simple linear regression chooses a <span class="math inline">\(\hat{\beta_0}\)</span> and <span class="math inline">\(\hat{\beta_1}\)</span> to minimize the Sum of Squared Residuals (SSR):</li>
</ul></li>
</ul>
<p><span class="math display">\[\textrm{Find }\hat{\beta_0},\,\hat{\beta_1} \text{ arg min}_{\beta_0, \beta_1} \sum (y_i-(\hat{\beta_0}+\hat{\beta_1}x_i))^2\]</span> - Multiple linear regression chooses a vector of coefficients <span class="math inline">\(\hat{\beta}\)</span> to minimize the Sum of Squared Residuals (SSR):</p>
<p><span class="math display">\[\textrm{Find }\widehat{\beta} \text{ argmin }_{\widehat{\beta}} \sum \epsilon^2=\epsilon^\prime\epsilon=(Y-X\widehat{\beta})^\prime(Y-X\widehat{\beta})\]</span></p>
<ul>
<li><em>Theoretical</em>
<ul>
<li>Multiple Linear regression provides a <strong>linear</strong> estimate of the conditional expectation function (CEF): <span class="math inline">\(E[Y|X]\)</span> where <span class="math inline">\(Y\)</span> is now a function of multiple predictors, <span class="math inline">\(X\)</span></li>
</ul></li>
</ul>
<p>class: inverse, middle, center # 💡 ## Estimating and Interpreting Multiple Regression Regression Models</p>
</section>
<section id="political-interest-and-partisan-evaluations" class="level2">
<h2 class="anchored" data-anchor-id="political-interest-and-partisan-evaluations">Political Interest and Partisan Evaluations</h2>
<p>Let’s load some data from the <a href="https://electionstudies.org/data-center/2016-time-series-study/">2016 NES</a> and explore the relationship between political interest and evaluations of presidential candidates:</p>
<ul>
<li>Political Interest: “How interested are you in in politics?
<ul>
<li>Very Interested</li>
<li>Somewhat interested</li>
<li>Not very Interested</li>
<li>Not at all Interested</li>
</ul></li>
<li>Feeling Thermometer: “… On the feeling thermometer scale of 0 to 100, how would you rate”
<ul>
<li>Donald Trump</li>
<li>Hillary Clinton</li>
</ul></li>
</ul>
</section>
<section id="data-1" class="level2">
<h2 class="anchored" data-anchor-id="data-1">Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://pols1600.paultesta.org/files/data/nes.rda"</span>))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Look at data</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(nes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1200   14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  caseid    state age gender educ faminc pid7 ideo5 pol_interest church_atd
1    745  Alabama  19      2    3     97    5     3            1          2
2   1115  Alabama  46      1    3      3    1     1            3          6
3    258  Alabama  59      2    2      6    2     3            2          1
4    126  Alabama  55      2    4      6    1     2            3          5
5    414  Alabama  66      1    3      8    7     4            3          3
6    523  Alabama  61      1    2     97    1     2            3          6
  bornagain01 ft_trump ft_hrc vote_choice
1           0        3     19       Other
2           0        0     36         HRC
3           1       22      2        &lt;NA&gt;
4           0        1     80         HRC
5           1      100      3        &lt;NA&gt;
6           1        0    100        &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="data-hlo" class="level2">
<h2 class="anchored" data-anchor-id="data-hlo">Data: HLO</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(nes<span class="sc">$</span>pol_interest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0   1   2   3 
 78 178 348 568 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nes<span class="sc">$</span>ft_trump)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00    2.00   30.00   38.38   72.00  100.00       3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nes<span class="sc">$</span>ft_hrc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00    3.00   44.00   42.99   76.00  100.00       1 </code></pre>
</div>
</div>
</section>
<section id="data-wranglingrecoding" class="level2">
<h2 class="anchored" data-anchor-id="data-wranglingrecoding">Data Wrangling/Recoding</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>nes <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">income =</span> <span class="fu">ifelse</span>(faminc <span class="sc">&gt;</span> <span class="dv">16</span>, <span class="cn">NA</span>, faminc),</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">interested =</span> <span class="fu">ifelse</span>(pol_interest<span class="sc">==</span><span class="dv">3</span>,T,F),</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">pol_interest_f =</span> <span class="fu">factor</span>(<span class="fu">case_when</span>(</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>      pol_interest <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"Not at all Interested"</span>,</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>      pol_interest <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Not very Interested"</span>,</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>      pol_interest <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Somewhat Interested"</span>,</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>      pol_interest <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Very Interested"</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>    )),</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">tc_diff =</span> <span class="fu">abs</span>(ft_trump <span class="sc">-</span> ft_hrc)</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> nes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="roadmap" class="level2">
<h2 class="anchored" data-anchor-id="roadmap">Roadmap</h2>
<p>Let’s estimate the following series of models, predicting the absolute value of the difference in feeling thermometer ratings between Trump and Clinton (<code>tc_diff</code>)</p>
<p><span class="math display">\[\text{tc_diff} = \beta_0\]</span> <span class="math display">\[\text{tc_diff} = \beta_0 + \beta_1\text{interested}\]</span> <span class="math display">\[\text{tc_diff} = \beta_0 + \beta_1\text{pol_interest_f}\]</span> <span class="math display">\[\text{tc_diff} = \beta_0 + \beta_1\text{pol_interest}\]</span> <span class="math display">\[\text{tc_diff} = \beta_0 + \beta_1\text{interested} + \beta_2\text{age}\]</span> <span class="math display">\[\text{tc_diff} = \beta_0 + \beta_1\text{interested} + \beta_2\text{age} + \beta_3\text{interested} \times \text{age}\]</span> <span class="math display">\[\text{tc_diff} = \beta_0 + \beta_1\text{age} + \beta_2\text{income}\]</span></p>
</section>
<section id="m0-the-empty-model" class="level2">
<h2 class="anchored" data-anchor-id="m0-the-empty-model"><code>m0</code>: “The Empty Model”</h2>
<p>A linear model with just an intercept returns the mean of <code>tc_diff</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>m0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> <span class="dv">1</span>, nes)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>m0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tc_diff ~ 1, data = nes)

Coefficients:
(Intercept)  
      53.58  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nes<span class="sc">$</span>tc_diff, <span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53.57776</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save Sum of Squared Residuals</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>ssr0 <span class="ot">&lt;-</span> <span class="fu">sum</span>(m0<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="m1-a-model-with-a-single-dichotomous-predictor" class="level4">
<h4 class="anchored" data-anchor-id="m1-a-model-with-a-single-dichotomous-predictor"><code>m1</code> A model with a single dichotomous predictor</h4>
<p>Now let’s model <code>tc_diff</code> as function of whether respondents are very interested in politics (<code>interested</code> = T) or not (<code>interested</code> = F)</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> interested, nes)</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) interestedTRUE 
      47.84500       12.74655 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nes<span class="sc">$</span>tc_diff[nes<span class="sc">$</span>interested <span class="sc">==</span> F],<span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 47.845</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m1)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   60.59155 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nes<span class="sc">$</span>tc_diff[nes<span class="sc">$</span>interested <span class="sc">==</span> T],<span class="at">na.rm =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60.59155</code></pre>
</div>
</div>
</section>
<section id="m1-a-model-with-a-single-dichotomous-predictor-1" class="level4">
<h4 class="anchored" data-anchor-id="m1-a-model-with-a-single-dichotomous-predictor-1"><code>m1</code> A model with a single dichotomous predictor</h4>
<ul>
<li>If we tell R not to include an intercept, it returns those conditional means exactly.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>m1_alt <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">+</span> interested, nes)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1_alt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>interestedFALSE  interestedTRUE 
       47.84500        60.59155 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(nes<span class="sc">$</span>tc_diff, nes<span class="sc">$</span>interested, mean,<span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   FALSE     TRUE 
47.84500 60.59155 </code></pre>
</div>
</div>
</section>
<section id="m1-a-model-with-a-single-dichotomous-predictor-2" class="level4">
<h4 class="anchored" data-anchor-id="m1-a-model-with-a-single-dichotomous-predictor-2"><code>m1</code> A model with a single dichotomous predictor</h4>
<ul>
<li>When we compare the SSR from <code>m1</code> we see that it has decreased from <code>m0</code> reflecting the fact some of the total variation in <code>tc_diff</code> is being explained by the variation in <code>interested</code></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save Sum of Squared Residuals</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>ssr1 <span class="ot">&lt;-</span> <span class="fu">sum</span>(m1<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>ssr1 <span class="sc">&lt;</span> ssr0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="m2-a-model-with-a-single-categoical-predictor" class="level4">
<h4 class="anchored" data-anchor-id="m2-a-model-with-a-single-categoical-predictor"><code>m2</code> A model with a single categoical predictor</h4>
<p>Now let’s model <code>tc_diff</code> as function of the categorical predictor <code>pol_interest_f</code>, which is a factor variable of the four unique levels of political interest</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> pol_interest_f, nes)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>m2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tc_diff ~ pol_interest_f, data = nes)

Coefficients:
                      (Intercept)  pol_interest_fNot very Interested  
                           46.104                              1.727  
pol_interest_fSomewhat Interested      pol_interest_fVery Interested  
                            2.136                             14.488  </code></pre>
</div>
</div>
<ul>
<li>Woah, why did R turn a single variable into model with four coefficients?</li>
</ul>
<p>When we give <code>lm()</code> factor or character data,</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(m2<span class="sc">$</span>model)[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tc_diff      pol_interest_f
1      16 Not very Interested
2      36     Very Interested
3      20 Somewhat Interested
4      79     Very Interested</code></pre>
</div>
</div>
<p>It converts this data in separate binary indicators for each level excluding the first (“Not at all interested”), that take a value of 1 when <code>pol_interest_f</code> equals that level and 0 otherwise</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(m2))[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) pol_interest_fNot very Interested
1           1                                 1
2           1                                 0
3           1                                 0
4           1                                 0
  pol_interest_fSomewhat Interested pol_interest_fVery Interested
1                                 0                             0
2                                 0                             1
3                                 1                             0
4                                 0                             1</code></pre>
</div>
</div>
</section>
</section>
<section id="m2-a-model-with-a-single-categoical-predictor-1" class="level2">
<h2 class="anchored" data-anchor-id="m2-a-model-with-a-single-categoical-predictor-1"><code>m2</code> A model with a single categoical predictor</h2>
<p>The coefficients in <code>m2</code> tell us how the conditional mean of <code>tc_diff</code> for someone with a given level of interest is likely to very from the conditional mean of <code>tc_diff</code> for someone that is not at all interested in politics.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(nes<span class="sc">$</span>tc_diff, nes<span class="sc">$</span>pol_interest_f, mean,<span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Not at all Interested   Not very Interested   Somewhat Interested 
             46.10390              47.83051              48.23988 
      Very Interested 
             60.59155 </code></pre>
</div>
</div>
<ul>
<li><code>Not at all interested</code> is the <em>reference</em> or <em>excluded</em> category, described by the intercept coefficient in <code>m2</code></li>
</ul>
</section>
<section id="m2-a-model-with-a-single-categoical-predictor-2" class="level2">
<h2 class="anchored" data-anchor-id="m2-a-model-with-a-single-categoical-predictor-2"><code>m2</code> A model with a single categoical predictor</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare to</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Not at all</span></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
    46.1039 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Not very</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m2)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   47.83051 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Somewhat</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m2)[<span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   48.23988 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Very</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m2)[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   60.59155 </code></pre>
</div>
</div>
</section>
<section id="m2-a-model-with-a-single-categorical-predictor" class="level2">
<h2 class="anchored" data-anchor-id="m2-a-model-with-a-single-categorical-predictor"><code>m2</code> A model with a single categorical predictor</h2>
<ul>
<li>Again if we excluded the intercept <code>lm()</code> returns the conditional means</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>m2_alt <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">+</span> pol_interest_f, nes)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m2_alt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pol_interest_fNot at all Interested   pol_interest_fNot very Interested 
                           46.10390                            47.83051 
  pol_interest_fSomewhat Interested       pol_interest_fVery Interested 
                           48.23988                            60.59155 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(nes<span class="sc">$</span>tc_diff, nes<span class="sc">$</span>pol_interest_f, mean,<span class="at">na.rm=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Not at all Interested   Not very Interested   Somewhat Interested 
             46.10390              47.83051              48.23988 
      Very Interested 
             60.59155 </code></pre>
</div>
</div>
</section>
<section id="m2-a-model-with-a-single-categorical-predictor-1" class="level2">
<h2 class="anchored" data-anchor-id="m2-a-model-with-a-single-categorical-predictor-1"><code>m2</code> A model with a single categorical predictor</h2>
<ul>
<li>Finally, note that the SSR for <code>m2</code> is lower than that of <code>m1</code>. Including more information about varying levels of political interest helped us explain more variation in our outcome</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save Sum of Squared Residuals</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>ssr2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(m2<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>ssr2 <span class="sc">&lt;</span> ssr1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="m3-a-model-with-a-single-numeric-predictor" class="level2">
<h2 class="anchored" data-anchor-id="m3-a-model-with-a-single-numeric-predictor"><code>m3</code> A model with a single numeric predictor</h2>
<p>What if we had instead modeled <code>tc_diff</code> as a function of <code>pol_interest</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> pol_interest, nes)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>m3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tc_diff ~ pol_interest, data = nes)

Coefficients:
 (Intercept)  pol_interest  
      40.799         6.012  </code></pre>
</div>
</div>
<p><code>lm()</code> returns a single coefficient, because <code>pol_interest</code> is a numeric variable.</p>
</section>
<section id="comparing-m2-to-m3" class="level2">
<h2 class="anchored" data-anchor-id="comparing-m2-to-m3">Comparing <code>m2</code> to <code>m3</code></h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>nes <span class="sc">%&gt;%</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(pol_interest,tc_diff))<span class="sc">+</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size=</span>.<span class="dv">5</span>, <span class="at">alpha=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span><span class="st">"lm"</span>, <span class="fu">aes</span>(<span class="at">col =</span> <span class="st">"m3"</span>),<span class="at">se=</span>F)<span class="sc">+</span></span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom =</span><span class="st">"point"</span>,</span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">fun =</span> mean,</span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">col =</span> <span class="st">"m2"</span>)</span>
<span id="cb111-8"><a href="#cb111-8" aria-hidden="true" tabindex="-1"></a>               )<span class="sc">+</span></span>
<span id="cb111-9"><a href="#cb111-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">col =</span> <span class="st">"Model"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="comparing-m2-to-m3-1" class="level4">
<h4 class="anchored" data-anchor-id="comparing-m2-to-m3-1">Comparing <code>m2</code> to <code>m3</code></h4>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="m4-a-model-with-both-a-dichtomous-and-continuous-predictor" class="level4">
<h4 class="anchored" data-anchor-id="m4-a-model-with-both-a-dichtomous-and-continuous-predictor"><code>m4</code>: A model with both a dichtomous and continuous predictor</h4>
<p>Now let’s estimate a multiple regression model “controlling” for age</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> interested <span class="sc">+</span> age, nes)</span>
<span id="cb112-2"><a href="#cb112-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) interestedTRUE            age 
    32.1757944      9.7739375      0.3533876 </code></pre>
</div>
</div>
<p>Note the size of the coefficient on <code>interested</code> has decreased, compared to <code>m1</code>. Part of the variation <code>tc_diff</code> explained by <code>interested</code> reflected variation explained by <code>age</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
     47.845 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb116"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m4)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>interestedTRUE 
      9.773938 </code></pre>
</div>
</div>
<ul>
<li>Mechanically, we sometimes say the coefficient on <code>interested</code> shifts the intercept of the line describing the relationship between <code>tc_diff</code> and age.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="m5-a-model-with-an-interaction-between-a-dichtomous-and-continuous-predictor" class="level4">
<h4 class="anchored" data-anchor-id="m5-a-model-with-an-interaction-between-a-dichtomous-and-continuous-predictor"><code>m5</code>: A model with an interaction between a dichtomous and continuous predictor</h4>
<p>What if we think the relationship between <code>age</code> and <code>tc_diff</code> varies depending on a person’s level of political interest?</p>
<p>We could fit an interacton model:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb118"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb118-1"><a href="#cb118-1" aria-hidden="true" tabindex="-1"></a>m5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> interested<span class="sc">*</span>age, nes)</span>
<span id="cb118-2"><a href="#cb118-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       (Intercept)     interestedTRUE                age interestedTRUE:age 
        39.7626421         -6.7040163          0.1822814          0.3396523 </code></pre>
</div>
</div>
<p>Mechanically, R takes the data</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(m5<span class="sc">$</span>model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  tc_diff interested age
1      16      FALSE  19
2      36       TRUE  46
3      20      FALSE  59
4      79       TRUE  55
5      97       TRUE  66
6     100       TRUE  61</code></pre>
</div>
</div>
<p>And creates a model matrix:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">model.matrix</span>(m5))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept) interestedTRUE age interestedTRUE:age
1           1              0  19                  0
2           1              1  46                 46
3           1              0  59                  0
4           1              1  55                 55
5           1              1  66                 66
6           1              1  61                 61</code></pre>
</div>
</div>
</section>
<section id="m5-a-model-with-an-interaction-between-a-dichtomous-and-continuous-predictor-1" class="level4">
<h4 class="anchored" data-anchor-id="m5-a-model-with-an-interaction-between-a-dichtomous-and-continuous-predictor-1"><code>m5</code>: A model with an interaction between a dichtomous and continuous predictor</h4>
<p>This interaction model essentially estimates separate models describing the relationship between <code>tc_diff</code> and <code>age</code> for the uninterested…</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>m5_uninterested <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> age, nes,</span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">subset =</span> interested <span class="sc">==</span> F)</span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5_uninterested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 39.7626421   0.1822814 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   39.76264 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb128"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5)[<span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age 
0.1822814 </code></pre>
</div>
</div>
</section>
<section id="m5-a-model-with-an-interaction-between-a-dichtomous-and-continuous-predictor-2" class="level4">
<h4 class="anchored" data-anchor-id="m5-a-model-with-an-interaction-between-a-dichtomous-and-continuous-predictor-2"><code>m5</code>: A model with an interaction between a dichtomous and continuous predictor</h4>
<p>And interested</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb130"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" aria-hidden="true" tabindex="-1"></a>m5_interested <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> age, nes,</span>
<span id="cb130-2"><a href="#cb130-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">subset =</span> interested <span class="sc">==</span> T)</span>
<span id="cb130-3"><a href="#cb130-3" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5_interested)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)         age 
 33.0586258   0.5219337 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb132"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5)[<span class="dv">1</span>] <span class="sc">+</span><span class="fu">coef</span>(m5)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   33.05863 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb134"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m5)[<span class="dv">3</span>] <span class="sc">+</span><span class="fu">coef</span>(m5)[<span class="dv">4</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      age 
0.5219337 </code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb136"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" aria-hidden="true" tabindex="-1"></a>nes <span class="sc">%&gt;%</span></span>
<span id="cb136-2"><a href="#cb136-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(interested))<span class="sc">%&gt;%</span></span>
<span id="cb136-3"><a href="#cb136-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(age, tc_diff, <span class="at">col =</span> interested))<span class="sc">+</span></span>
<span id="cb136-4"><a href="#cb136-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> .<span class="dv">5</span>, <span class="at">alpha =</span> .<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb136-5"><a href="#cb136-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span><span class="st">"lm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="m6-a-model-with-an-two-continuous-predictors" class="level4">
<h4 class="anchored" data-anchor-id="m6-a-model-with-an-two-continuous-predictors"><code>m6</code>: A model with an two continuous predictors</h4>
<p>Now lets model <code>tc_diff</code> as a function of two predictors: <code>age</code> and <code>income</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a>m6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(tc_diff <span class="sc">~</span> age <span class="sc">+</span> income, nes)</span>
<span id="cb137-2"><a href="#cb137-2" aria-hidden="true" tabindex="-1"></a>m6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tc_diff ~ age + income, data = nes)

Coefficients:
(Intercept)          age       income  
    33.1994       0.4003       0.1573  </code></pre>
</div>
</div>
<p>We interpret this model as saying:</p>
<ul>
<li>Controlling for <code>income</code>, as <code>age</code> increases by 1 we can expect the predicted difference in <code>tc_diff</code> to increase by 0.40</li>
<li>Controlling for <code>age</code>, as <code>income</code> increases by 1 we can expect the predicted difference in <code>tc_diff</code> to increase by 0.16</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-66-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="multiplicative-interactions-with-a-continuous-moderator" class="level2">
<h2 class="anchored" data-anchor-id="multiplicative-interactions-with-a-continuous-moderator">Multiplicative interactions with a continuous moderator</h2>
<p>Suppose we wanted to fit an interaction between two continuous variables like <code>age</code> and <code>income</code>.</p>
<p>The general form of this model is</p>
<p><span class="math display">\[
Y= \beta_0 + \beta_1X + \beta_2 +\beta_3X\times Z + \epsilon
\]</span></p>
<ul>
<li>The marginal effect of X on Y, now depends on the value of Z at which you evaluate the relationship</li>
</ul>
<p><span class="math display">\[
\frac{\partial Y}{\partial X}=\beta_1+\beta_3Z
\]</span></p>
<p>Easier to show this with some simulated data:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-slides_files/figure-html/unnamed-chunk-68-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>class: inverse, middle, center # 💡 ## Reading Regression Tables</p>
</section>
<section id="regression-tables" class="level2">
<h2 class="anchored" data-anchor-id="regression-tables">Regression Tables</h2>
<ul>
<li><p>Academic articles are littered with regression tables.</p></li>
<li><p>Below we’ll see how to produce regression tables in R</p></li>
<li><p>Learn some heuristics for how to interpret regression tables</p>
<ul>
<li>We’ll cover the theory behind these heuristics in the coming weeks</li>
</ul></li>
</ul>
</section>
<section id="making-regression-tables-in-r" class="level2">
<h2 class="anchored" data-anchor-id="making-regression-tables-in-r">Making Regression Tables in R</h2>
<p>We can make a very simple regression table using the <code>htmlreg</code> function from the <code>texreg</code> package</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a>texreg<span class="sc">::</span><span class="fu">htmlreg</span>(</span>
<span id="cb139-2"><a href="#cb139-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">list</span>(m0,m1,m3,m4,m5,m6)</span>
<span id="cb139-3"><a href="#cb139-3" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;"&gt;
&lt;caption&gt;Statistical models&lt;/caption&gt;
&lt;thead&gt;
&lt;tr&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Model 1&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Model 2&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Model 3&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Model 4&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Model 5&lt;/th&gt;
&lt;th style="padding-left: 5px;padding-right: 5px;"&gt;Model 6&lt;/th&gt;
&lt;/tr&gt;
&lt;/thead&gt;
&lt;tbody&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(Intercept)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;53.58&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;47.84&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;40.80&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;32.18&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;39.76&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;33.20&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.92)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(1.26)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(2.35)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(2.71)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(3.62)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(3.35)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;interestedTRUE&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;12.75&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;9.77&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;-6.70&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(1.81)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(1.84)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(5.55)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;pol_interest&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;6.01&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.98)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;age&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.35&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.18&lt;sup&gt;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.40&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.05)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.08)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.06)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;interestedTRUE:age&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.34&lt;sup&gt;&amp;#42;&amp;#42;&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.11)&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;income&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.16&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;&amp;nbsp;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;(0.29)&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-top: 1px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.04&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.03&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.08&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.04&lt;/td&gt;
&lt;/tr&gt;
&lt;tr&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Adj. R&lt;sup&gt;2&lt;/sup&gt;&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.00&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.04&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.03&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.07&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.08&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;0.04&lt;/td&gt;
&lt;/tr&gt;
&lt;tr style="border-bottom: 2px solid #000000;"&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;Num. obs.&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1196&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1168&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1168&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1168&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1168&lt;/td&gt;
&lt;td style="padding-left: 5px;padding-right: 5px;"&gt;1049&lt;/td&gt;
&lt;/tr&gt;
&lt;/tbody&gt;
&lt;tfoot&gt;
&lt;tr&gt;
&lt;td style="font-size: 0.8em;" colspan="7"&gt;&lt;sup&gt;&amp;#42;&amp;#42;&amp;#42;&lt;/sup&gt;p &amp;lt; 0.001; &lt;sup&gt;&amp;#42;&amp;#42;&lt;/sup&gt;p &amp;lt; 0.01; &lt;sup&gt;&amp;#42;&lt;/sup&gt;p &amp;lt; 0.05&lt;/td&gt;
&lt;/tr&gt;
&lt;/tfoot&gt;
&lt;/table&gt;</code></pre>
</div>
</div>
<p>Yuck, we need to set a argument in the chunk header to results=“asis”</p>
<pre><code>
```{r echo=F, results = "asis"}`r`''`
texreg::htmlreg(
  list(m0,m1,m3,m4,m5,m6)
)

```
</code></pre>
<div class="cell" data-layout-align="center">
<table class="texreg" style="margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;">
<caption>
Statistical models
</caption>
<thead>
<tr>
<th style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 1
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 2
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 3
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 4
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 5
</th>
<th style="padding-left: 5px;padding-right: 5px;">
Model 6
</th>
</tr>
</thead>
<tbody>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
(Intercept)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
53.58<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
47.84<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
40.80<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
32.18<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
39.76<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
33.20<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.92)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.26)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(2.35)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(2.71)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(3.62)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(3.35)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
interestedTRUE
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
12.75<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
9.77<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
-6.70
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.81)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(1.84)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(5.55)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
pol_interest
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
6.01<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.98)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.35<sup>***</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.18<sup>*</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.40<sup>***</sup>
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.05)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.08)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.06)
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
interestedTRUE:age
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.34<sup>**</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.11)
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
income
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.16
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
&nbsp;
</td>
<td style="padding-left: 5px;padding-right: 5px;">
(0.29)
</td>
</tr>
<tr style="border-top: 1px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.00
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.07
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.08
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr>
<td style="padding-left: 5px;padding-right: 5px;">
Adj. R<sup>2</sup>
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.00
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.03
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.07
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.08
</td>
<td style="padding-left: 5px;padding-right: 5px;">
0.04
</td>
</tr>
<tr style="border-bottom: 2px solid #000000;">
<td style="padding-left: 5px;padding-right: 5px;">
Num. obs.
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1196
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1168
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1168
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1168
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1168
</td>
<td style="padding-left: 5px;padding-right: 5px;">
1049
</td>
</tr>
</tbody>
<tfoot>
<tr>
<td style="font-size: 0.8em;" colspan="7">
<sup>***</sup>p &lt; 0.001; <sup>**</sup>p &lt; 0.01; <sup>*</sup>p &lt; 0.05
</td>
</tr>
</tfoot>
</table>
</div>
</section>
<section id="interpreting-regression-tables-stargazing" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-regression-tables-stargazing">Interpreting Regression Tables (Stargazing)</h2>
<ul>
<li>Each column is a model</li>
<li>Each row is a coefficient from that model with its <strong>standard error</strong> (more to come) in parantheses below</li>
<li>The bottom of the table shows summary stastitics of the model ( <span class="math inline">\(R^2\)</span> = proportion of variance explained)</li>
<li>Coefficients with asterisks <code>*</code> are <strong>statistically significant</strong>
<ul>
<li>It is unlikely that we would see a coefficient this big or bigger if the true coefficient were 0</li>
</ul></li>
<li>Rule of thumb:</li>
</ul>
<p><span class="math display">\[\text{If }\frac{\beta}{se} &gt; 2 \to \text{Statistically Significant}\]</span></p>
<p>class: inverse, middle, center # 💡 ## Summary</p>
</section>
<section id="summary-1" class="level2">
<h2 class="anchored" data-anchor-id="summary-1">Summary</h2>
<p>Today we estimated and interpreted a series of multiple regression models</p>
<ul>
<li><p>The coefficients in these models still describe slopes (partial derivatives), now for planes (and hyper planes)</p></li>
<li><p>Controlling for variables is easy in <code>lm()</code></p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb142"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb142-1"><a href="#cb142-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data=</span>df)</span>
<span id="cb142-2"><a href="#cb142-2" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> z, <span class="at">data=</span>df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the lab and next week, we will start to explore</p>
<ul>
<li>What it means to “control for x”</li>
<li>How can we compare different models</li>
<li>How can we interpret predictions from multiple regression</li>
</ul>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>If you’re Group 01 don’t change your name to Group 4<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>