{
  "hash": "5737d2635992bcfd1436f1bffc0aaf8c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"POLS 1600\"\nsubtitle: \"Presentations\"\ndate: last-modified\ndate-format: \"[Updated ]MMM D, YYYY\"\nformat: \n  revealjs:\n    theme: brownslides.scss\n    logo: images/pols1600_hex.png\n    footer: \"POLS 1600\"\n    multiplex: false\n    transition: fade\n    slide-number: c\n    incremental: true\n    center: false\n    menu: true\n    scrollable: true\n    highlight-style: github\n    progress: true\n    code-overflow: wrap\n    html-math-method: mathjax\n    chalkboard: true\n    # include-after-body: title-slide.html\n    title-slide-attributes:\n      align: left\n      data-background-image: images/pols1600_hex.png\n      data-background-position: 90% 50%\n      data-background-size: 40%\nfilters:\n  - openlinksinnewpage\n  - webr\nwebr:\n  packages: ['dplyr',\"ggplot2\"]\n  autoload-packages: true\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  message: false\n  cache: false\n---\n\n::: {.cell}\n\n:::\n\n\n\n\n\n# {{< fa map-location>}} Overview {.inverse}\n\n## Class Plan\n\n- Announcements\n- Presentations\n- Workshop / Review\n  - Predicted values from linear models\n- Final Projects\n\n\n## Annoucements\n\n- Lab 11/[Assignment 3](https://pols1600.paultesta.org/assignments/a3) this week\n- Next Tuesday, April 22, Work on Presentations/Drafts\n- [Assignment 4](https://pols1600.paultesta.org/assignments/a3) now due April 25.\n- April 29, Final Workshop \n- May 1   Class Presentations\n\n\n## Setup: Packages for today\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Pacakges for today\nthe_packages <- c(\n  ## R Markdown\n  \"kableExtra\",\"DT\",\"texreg\",\"htmltools\",\n  ## Tidyverse\n  \"tidyverse\", \"lubridate\", \"forcats\", \"haven\", \"labelled\",\n  ## Extensions for ggplot\n  \"ggmap\",\"ggrepel\", \"ggridges\", \"ggthemes\", \"ggpubr\", \n  \"patchwork\",\n  \"GGally\", \"scales\", \"dagitty\", \"ggdag\", \"ggforce\",\n  # Data \n  \"COVID19\",\"maps\",\"mapdata\",\"qss\",\"tidycensus\", \"dataverse\", \n  # Analysis\n  \"DeclareDesign\", \"easystats\", \"zoo\"\n)\n\n## Define a function to load (and if needed install) packages\n\nipak <- function(pkg){\n    new.pkg <- pkg[!(pkg %in% installed.packages()[, \"Package\"])]\n    if (length(new.pkg)) \n        install.packages(new.pkg, dependencies = TRUE)\n    sapply(pkg, require, character.only = TRUE)\n}\n\n## Install (if needed) and load libraries in the_packages\nipak(the_packages)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   kableExtra            DT        texreg     htmltools     tidyverse \n         TRUE          TRUE          TRUE          TRUE          TRUE \n    lubridate       forcats         haven      labelled         ggmap \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      ggrepel      ggridges      ggthemes        ggpubr     patchwork \n         TRUE          TRUE          TRUE          TRUE          TRUE \n       GGally        scales       dagitty         ggdag       ggforce \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      COVID19          maps       mapdata           qss    tidycensus \n         TRUE          TRUE          TRUE          TRUE          TRUE \n    dataverse DeclareDesign     easystats           zoo \n         TRUE          TRUE          TRUE          TRUE \n```\n\n\n:::\n:::\n\n\n\n# {{< fa magnifying-glass>}} Presentations {.inverse}\n\n## Presentations {.smaller}\n\n- Motivation\n\n- Research Question\n\n- Theory\n\n- Expectations\n\n- Data\n\n  - Summary\n\n  - Descriptive Table and/or Figure (Optional)\n\n- Design\n\n- Results\n\n  - Summary\n\n  - Table (Optional)\n\n  - Figure (Optional)\n\n- Conclusion\n\n-   Appendices (Extra Slides Optional)\n\n## Template\n\nLet's open up the [template](https://pols1600.paultesta.org/assignments/a5) and explore.\n\n\n# {{< fa magnifying-glass>}} Review {.inverse}\n\n## Three Modes of Inference\n\n- Descriptive\n\n- Causal\n\n- Predictive\n\n## Descriptive Inference {.smaller}\n\n> Summarize distributions and relationships in data\n\n- You should know how to:\n  - [Calculate](https://pols1600.paultesta.org/slides/01-slides#/using-r-to-summarize-data) and interpret measures: \n  - Central Tendency\n  - Dispersion\n  - Association\n- [Load](https://pols1600.paultesta.org/slides/01-slides#/loading-data-into-r), [look at](https://pols1600.paultesta.org/slides/01-slides#/looking-at-your-data), [wrangle](https://pols1600.paultesta.org/slides/01-slides#/dplyr-functions-for-data-wrangling), and [describe](https://pols1600.paultesta.org/slides/01-slides#/describing-data-in-r) data using:\n  - Tables\n  - Figures\n  \n## Data Wrangling {.smaller}\n\n> The process of transforming data into a useable format\n\nYou should know how to:\n\n- Load, look at,and transform data into R\n- Get a [HLO](https://pols1600.paultesta.org/slides/01-slides#/hlos-allow-you-to) of the raw data:\n  - Unit of observation\n  - Dimensions of the data\n  - Quickly summarize the distributions and values of variables\n- [Recode](https://pols1600.paultesta.org/labs/09-lab-comments#recode-the-data) the data to:\n  - Replace values as `NA`s\n  - Create categories, indicators (0,1), and factors\n  - Transform predictors (e.g. standardizing predictors)\n- Reshape the data\n  - Pivoting columns and rows\n  - Joining data sets together.\n- [Aggregate](https://pols1600.paultesta.org/labs/02-lab-comments#reproduce-the-figure-from-lab-01) the data into [summaries](https://pols1600.paultesta.org/labs/03-lab-comments#calculate-the-average-treatment-effect)\n  \n## Data Visualization{.smaller}\n\n> A tool for describing distributions and relationships\n\nYou should know:\n\n- The [grammar of graphics](https://pols1600.paultesta.org/slides/02-slides#/the-grammar-of-graphics):\n  - Data\n  - Aesthetic mappings\n  - Geometries\n- How to [generate common plots](https://pols1600.paultesta.org/slides/02-slides#/describing-distributions-and-associations) to describe:\n  - Distributions\n  - Relationships\n  \n## Causal Inference{.smaller}\n\n> Causal Inference requires counterfactual comparisons\n\nYou should know:\n\n- [Potential outcomes](https://pols1600.paultesta.org/slides/03-slides#/potential-outcomes-notation) and [DAGs](https://pols1600.paultesta.org/slides/05-slides#/directed-acyclic-graphs-1)\n\n- The [fundamental problem of causal inference](https://pols1600.paultesta.org/slides/03-slides#/fundamental-problem-of-causal-inference)\n\n- Bias caused by:\n  - [Confounding](https://pols1600.paultesta.org/slides/05-slides#/section-1) (Coffee and Cancer)\n  - [Colliding](https://pols1600.paultesta.org/slides/05-slides#/section-2) (Dating Jerks)\n- Casual Identification in:\n  - [Experimental](https://pols1600.paultesta.org/slides/03-slides#/causal-identification-with-experimental-designs) designs\n  - [Observational](https://pols1600.paultesta.org/slides/05-slides#/observational-designs) designs \n  \n## Prediction with Linear Models {.smaller}\n\n> Linear regression provides a linear estimate of the conditional expectation function \n\nYou should know:\n\n- [How linear regression works](https://pols1600.paultesta.org/slides/05-slides#/understanding-linear-regression)\n\n- [What it means to control for](https://pols1600.paultesta.org/slides/07-slides.html#/regression-models-partition-variance) predictors in a multiple regression\n\n- When and [why we should control](https://pols1600.paultesta.org/slides/05-slides#/when-to-control-for-a-variable) for predictors.\n\n- How to translate [substantive claims]{.blue} into [empirical expectations](https://pols1600.paultesta.org/labs/06-lab-comments#estimate-a-model-controlling-for-age) for our models\n\n- How to [estimate and interpret]{.blue} these models using [tables](https://pols1600.paultesta.org/labs/06-lab-comments#display-the-model-as-a-regression-table) and [figures](https://pols1600.paultesta.org/labs/10-lab-comments#visualize-predicted-values)\n\n- How to [quantify uncertainty]{.blue} about these estimates using [confidence intervals](https://pols1600.paultesta.org/slides/10-slides#/confidence-intervals-1) and [hypothesis tests](https://pols1600.paultesta.org/slides/10-slides#/what-is-a-hypothesis-test).\n\n\n# {{< fa lightbulb>}} Quantifying Uncertainty {.inverse}\n\n## Probability {.smaller}\n\n- [Probability](https://pols1600.paultesta.org/slides/08-slides#/probability-1) describes the likelihood of an event\n\n- [Random variables](https://pols1600.paultesta.org/slides/08-slides#/random-variables) assign numeric values to all the events that could occur.\n\n- [Probability distributions](https://pols1600.paultesta.org/slides/08-slides#/probability-distributions) assign probabilities to every value of a random variable. Can be:\n\n  - discrete\n  - continuous\n  - characterized by their expected values and variances\n  - used to:\n  - describe the [data generating process]{.blue}\n  - [quantify uncertainty]{.blue} about estimates\n\n\n## Sampling Distributions and Standard Errors {.smaller}\n\n- A sampling distribution is a theoretical probability distribution of estimates obtained from taking repeated samples of size $n$ from some population\n\n  - A distribution of what we could have seen\n\n- A standard error is simply the standard deviation ($\\sigma$) of the sampling distribution\n\n  - A measure of how much our estimate could have varied.\n\n- Law of Large Numbers: As $N \\to \\infty$ $\\bar{x} \\to \\mu$\n- Central Limit Theorem: As $N \\to \\infty$ $\\bar{x} \\sim \\mathcal{N}(\\mu, \\sigma^2)$\n\n## Confidence Intervals {.smaller}\n\n> Confidence intervals provide a range of plausible values for our estimate\n\n- Three components:\n  - Point Estimate (i.e. a mean, or coefficient)\n  - Confidence Level (Often 95 percent by convention)\n  - Margin of Error (+/- some range (typically 2\\*SD for 95 percent CI))\n- Confidence is about the interval\n  - 95 percent of the intervals construct in this manner would contain the truth.\n\n## Hypothesis Testing {.smaller}\n\n- A hypothesis test quantifies how likely it is that we would observe what we did (our test statistic), if some claim about the world were true (our hypothesis, typically a null ).\n\n- If our claim were true, then [under this null hypothesis]{.blue}, our test statistic would have a distribution centered around the truth.\n\n- A [p-value]() which describes the probability of observing a test statistic as extreme or more extreme in a world where our null hypothesis was true\n\n  - If our [p-value is small]{.blue} ($p < 0.05$), we [reject the null]{.blue} hypothesis\n\n     If our [p-value is large]{.blue} ($p > 0.05$), we [fail to reject the null]{.blue}, or retain the null hypothesis\n\n\n## {.smaller}\n#### Relationship between CIs and Hypothsis Testing\n\n:::: panel-tabset\n## Concept\n\nWe can think of a confidence interval as a [range of hypotheses we would fail to reject]{.blue} with $p < \\alpha$\n\n\n\n## {{<fa code>}} Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Data\nload(url(\"https://pols1600.paultesta.org/files/data/nes24.rda\"))\n\n# Fit Model\nm1 <- lm_robust(dv_participation ~   education + income, df,\n                se = \"classical\")\n\n# Range of hypotheses for education\npval_ci_df <- tibble(\n  # Hypothesized Betas for Education\n  Hypothesis = seq(0, .32, length.out = 100),\n  # Test Statistics\n  Statistic = (m1$coefficients[\"education\"] - Hypothesis) /\n  m1$std.error[\"education\"],\n  # P-value for two sided test\n  `p-value` = 2*pt(abs(Statistic), df = m1$df,lower.tail = F)\n)\n\nfig_pval_ci <- pval_ci_df %>% \n  ggplot(aes(Hypothesis, `p-value`))+\n  geom_line()+\n  geom_vline(xintercept = m1$coefficients[\"education\"],\n             linetype = \"solid\",\n             col = \"red\")+\n  geom_vline(xintercept = m1$conf.low[\"education\"],\n             linetype = \"dotted\")+\n  geom_vline(xintercept = m1$conf.high[\"education\"],\n             linetype = \"dotted\")+\n  geom_hline(yintercept = 0.05,\n             linetype = \"dashed\")+\n  labs(\n    x = \"Hypothesized Education, Coefficent\",\n    title = \"Confidence intervals are a range\\nof plausible hypotheses\"\n  )+\n  theme_minimal()\n```\n:::\n\n\n\n## {{<fa table>}} Table\n\n\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.31<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.14; 0.48]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">education</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.17<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.12; 0.21]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">income</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.01</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[-0.01; 0.03]</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">1687</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">RMSE</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">1.29</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"2\"><sup>&#42;</sup> 0 outside the confidence interval.</td>\n</tr>\n</tfoot>\n</table>\n\n\n\n\n## {{<fa chart-line>}} Figure\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/fig_pval_ci-1.png){width=960}\n:::\n:::\n\n\n\n::::\n\n## Four Possible Outcomes of a hypothesis Test {.smaller}\n\n::::{.columns}\n\n:::{.column width=45%}\n\n- **False Positive: (Type I Error)** \n  - Rejecting a True $H_0$.\n  - $\\tau = 0$, but $\\hat{\\tau}$ has a $p<0.05$\n  - Probability=$\\alpha$\n\n- **True Positive: (Correct Decision)** \n  - Rejecting a false $H_0$: \n  - $\\tau \\neq 0$, and  $\\hat{\\tau}$ has a $p<0.05$\n  - Occurs with Probability = $1-\\beta$\n\n\n:::\n\n\n:::{.column width=45%}\n\n- **True Negative: (Correct Decision) ** \n  - Failing to reject a True $H_0$: \n  - $\\tau = 0$, and $\\hat{\\tau}$ has a $p>0.05$\n  - Occurs with Probability = $1-\\alpha$\n\n- **False Negative: (Type II Error)** \n  - Failing to reject a false $H_0$. \n  - $\\tau \\neq 0$ but $\\hat{\\tau}$ has a $p>0.05$\n  - Occurs with Probability= $\\beta$\n\n:::\n\n::::\n\n## Type 1 and 2 Errors\n\n![](https://miro.medium.com/max/1400/1*uF5aBZ63BZ8IDEyF8wo-CA.png)\n\n[Source](https://towardsdatascience.com/a-general-guidance-of-hypothesis-testing-7cab119ca999)\n\n## Statistical Power{.smaller}\n\n```{webr-r}\n#| label: plot_power\n#| context: setup\n\npower_function <- function(tau = 2, se =1, pval = 0.05){\n  df <- tibble(\n    x = seq(-4*se, tau+4*se,length.out = 100 ),\n    p = dnorm(x, mean = 0, sd = se)\n  )\n  the_x_min <- min(c(min(df$x), -5))\n  the_x_max <- max(max(df$x), 7)\n  the_y_max <- max(df$p)\n  \n  z <- qnorm(1-(pval/2), sd = se)\n  power <- pnorm(z, mean = tau, sd =se, lower.tail = F)\n  type2_error <- pnorm(z, mean = tau, sd =se)\n  if(power > type2_error){\n    the_y_power <- dnorm(z, mean = tau, sd = se)*.7\n    the_y_type2 <- dnorm(z, mean = tau, sd = se)*.3\n  }\n  if(power <= type2_error){\n    the_y_power <- dnorm(z, mean = tau, sd = se)*.3\n    the_y_type2 <- dnorm(z, mean = tau, sd = se)*.7\n  }\n\n  \n  fig_power <- df %>% \n    ggplot(aes(x))+\n    ylim(0,the_y_max + the_y_max/10)+\n    xlim(the_x_min, the_x_max)+\n    stat_function(geom = \"line\", fun = dnorm,\n                args = list(sd = se),\n                alpha = 0.5)+\n    stat_function(geom = \"line\", fun = dnorm,\n                alpha = 0.5,\n                col = \"blue\",\n                args =list(mean = tau, sd = se))+\n    stat_function(geom = \"area\", fun = dnorm,\n                fill = \"darkblue\",\n                alpha = 0.5,\n                xlim = c(the_x_min,qnorm(1-(pval/2),sd = se)),\n                args =list(mean = tau, sd = se))+\n    stat_function(geom = \"area\", fun = dnorm,\n                fill = \"lightblue\",\n                alpha = 0.7,\n                xlim = c(qnorm(1-(pval/2), sd = se),the_x_max),\n                args =list(mean = tau, sd = se))+\n    stat_function(geom = \"area\", fun = dnorm,\n                fill = \"red\",\n                alpha = .25,\n                xlim = c(qnorm(1-(pval/2), sd = se),the_x_max),\n                args =list(mean = 0, sd = se)\n                )+\n    stat_function(geom = \"area\", fun = dnorm,\n                fill = \"red\",\n                alpha = .5,\n                xlim = c(qnorm(pval/2,sd = se),the_x_min),\n                args =list(mean = 0, sd = se)\n                )+\n    geom_vline(xintercept = qnorm(1-(pval/2),sd = se), linetype =2)+\n    geom_segment(\n      data = tibble(x = 0,\n           xend= tau,\n           y = the_y_max,\n           yend = the_y_max),\n      aes(x = x, xend = xend, \n          y=y, yend=yend)\n      )+\n    annotate(\"text\", x = tau/2, y = the_y_max + the_y_max/40, \n             label = expression(tau), hjust=.5)+\n    annotate(\"text\", x = -z-se/10, y = the_y_max*.02, \n             label = expression(\n               paste(alpha,\"/2\", sep =\"\")), hjust=1\n             )+\n    annotate(\"text\", x = z+se/10, y = the_y_max*.02, \n             label = expression(\n               paste(alpha,\"/2\", sep =\"\")), hjust=0\n             )+\n  annotate(\"text\", x = z-se/8, y = the_y_type2-the_y_max/20, label = expression(beta), hjust=1) +\n  annotate(\"text\", x = z-se/8, y = the_y_type2, label = \"Type II-Error\", hjust=1)+\n  annotate(\"text\", x = z+se/8, y = the_y_power, label = paste( \"Statistical Power = \", round(power,2),sep = \"\"), hjust=0)+\n  annotate(\"text\", x = z+se/8, y = the_y_power-the_y_max/20, label = expression(paste(\"1-\",beta,sep=\"\")), hjust=0)+\n\n  annotate(\"text\", x = 0, y = the_y_max + the_y_max/40, label = expression(H[0]), hjust=0.5)+\n  annotate(\"text\", x = tau, y = the_y_max + the_y_max/40, label = expression(H[1]), hjust=0.5)+\nannotate(\"text\", x = z+se/8, y = the_y_max + the_y_max/10, label = \"z=critical value\", hjust=0)+\n    theme_void()\n\n  \n  return(fig_power)\n}\n\n```\n\n:::: panel-tabset\n\n## Concept\n\n:::{.nonincremental}\n\n- Consider two distributions of statistics under \n  - a null of no effect ($H_0$) \n  - an effect of $\\tau$ ($H_1$)\n- For a significance threshold of $\\alpha$ we would:\n  - Fail to reject the null $\\beta$  (Type II Errors)\n  - Correctly reject the null $1 -\\beta$ (Statistical Power)\n\n:::\n\n## Power\n\nTry changing $\\tau$ (the effect size), and se (the standard deviation of the effect)\n\n```{webr-r}\n#| label: power\n#| autorun: true\n#| context: interactive\n#| message: false\npower_function(tau = 2, se = 1, pval = 0.05)\n```\n\n## Comments\n\nPower is a function of:\n\n- Sample size ($N$)\n  - Larger samples, smaller standard errors (LLN)\n\n- Effect size ($\\tau$)\n  - Bigger effects less overlap\n  \n- Significance threshold ($\\alpha$)\n  - Decrease Type 1 (False Positives) error leads to increased Type 2 (False Negatives)\n  \n- The distribution of the data \n  - Variance, asympotitc approximations\n  \n::::\n\n# {{< fa lightbulb>}} Final Projects {.inverse}\n\n## Strucutre of Final Paper and Drafts {.smaller}\n\n[Assignment 4:](https://pols1600.paultesta.org/assignments/a4) Seven sections\n\n1.  Introduction (5 percent, \\~ 4 paragraphs)\n2.  Theory and Expectations (10 percent, \\~4+ paragraphs)\n3.  Data (20 percent \\~ 4+ paragraphs)\n4.  Design (25 percent \\~ 5+ paragraphs)\n5.  Results (25 percent \\~ 5+ paragraphs)\n6.  Conclusion (5 percent \\~ 3+ paragraphs)\n7.  Appendix (10 percent \\~ Variable codebook and all the R code for your project)\n\n## For Thursday {.smaller}\n\n- [Assignment 3](https://pols1600.paultesta.org/assignments/a3)\n\n- [Download template](https://pols1600.paultesta.org/assignments/pols1600_paper_template.qmd)\n\n- Create shared google drive.\n\n- Make progress on:\n  - 3.  **Data** (20 percent \\~ 4+ paragraphs)\n  - 4.  *Design* (25 percent \\~ 5+ paragraphs)\n  - 5.  **Results** (25 percent \\~ 5+ paragraphs)\n\n## Motivating Questions {.smaller}\n\nIn the reset of today's class, we'll get some practice putting together the various skills you need for your drafts by exploring the following:\n\n- How does partisanship shape American's perceptions of vaccines?\n\n- Who is skeptical of the benefits of vaccination?\n\n- Have these perceptions about vaccines changed over time?\n\n## Tasks:{.smaller}\n\nTo explore these questions, we need to\n\n- Get setup to work\n\n- Load our data\n\n- Recode our data\n\n- Summarize our data\n\n- Specify our expectations\n\n- Estimate models to test these expectations\n\n- Present and interpret results using\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis tests \n\n## New packages\n\nTo easily load survey data for our question, we'll need the `anesr` package, which loads data from the American National Election Studies into R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# # Uncomment to uninstall package to download NES survey data\n# library(devtools)\n# install_github(\"jamesmartherus/anesr\")\nrequire(anesr)\n```\n:::\n\n\n\n## Packages for today\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Pacakges for today\nthe_packages <- c(\n  ## R Markdown\n  \"kableExtra\",\"DT\",\"texreg\",\"htmltools\",\n  ## Tidyverse\n  \"tidyverse\", \"lubridate\", \"forcats\", \"haven\", \"labelled\",\n  ## Extensions for ggplot\n  \"ggmap\",\"ggrepel\", \"ggridges\", \"ggthemes\", \"ggpubr\", \n  \"patchwork\",\n  \"GGally\", \"scales\", \"dagitty\", \"ggdag\", \"ggforce\",\n  # Data \n  \"COVID19\",\"maps\",\"mapdata\",\"qss\",\"tidycensus\", \"dataverse\", \n  # Analysis\n  \"DeclareDesign\", \"easystats\", \"zoo\"\n)\n\n## Define a function to load (and if needed install) packages\n\nipak <- function(pkg){\n    new.pkg <- pkg[!(pkg %in% installed.packages()[, \"Package\"])]\n    if (length(new.pkg)) \n        install.packages(new.pkg, dependencies = TRUE)\n    sapply(pkg, require, character.only = TRUE)\n}\n\n## Install (if needed) and load libraries in the_packages\nipak(the_packages)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   kableExtra            DT        texreg     htmltools     tidyverse \n         TRUE          TRUE          TRUE          TRUE          TRUE \n    lubridate       forcats         haven      labelled         ggmap \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      ggrepel      ggridges      ggthemes        ggpubr     patchwork \n         TRUE          TRUE          TRUE          TRUE          TRUE \n       GGally        scales       dagitty         ggdag       ggforce \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      COVID19          maps       mapdata           qss    tidycensus \n         TRUE          TRUE          TRUE          TRUE          TRUE \n    dataverse DeclareDesign     easystats           zoo \n         TRUE          TRUE          TRUE          TRUE \n```\n\n\n:::\n:::\n\n\n\n## Data {.smaller}\n\nNow that we have `anesr` installed, let's load data from the 2016 and 2020 National Election Studies:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load data\ndata(timeseries_2016, package = \"anesr\")\ndata(timeseries_2020, package = \"anesr\")\n```\n:::\n\n\n\nAnd copy those data frames into new dataframes with shorter names\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Rename datasets\nnes16 <- timeseries_2016\nnes20 <- timeseries_2020\n```\n:::\n\n\n\n## Finding variables: Outcomes {.smaller}\n\nOur primary outcome of interest are beliefs about vaccines.\n\nVariables `V162162x` in the 2016 NES and `V202383x` in the 2020 NES will serve as our primary outcome of interest, summarizing respondents answer to the following question:\n\n> Do the health benefits of vaccinations generally outweigh the risks, do the risks outweigh the benefits, or is there no difference?\n\n## Finding variables: Predictors {.smaller}\n\nSimilarly, `V161158x` in the 2016 NES and `V201231x` in the 2020 NES will serve our key predictor (respondent's partisanship).\n\nFinally, we'll control respondents' age, using `V161267` in the 2016 NES and `V201507x` in the 2020 NES\n\n\n## Examine Distributions: Vaccine Beliefs {.smaller}\n\nThe variables in the NES datasets are of a class `labelled` which allows numeric values to have substantive labels\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclass(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"haven_labelled\"\n```\n\n\n:::\n:::\n\n\n\nOur outcome variable has the following labels:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlabelled::val_labels(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                   -9. Refused \n                                            -9 \n                                -8. Don't know \n                                            -8 \n-7. No post data, deleted due to incomplete IW \n                                            -7 \n                -6. No post-election interview \n                                            -6 \n                      1. Benefits much greater \n                                             1 \n                2. Benefits moderately greater \n                                             2 \n                  3. Benefits slightly greater \n                                             3 \n                              4. No difference \n                                             4 \n                     5. Risks slightly greater \n                                             5 \n                   6. Risks moderately greater \n                                             6 \n                         7. Risks much greater \n                                             7 \n```\n\n\n:::\n:::\n\n\n\nAnd distribution of responses:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  -9   -8   -7   -6    1    2    3    4    5    6    7 \n  21   28   86  536 1687  726  258  539   96  211   82 \n```\n\n\n:::\n:::\n\n\n\n## Recoding outcome variables\n\n:::: panel-tabset\n\n## Tasks\n\nWhat transformations do we need to make to `V162162x` in `nes16` and `V202383x` in `nes20` so that these variables are suitable for analysis?\n\n\n- Recode negative values to be `NA`\n\n- Reverse code so that higher values indicate greater belief vaccines benefits\n\n- Create an indicator of people who are vaccine skeptics\n\n## {{< fa code >}} Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnes16 %>%\n  mutate(\n    # Make Negative values NA, Reverse Code So Higher Values = Benefits > Risks\n    vaccine_benefits = ifelse(V162162x < 0, NA, (V162162x-8)*-1),\n    # Indicator of vaccine skepticism (Risks > Benefits)\n    vaccine_skeptic01 = case_when(\n      vaccine_benefits > 4 ~ 0,\n      vaccine_benefits <= 4 ~ 1,\n      TRUE ~ NA_real_\n    )\n  ) -> nes16 # Save recodes to nes16\n\nnes20 %>%\n  mutate(\n    # Make Negative values NA, Reverse Code So Higher Values = Benefits > Risks\n    vaccine_benefits = ifelse(V202383x < 0, NA, (V202383x-8)*-1),\n    # Indicator of vaccine skepticism (Risks > Benefits)\n    vaccine_skeptic01 = case_when(\n      vaccine_benefits > 4 ~ 0,\n      vaccine_benefits <= 4 ~ 1,\n      TRUE ~ NA_real_\n    )\n  ) -> nes20 # Save recodes to nes20\n```\n:::\n\n\n\n::::\n\n## Recoding Predictors\n\n:::: panel-tabset\n\n## Tasks\n\n:::{.nonincremental}\n\nNow we repeat this process for our key predictor, partisanship.\n\n- Recode partisanship variables `V161158x` in `nes16` and `V201231x` in `nes20`\n\n- Create indicators from this recoded variable that classify partisanship as categorical variable (with Democrats as the reference category)\n\nAnd our covariate, age variables `V161267` in `nes16` and `V201507x` in `nes20`\n\n- Recode negative values to be `NA`\n\n:::\n\n## {{<fa code >}} Code \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnes16 %>%\n  mutate(\n    pid = ifelse(V161158x < 0, NA, V161158x),\n    pid3cat = case_when(\n      pid < 4 ~ \"Democrat\",\n      pid == 4 ~ \"Independent\",\n      pid > 4 ~ \"Republican\",\n      TRUE ~ \"Independent\"\n    ) %>% factor(., levels = c(\"Democrat\",\"Independent\",\"Republican\")),\n    age = ifelse(V161267 < 0, NA, V161267)\n  ) -> nes16\n\n## Recoding Partisanship (V201231x) in 2020 NES\n\nnes20 %>%\n  mutate(\n    pid = ifelse(V201231x < 0, NA, V201231x),\n    pid3cat = case_when(\n      pid < 4 ~ \"Democrat\",\n      pid == 4 ~ \"Independent\",\n      pid > 4 ~ \"Republican\",\n      TRUE ~ \"Independent\"\n    ) %>% factor(., levels = c(\"Democrat\",\"Independent\",\"Republican\")),\n    age = ifelse(V201507x < 0, NA, V201507x)\n  ) -> nes20\n```\n:::\n\n\n\n::::\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- **Summarize our data**📥\n\n- Specify our expectations\n\n- Estimate models to test these expectations\n\n- Presenting and interpreting results using\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis tests \n\n\n## Descriptive statistics (2016) {.smaller}\n\n:::: panel-tabset\n\n## Tasks \n\n1.  Create `the_vars`\n\n2.  Select these variables\n\n3.  Pivot the data\n\n4.  Calculate summary statistics\n\n5.  Format as an html table\n\n## {{< fa code >}} Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Create a object with the names of the variables you want to summarize\nthe_vars <- c(\"vaccine_skeptic01\",\"pid\",\"age\")\n# 2. Select these variables\nnes16 %>%\n  select(all_of(the_vars)) %>%\n# 3. Pivot the data\n  pivot_longer(\n    cols = all_of(the_vars),\n    names_to = \"Variable\"\n  )%>%\n  mutate(\n    Variable = factor(Variable, levels = the_vars)\n  )%>%\n  arrange(Variable)%>%\n  dplyr::group_by(Variable)%>%\n  # 3. Calculate summary statistics\n  dplyr::summarise(\n    min = min(value, na.rm=T),\n    p25 = quantile(value, na.rm=T, prob = 0.25),\n    Median = quantile(value, na.rm=T, prob = 0.5),\n    mean = mean(value, na.rm=T),\n    p75 = quantile(value, na.rm=T, prob = 0.25),\n    max = max(value, na.rm=T),\n    missing = sum(is.na(value))\n  ) -> sum_df \n\nsum_tab <- \nknitr::kable(sum_df,\n             caption = \"Descriptive Statistics\",\n             digits = 2) %>%\n  kableExtra::kable_styling() %>%\n  kableExtra::pack_rows(\"Outcome\", start_row = 1, end_row =1) %>%\n  kableExtra::pack_rows(\"Key Predictors\", start_row = 2, end_row =2) %>%\n  kableExtra::pack_rows(\"Covariates\", start_row = 3, end_row =3)\n```\n:::\n\n\n\n## {{<fa table >}} Table\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Descriptive Statistics</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> min </th>\n   <th style=\"text-align:right;\"> p25 </th>\n   <th style=\"text-align:right;\"> Median </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> p75 </th>\n   <th style=\"text-align:right;\"> max </th>\n   <th style=\"text-align:right;\"> missing </th>\n  </tr>\n </thead>\n<tbody>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Outcome</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> vaccine_skeptic01 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.26 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 671 </td>\n  </tr>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Key Predictors</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> pid </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 3.86 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n  </tr>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Covariates</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> age </td>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 50 </td>\n   <td style=\"text-align:right;\"> 49.58 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 90 </td>\n   <td style=\"text-align:right;\"> 121 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::::\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- *Summarize our data* ✅\n\n- **Specify our expectations** 📥\n\n- Estimate models to test these expectations\n\n- Presenting and interpreting results using\n\n  - Tables\n  - Figures\n  - Confidence intervals (review)\n  - Hypothesis tests (new!)\n\n## Specificying Expecations {.smaller}\n\n:::{.nonincremental}\n\nConsider our first two motivating questions\n\n- How does partisanship shape American's perceptions of vaccines?\n\n- Who is skeptical of the benefits of vaccination?\n\nAnd some illustrative stereotypes:\n\n- \"Republicans are *anti-science*\"\n- \"Liberal always fall for Goopy *pseudo-science*\"\n- \"Independents love to *do their own research*\"\n\nWhat are the empirical implications of these claims?\n\n:::\n\n## Specificying Expecations {.smaller}\n\n:::{.nonincremental}\n\nSimilarly, consider our third question:\n\n- Have these perceptions about vaccines changed over time?\n\nAnd some similar simplified claims:\n\n- \"The Covid-19 vaccine is a miracle of modern science\"\n- \"Social media is rife with misinformation about the Covid-19 vaccine\"\n- \"Politicians are politicizing vaccine politics for political benefits\"\n\nWhat are the empirical implications of these claims?\n\n:::\n\n## Specificying Expecations {.smaller}\n\nOur goal is to take claims/conventional wisdom/theories, and derive their empirical implications:\n\n- **H1: Partisan Differences in Vaccine Skepticism**\n  - **H1a:** Republicans will be the most skeptical of vaccines\n  - **H1b:** Democrats will be the most skeptical of vaccines\n  - **H1c:** Independents will be the most skeptical of vaccines\n  \n## Specificying Expecations {.smaller}\n\n\n- **H2: Temporal Differences in Vaccine Skepticism**\n  - **H2a:** Vaccine skepticism will decrease from 2016 to 2020 with the widespread roll out of the Covid-19 vaccine\n  - **H2b:** Vaccine skepticism will increase from 2016 to 2020 with increased amounts of misinformation about the Covid-19 vaccine\n  \n- **H3: Partisan Difference in Vaccine Skepticism Over Time** Partisan differences in Vaccine Skepticism will increase from 2016 to 2020 with the politicization of Covid-19 policies\n\n## Motivating your expectations {.smaller}\n\nIn your final papers, unlike in these slides, your expectations should be grounded in existing theory, research, and evidence. For the present question, we might cite sources such as:\n\n- Enders, Adam M., and Steven M. Smallpage. \"Informational cues, partisan-motivated reasoning, and the manipulation of conspiracy beliefs.\" Political Communication 36.1 (2019): 83-102.\n\n- Stecula, Dominik A., and Mark Pickup. \"How populism and conservative media fuel conspiracy beliefs about COVID-19 and what it means for COVID-19 behaviors.\" Research & Politics 8.1 (2021): 2053168021993979.\n\n- Jennings, Will, et al. \"Lack of trust, conspiracy beliefs, and social media use predict COVID-19 vaccine hesitancy.\" Vaccines 9.6 (2021): 593.\n\n- Hollander, Barry A. \"Partisanship, individual differences, and news media exposure as predictors of conspiracy beliefs.\" Journalism & Mass Communication Quarterly 95.3 (2018): 691-713.\n\n## Model Specification {.smaller}\n\nTranslate these expectations into empirical models requires choices about **how to specify our models**\n\n- How should we measure/operationalize our outcome\n\n  - Should we measure beliefs about vaccines with 7-point ordinal scale or as a binary indicator of vaccine skepticism\n\n- How should we measure/operationalize our key predictor(s)\n\n  - Should we measure partisanship using a 7 point scale or as categorical variable?\n\n- What should we control for in our model?\n\n  - Factors likely to predict both our outcome and our key predictor of interest\n\n- There are rarely *definitive* answers to these questions. Instead, we will often estimate **multiple models** to try and show that our findings are **robust** to alternative specifications\n\n## Model Specification {.smaller}\n\nFor your projects, every group will almost surely estimate some form of the following:\n\n1.  Baseline bivariate model: The simplest test of the relationship between your outcome and key predictor\n\n2.  Multiple regression model: A test of the robustness of this relationship, controlling for alternative explanations\n\n## Model Specification {.smaller}\n\nIn practice, I suspect you may estimate multiple regression models such as:\n\n- Alternative specifications/operationalizations of outcomes and predictors\n\n- Interaction models to test conditional relationships\n\n- Polynomial models to test non-linear relationships\n\n## {.smaller}\n#### Translating Theoretical Claims into Empirical Expectations\n\nBefore we estimate our models in R, we will write down our models formally and empirical implications of our theoretical expectations in terms of the coefficients of our model.\n\nFor example, our baseline model might be:\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{7pt} + X\\beta + \\epsilon$$ \n\nIf $\\beta_1$ is positive this is consistent with **H1a** (greater skepticism among Republicans), - If $\\beta_2$ is negative this is consistent with **H1b** (greater skepticism among Democrats),\n\n- But how could we test **H1c** -- greater skepticism among Independents, who are \"4s\" on $\\text{PID}_{7pt}$?\n\n## {.smaller}\n#### Translating Theoretical Claims into Empirical Expectations\n\nWe could fit a polynomial regression, including both partisanship and \"partissanship squared\" to allow the relationship between partisanship and vaccine skepticism to vary non-linearly\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{7pt} +  \\beta_2 \\text{PID}_{7pt}^2+ X\\beta+ \\epsilon$$ \n\n## {.smaller}\n#### Translating Theoretical Claims into Empirical Expectations\n\nOr we could estimate a model treating Partisanship as a **categorical** variable rather than an **ordinal interval** variable. \n\nIn our recoding, we set `\"Democrat\"` to be the first level of the variable `pid3cat`, so the model R will estimate by default is:\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{Ind} +  \\beta_2 \\text{PID}_{Rep}+ X\\beta + \\epsilon$$\n\n## Testing differences over time {.smaller}\n\nTesting Hypotheses 2 and 3 involve making comparisons across models estimated on data from different surveys.\n\nFormally, testing these expectations is a little more complicated\n\n- we could pool our two surveys together include an interaction term for survey year\n\nFor our purposes, we'll treat these as more qualitative/exploratory hypotheses:\n\n- H2a/b implies overall rates of vaccine skepticism will be lower/higher in 2020 compared to 2016\n\n- H3 implies that whatever partisan differences we find in 2016 should be larger in 2020.\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- *Specify our expectations* ✅\n\n- **Estimate models to test these expectations** 📥\n\n- Presenting and interpreting results using\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis tests \n\n\n## Estimating Empirical Models \n\nHaving derived empirical implications of our theoretical expectations expressed in terms of linear regressions, now we simply have to estimate our models in R.\n\nWhen estimating the **same model** on **different datasets** we can write the formulas once\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf1 <- formula(vaccine_skeptic01 ~ pid + age)\nf2 <- formula(vaccine_skeptic01 ~ pid + I(pid^2) + age)\nf3 <- formula(vaccine_skeptic01 ~ pid3cat + age)\n```\n:::\n\n\n\n## Estimating Empirical Models\n\nAnd then pass it to `lm()` with different `data` arguments:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1_2016 <- lm(formula = f1, data = nes16)\nm1_2020 <- lm(formula = f1, data = nes20)\nm2_2016 <- lm(formula = f2, data = nes16)\nm2_2020 <- lm(formula = f2, data = nes20)\nm3_2016 <- lm(formula = f3, data = nes16)\nm3_2020 <- lm(formula = f3, data = nes20)\n```\n:::\n\n\n\n## Estimating Empirical Models {.smaller}\n\n:::{.nonincremental}\n\nIf you've:\n\n- coded your data correctly\n\n- developed clear testable implications from your theoretical expectations\n\nSpecifying and estimating empirical models is straightforward. Literally a few lines of code.\n\n:::\n\n## Progress Report {.smaller}\n\nTo explore these questions, we need to\n\n- *Get setup to work* ✅\n\n- *Load our data* ✅\n\n- *Recode our data* ✅\n\n- *Specify our expectations* ✅\n\n- *Estimate models to test these expectations* ✅\n\n- *Present our results* 📥\n\n  - Tables\n  - Figures\n  - Confidence intervals \n  - Hypothesis testing\n\n## Presenting and Interpreting Your Results {.smaller}\n\nPresenting and interpreting your results is requires both art and science.\n\nYour goal is to tell a story with your results,\n\nLet's start by producing a regression table, which provides a concise summary of multiple regression models.\n\n\n## Regression Tables {.smaller}\n\n:::: panel-tabset\n\n## Tasks\n\n:::{.nonincremental}\n\n- Giving the variables in substantive names\n\n- Reporting coefficients to 3 decimal places\n\n- Using a single significance threshold of $p < 0.05$\n\n- Giving the models custom names\n\n- Adding a header to group models by year\n\n- Changing the caption of the table\n\n:::\n\n## {{< fa code >}} Code\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Basic\ntab_basic <- texreg::htmlreg(\n  list(m1_2016,m2_2016,m3_2016,\n       m1_2020,m2_2020,m3_2020)\n)\n\n# Formatted\ntab_fetch <- texreg::htmlreg(\n  list(m1_2016,m2_2016,m3_2016,\n       m1_2020,m2_2020,m3_2020),\n  # Reporting coefficients to 3 decimal places\n  digits = 3,\n  # Using a single significance threshold \n  stars = 0.05,\n  # Giving the variables in substantive names\n  custom.coef.names = c(\n    \"(Intercept)\",\n    \"PID (7pt)\",\n    \"Age\",\n    \"PID<sup>2</sup> (7pt)\",\n    \"Independent\",\n    \"Republican\"\n  ),\n  # Use SE instead o CIs\n  include.ci = F,\n  # Giving the models custom names\n  custom.model.names = paste(\"(\",c(1:6),\")\", sep=\"\"),\n  # Adding a header to group models by year\n  custom.header = list(\"NES 2016\" = 1:3, \"NES 2020\" = 4:6),\n  # Changing the caption of the table\n  caption = \"Partisanship and Vaccine Skepticism\"\n)\n```\n:::\n\n\n\n## {{< fa table >}} Basic\n\n\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 2</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 3</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 4</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 5</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 6</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.46<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.35<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.42<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.34<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.32<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.35<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.04)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.06<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.01)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid^2</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.01<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid3catIndependent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.17<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.20<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid3catRepublican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.10<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.01)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.05</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n\n\n## {{< fa table >}} Fetch\n\n\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Partisanship and Vaccine Skepticism</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2016</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2020</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(1)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(2)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(3)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(4)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(5)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(6)</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.458<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.350<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.417<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.343<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.318<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.352<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.025)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.035)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.018)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.024)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.064<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.021<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.037<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.003)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID<sup>2</sup> (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.009<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.002</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Independent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.175<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.200<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Republican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.100<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.023</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.028</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.022</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.027</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n\n\n::::\n\n## Telling a Story with Regression {.smaller}\n\n:::{.nonincremental}\n\nFirst, provide an overview the models presented in the table\n\n- Explain what each model is doing conceptually\n\nThen start with your simplest model (first column)\n\n- Use this as a chance to explain core concepts from the course\n  - What is regression\n  - How should I interpret a coefficient substantively\n  - How should I interepret the statistical signficance of a give coefficient\n- As you move from left to right (simple to more complex)\n  - you need not interpret every single coefficient in the model\n  - instead highlight the factors that are important for the reader to note (e.g. a comparison between one coefficient in model or another.)\n\n:::\n\n## Example {.smaller}\n\nTable 1 presents the results of three specifications exploring the relationship between partisanship and vaccine skepticism using data from the 2016 (Models 1-3) and 2020 (Models 4-5) National Election Studies.\n\nModels 1 and 4 operationalize partisanship as a 7-point scale, where 1 corresponds to Strong Democrats, 4 to Indepndents, and 7 to Strong Republicans in the 2016 (Model 1) and 2020 (Model 2) surveys.\n\nModels 2 and 5 allow the relationship between partisanship and vaccine skepticism to vary non-linear again for the 2016 (Model 2) and 2020 (Model 5) elections.\n\nModels 3 and 6 treat partisanship as categorical variable, describing how Independents and Republicans differ from Democrats, the reference category in these models.\n\nAll models control age, since (put in substantive justification for controlling for age here)\n\n## Story: Testing for Partisan Differences {.smaller}\n\n- The results from Model 1 provide little initial evidence for partisan differences in vaccine skepticism in the 2016 Election.\n\n  - The coefficient on the partisanship variable is -0.005, suggesting that a unit increase in partisanship (going from being a Strong Democrat to just a Democrat, or an Independent to an independent who leans Republican), is associated with just a 0.5 percentage point increase in the probability of being a vaccine skeptic (believing that the risks of vaccination outweigh the benefits or that their is no difference in the risks versus benefits).\n\n- Furthermore the 95-percent confidence interval for this estimate (-0.011, 0.002) brackets 0, suggesting the true population estimate from this model could be either positive or negative. Similarly, we fail to reject the null hypothesis that the true coefficient on partisanship in this model is 0 as the test statistic for this estimate ( -1.38) corresponds to a p-value of 0.168 suggesting that we would see test statistics this large or larger fairly often when the true relationship was 0.\n\n- In sum, the results from Model 1 provide little support for any of the expectations described by *H1*\n\n## Testing for Partisan Differences: Model 2 {.smaller}\n\n- While coefficients from Model 1 suggest little evidence of partisan differences in vaccine skepticism, the coefficients on both partisanship, and partisanship squared are statistically significant (p < 0.05).\n\n## Interpreting Model 2 {.smaller}\n\n:::: panel-tabset\n\n## Task\n\n- The coefficients from polynomial regressions can be difficult to interpret jointly and so Figure 1 presents the predicted values from Model 2, holding age constant at its sample mean.\n\n## {{< fa code >}}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_df_m2 <- expand_grid(\n  pid = 1:7,\n  age = mean(nes16$age, na.rm=T)\n)\npred_df_m2 <- cbind(pred_df_m2, predict(m2_2016,pred_df_m2, interval =\"confidence\"))\n\nfig_m2 <- pred_df_m2 %>%\n  ggplot(aes(pid, fit, ymin =lwr, ymax =upr))+\n  geom_line()+\n  geom_ribbon(alpha=.2, fill=\"grey\")+\n  theme_bw()+\n  labs(x = \"Partisanship\",\n       y = \"Predicted Vaccine Skepticism\",\n       title = \"Independents are the most skeptical of vaccines\",\n       subtitle = \"Data: 2016 NES\"\n       )\n```\n:::\n\n\n\n## {{< fa chart-lines>}} Figure\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfig_m2\n```\n\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/pred-1.png){width=960}\n:::\n:::\n\n\n\n## Interpretation\n\nWe see from Model 2 that 29.7 percent \\[27.3%, 32.1%\\] of Independents in the 2016 NES were predicted to be vaccine skeptics compared to 23.7 percent \\[20.8%, 26.5%\\] of Strong Democrats and only 20.1 percent \\[16.9%, 23.3%\\] of Strong Republicans.\n\n::::\n\n## Interpreting Model 3 {.smaller}\n\n:::: panel-tabset\n\n## Interpretation\n\nModel 3 tells a similar story to model 2. Again, adjusting for differences in vaccine skepticism explained by age, Model 3 predicts that 41.7 percent \\[37.7%, 45.6%\\] of Independents in the 2016 NES are vaccine skeptics compared to 24.2 percent \\[22.1%, 26.2%\\] of Democrats, and 22.6 percent \\[20.4%, 24.8%\\] of Republicans.\n\nNote the coefficients from Model 3 imply that the differences between Independents and Democrats are statistically significant ($\\beta_{Ind} = 0.175, p < 0.05$), the differences between Republicans and Democrats are not ($\\beta_{Rep} = -0.004, p = 0.31$)\n\n## {{< fa code >}} Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_df_m3 <- expand_grid(\n  pid3cat = c(\"Democrat\", \"Independent\",\"Republican\"),\n  age = mean(nes16$age, na.rm=T)\n)\npred_df_m3 <- cbind(pred_df_m3, predict(m3_2016,pred_df_m3, interval =\"confidence\"))\npred_df_m3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      pid3cat      age       fit       lwr       upr\n1    Democrat 49.58231 0.2419547 0.2211228 0.2627867\n2 Independent 49.58231 0.4169043 0.3773539 0.4564547\n3  Republican 49.58231 0.2261496 0.2038046 0.2484947\n```\n\n\n:::\n:::\n\n\n\n::::\n\n## {.smaller}\n\n\n\n\n\n```{.r .cell-code}\ntab_fetch\n```\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Partisanship and Vaccine Skepticism</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2016</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2020</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(1)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(2)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(3)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(4)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(5)</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">(6)</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.458<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.350<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.417<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.343<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.318<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.352<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.025)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.035)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.018)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.024)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.064<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.021<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.037<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.003)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID<sup>2</sup> (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.009<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.002</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Independent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.175<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.200<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Republican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.100<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.023</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.028</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.022</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.027</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n\n\n\n\n## Testing for Differences Over Time {.smaller}\n\nThe results for the 2016 NES suggest political independents are most skeptical of vaccines.\n\nThe results for 2020 suggest the relationship between partisanship and vaccine skepticism has changed overtime.\n\n- The coefficient on partisanship in model 4 is now positive and statistically significant (p \\< 0.05), suggesting that as respondents become more Republican, they are more likely to be skeptical of vaccines\n\n- The coefficients from Model 5 suggest the relationship between partisanship skepticism is non linear, which is confirmed by model 6.\n\n- In Model 6, we see that independents remain the most skeptical of vaccines in 2020 $(\\beta = 0.20,\\, p <0.05)$, but that Republicans now tend to be more skeptical of vaccines than Democrats $(\\beta = 0.10,\\, p <0.05)$\n\n\n# {{< fa lightbulb>}} Regression Discontinuity Design {.inverse}\n\n## Motivating Example\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n\n- Do Members of Parliament in the UK get richer from holding office (QSS Chapter 4.3.4)\n\n:::\n\n:::{.column width=\"70%\"}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./images/04_eggers.png){width=386}\n:::\n:::\n\n\n[Eggers and Hainmueller (2009)](https://www.cambridge.org/core/journals/american-political-science-review/article/abs/mps-for-sale-returns-to-office-in-postwar-british-politics/E4C2B102194AA1EA0D2F1F777EAE3C08)\n]\n\n:::\n\n::::\n\n## Logic of the Regression Discontinuity Design (RDD) \n\n- What's the effect of holding elected office in the UK on personal wealth?\n\n- People who win elections differ in many ways from people who lose elections.\n\n- Logic of an RDD: \n\n  - Just look at the wealth of individuals who either narrowly won or lost elections.\n\n  - Candidates close to 50 percent cutoff (discontinuity) should be more comparable (better counterfactuals)\n\n##  Eggers and Hainmueller (2009)  {.smaller}\n\n:::: panel-tabset\n\n## Data\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(qss)\ndata(MPs)\nglimpse(MPs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 427\nColumns: 10\n$ surname    <chr> \"Llewellyn\", \"Morris\", \"Walker\", \"Walker\", \"Waring\", \"Brown…\n$ firstname  <chr> \"David\", \"Claud\", \"George\", \"Harold\", \"John\", \"Ronald\", \"Le…\n$ party      <chr> \"tory\", \"labour\", \"tory\", \"labour\", \"tory\", \"labour\", \"tory…\n$ ln.gross   <dbl> 12.13591, 12.44809, 12.42845, 11.91845, 13.52022, 12.46052,…\n$ ln.net     <dbl> 12.135906, 12.448091, 10.349009, 12.395034, 13.520219, 9.63…\n$ yob        <int> 1916, 1920, 1914, 1927, 1923, 1921, 1907, 1912, 1905, 1920,…\n$ yod        <int> 1992, 2000, 1999, 2003, 1989, 2002, 1987, 1984, 1998, 2004,…\n$ margin.pre <dbl> NA, NA, -0.057168204, -0.072508894, -0.269689620, 0.3409586…\n$ region     <chr> \"Wales\", \"South West England\", \"North East England\", \"Yorks…\n$ margin     <dbl> 0.05690404, -0.04973833, -0.04158868, 0.02329524, -0.230005…\n```\n\n\n:::\n:::\n\n\n\n## Variables\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Variable   |Description                                                        |\n|:----------|:------------------------------------------------------------------|\n|surname    |surname of the candidate                                           |\n|firstname  |first name of the candidate                                        |\n|party      |party of the candidate (labour or tory)                            |\n|ln.gross   |log gross wealth at the time of death                              |\n|ln.net     |log net wealth at the time of death                                |\n|yob        |year of birth of the candidate                                     |\n|yod        |year of death of the candidate                                     |\n|margin.pre |margin of the candidate’s party in the previous election electoral |\n|region     |region                                                             |\n|margin     |margin of victory (vote share)                                     |\n\n\n:::\n:::\n\n\n\n\n## {{<fa code>}}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nMPs %>%\n  ggplot(aes(margin, ln.net))+\n  geom_point(shape=1)+\n  facet_grid(~party)+\n  geom_smooth(data =MPs %>%\n                filter(margin <0),\n              method = \"lm\")+\n  geom_smooth(data =MPs %>%\n                filter(margin >0),\n              method = \"lm\")+\n  theme_bw() -> fig_rdd\n```\n:::\n\n\n\n## {{<fa chart-line>}}\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/rddfig-1.png){width=960}\n:::\n:::\n\n\n\n::::\n\n## RDD Notation {.smaller}\n\n- $X$ is a **forcing** variable\n- Treatment $D$ is a determined by $X$\n\n$$\nD_i = 1\\{X_i > c\\}\n$$\n\n- $X$ is the `margin` variable in the example data, and $D=1$ if `margin` is greater than 0 (i.e. the candidate won the election)\n\n- Interested in the differences in the outcome at the threshold\n\n$$\\lim_{x \\downarrow  c} E[Y_i|X=x] - \\lim_{x \\uparrow  c} E[Y_i|X=x]$$\n\n## Causal Identification with an RDD {.smaller}\n\nIf we assume $E[Y_i(0)|X=x]$ and $E[Y_i(1)|X=x]$ are continuous in x, then we can estimate a (local) ATE at the threshold:\n\n$$\\begin{align}\nATE_{RDD} &= E[Y(1)-Y(0)|X_i=c] \\\\\n&=  E[Y(1)|X_i=c] -  E[Y(0)|X_i=c]\\\\\n&= \\lim_{x \\downarrow  c} E[Y_i|X=x] - \\lim_{x \\uparrow  c} E[Y_i|X=x] \\\\\n\\end{align}$$\n\n## Continuity Assumption\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](https://mixtape.scunning.com/graphics/rdd_simul_ex.jpg)\n:::\n:::\n\n\n\n[Cunningham (2022)](https://mixtape.scunning.com/regression-discontinuity.html#continuity-assumption)\n\n## Causal Identification with an RDD {.smaller}\n\n- The continuity assumption is a formal way of saying that observations close to the threshold are good counterfactuals for each other\n\n- We can't prove this assumption\n\n- But if it holds, we should observe\n \n  - no sorting around the cutoff (no self selection)\n \n  - similar distributions of covariates around the cutoff (balance tests)\n  \n  - no effect of treatment on things measured pre-treatment (placebo tests)\n\n\n\n\n\n# {{< fa lightbulb>}} Instrumental Variables {.inverse}\n\n\n\n## Instrumental Variables  {.smaller}\n\nInstrumental variables are an economists favorite tool for dealing with **omitted variable bias**\n\n- We have some non random treatment whose effects we'd like to assess\n- We're worried that these effects are **confounded** by some unobserved, omitted variable, that influences both the treatment and the outcome\n- We find an **instrumental variable** that satisfies the following:\n  - Randomization\n  - Excludability\n  - First-stage relatioship\n  - Monotonicity\n- Allowing us estimate a Local Average Treatment Effect (LATE) using the only the variation in our treatment is **exogenous** (uncorrelated with ommited variables)\n\n\n\n## IV Assumption: Randomization\n\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n- No path from $U$ to $Z$\n\n:::\n\n::: {.column width=\"70%\"}\n\n![](https://book.declaredesign.org/figures/figure-16-7.svg)\n[Source](https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables)\n\n:::\n\n::::\n\n\n## IV Assumption: Excludability\n\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n- No path from $Z$ to $Y$\n\n:::\n\n::: {.column width=\"70%\"}\n\n![](https://book.declaredesign.org/figures/figure-16-7.svg)\n\n[Source](https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables)\n\n\n:::\n\n::::\n\n\n## IV Assumption:  First Stage\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n\n- Path from $Z$ to $D$\n\n:::\n\n::: {.column width=\"70%\"}\n\n![](https://book.declaredesign.org/figures/figure-16-7.svg)\n\n[Source](https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables)\n\n\n:::\n\n::::\n\n\n\n\n## IV Assumption: Monotonicity\n\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n\n-  $D_i(Z=1)\\geq D_i(Z=0)$\n- \"No Defiers\"\n\n\n:::\n\n::: {.column width=\"70%\"}\n\n![](https://book.declaredesign.org/figures/figure-16-7.svg)\n\n[Source](https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables)\n\n\n:::\n\n::::\n\n\n## Compliance\n\nWith a binary treatment, $D$ and binary instrument $Z$ there are four types of compliance\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Type          | $D_i(Z=1)$| $D_i(Z=0)$|\n|:-------------|----------:|----------:|\n|Always Takers |          1|          1|\n|Never Takers  |          0|          0|\n|Compliers     |          1|          0|\n|Defiers       |          0|          1|\n\n\n:::\n:::\n\n\n\n- Assuming Monotonicity means there are \"No Defiers\"\n\n## Estimating the Local Average Treatment Effect\n\nIf we believe our assumptions of:\n\n- Randomization\n- Excludability\n- First-stage relationship\n- Monotonicity\n\nThen we can estimate [Local Average Treatment Effect (LATE)]{.blue} sometimes called the [Complier Average Treatment Effect (CATE)]{.blue} \n\n## Estimating the Local Average Treatment Effect\n\nIt can be [shown](https://www.mattblackwell.org/files/teaching/s10-iv-handout.pdf) that the LATE:\n\n$$LATE = \\frac{E[Y|Z=1] - E[Y|Z=0]}{E[D|Z=1]-E[D|Z=0]}= \\frac{ATE_{Z\\to Y}}{ATE_{Z\\to D}}$$\n\nWhere:\n\n- $ATE_{Z\\to Y}$ is the known as the \"Intent to Treat\" effect (ITT) (i.e. the effect of being assigned to treatment)\n\n- $ATE_{Z\\to D}$ is the \"effect\" of being assigned to treatment on actually receiving treatment\n\n\n\n\n\n\n## Example: Earnings and Military Service {.smaller}\n\nAdapted from [Edward Rubin](https://raw.githack.com/edrubin/EC421W19/master/LectureNotes/11InstrumentalVariables/11_instrumental_variables.html#42)\n\n*Example:* If we want to estimate the effect of veteran status on earnings,\n\n$$\n\\begin{align}\n  \\text{Earnings}_i = \\beta_0 + \\beta_1 \\text{Veteran}_i + u_i \\tag{1}\n\\end{align}\n$$\n\n\n\nWe would love to calculate $\\color{#e64173}{\\text{Earnings}_{1i}} - \\color{#6A5ACD}{\\text{Earnings}_{0i}}$, but we can't.\n\n\n\nAnd OLS will likely be biased for $(1)$ due to selection/omitted-variable bias.\n\n\n\n## Introductory example {.smaller}\n\nImagine that we can split veteran status into an exogenous (as-if random, unbiased) part and an endogenous (non-random, biased) part...\n\n\n\n$$\n\\begin{align}\n  \\text{Earnings}_i\n  &= \\beta_0 + \\beta_1 \\text{Veteran}_i + u_i \\tag{1} \\\\\n  &= \\beta_0 + \\beta_1 \\left(\\text{Veteran}_i^{\\text{Exog.}} + \\text{Veteran}_i^{\\text{Endog.}}\\right) + u_i \\\\\n  &= \\beta_0 + \\beta_1 \\text{Veteran}_i^{\\text{Exog.}} + \\underbrace{\\beta_1 \\text{Veteran}_i^{\\text{Endog.}} + u_i}_{w_i} \\\\\n  &= \\beta_0 + \\beta_1 \\text{Veteran}_i^{\\text{Exog.}} + w_i\n\\end{align}\n$$\n\n\n\nWe could use this exogenous variation in veteran status to consistently estimate $\\beta_1$.\n\n\n\n**Q:** What would exogenous variation in veteran status mean?\n\n\n\n## Introductory example {.smaller}\n\n**Q:** What would exogenous variation in veteran status mean?\n\n\n\n$A_1$ Choices to enlist in the military that are essentially random—or at least uncorrelated with omitted variables and the disturbance.\n\n\n\n$A_2$ .No selection bias:\n\n$$\n\\begin{align}\n  \\color{#e64173}{\\mathop{E}\\left(\\text{Earnings}_{0i}\\mid\\text{Veteran}_i = 1\\right)} - \\color{#6A5ACD}{\\mathop{E}\\left( \\text{Earnings}_{0i} \\mid \\text{Veteran}_i = 0 \\right)} = 0\n\\end{align}\n$$\n\n## Instruments {.smaller}\n\n- **Q:** How do we isolate this *exogenous variation* in our explanatory variable?\n\n- **A:** Find an instrument (an instrumental variable).\n\n\n\n- **Q:** What's an instrument?\n\n- **A:** An **instrument** is a variable that is\n  \n  1. **correlated** with the **explanatory variable** of interest (*relevant*),\n  2. **uncorrelated** with the **error** term (*exogenous*).\n\n\n\n## Instruments {.smaller}\n\n\nSo if we want an instrument $z_i$ for endogenous veteran status in\n\n$$\n\\begin{align}\n  \\text{Earnings}_i = \\beta_0 + \\beta_1 \\text{Veteran}_i + u_i\n\\end{align}\n$$\n\n1. **Relevant:** $\\mathop{\\text{Cov}} \\left( \\text{Veteran}_i,\\, z_i \\right) \\neq 0$\n2. **Exogenous:** $\\mathop{\\text{Cov}} \\left( z_i,\\, u_i \\right) = 0$\n\n## Instruments: Relevance {.smaller}\n\n**Relevance:** We need the instrument to cause a change in (correlate with) our endogenous explanatory variable.\n\nWe can actually test this requirement using regression and a *t* test.\n\n\n\n***Example:*** For the veteran status, consider three potential instruments:\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n1. Social security number\n\n2. Physical fitness\n\n3. Vietnam War draft\n\n:::\n\n::: {.column width=\"70%\"}\n- **Probably not relevant** uncorrelated with military service\n\n- *Potentially relevant* service may correlate with fitness\n\n- **Relevant** being drafted led to service\n\n:::\n\n::::\n\n\n\n\n\n\n\n## Instruments: Exogeneity {.smaller}\n\n[Exogeneity:]{.blue} The instrument to be independent of omitted factors that affect our outcome variable—as good as randomly assigned.\n\n$z_i$ must be uncorrelated with our disturbance $u_i$. [Not testable.]{.blue}\n\n\n\n***Example:*** For the [veteran status]{.blue}, consider three potential instruments:\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n1. Social security number\n\n2. Physical fitness\n\n3. Vietnam War draft\n\n:::\n\n::: {.column width=\"70%\"}\n- **Exogenous** SSN essentially random\n\n- *Not Exogenous* fitness correlated with many things\n\n- **Exogenous** draft via lottery\n\n:::\n\n::::\n\n## Venn diagram explanation\n\nIn the following figures (Venn diagrams)\n\n- Each circle illustrates a variable.\n- Overlap gives the share of correlatation between two variables.\n- Dotted borders denote *omitted* variables.\n\n\n## Relevant and Exogenous\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/venn_iv-1.png){width=960}\n:::\n:::\n\n\n\n## Relevant, Not Exogenous\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/venn_iv_endog-1.png){width=960}\n:::\n:::\n\n\n\n## Not Relevant and Not Exogenous\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/venn_iv_irrelevant-1.png){width=960}\n:::\n:::\n\n\n\n## Relevant, Not Exogenous\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](12-slides_files/figure-revealjs/venn_iv_endog2-1.png){width=960}\n:::\n:::\n\n\n\n\n\n## Take-aways\n\n- Figure 1: [Valid instrument]{.blue} (relevant; exogenous, e.g. draft lotto number)\n- Figure 2: [Invalid instrument]{.yellow} (relevant; not exogenous, e.g. physical fitness)\n- Figure 3: [Invalid instrument]{.yellow} (not relevant; not exogenous)\n- Figure 4: [Invalid instrument]{.yellow} (relevant; not exogenous)\n\n## IV Applications\n\n![](images/ivtweet.png)\n\n\n## IV Summary\n\nInstrumental variables require a number of assumptions to yield credible causal claims:\n\n- Randomization\n- Excludability\n- First-stage relationship\n- Monotonicity\n\nEstimation and inference of IVs is beyond the scope of this course. \n\n  - See Edward Rubin's excellent [slides](https://raw.githack.com/edrubin/EC421W19/master/LectureNotes/11InstrumentalVariables/11_instrumental_variables.html#85)\n  - And Matt Blackwells [notes](https://www.mattblackwell.org/files/teaching/s10-iv-handout.pdf)\n\n- Understanding the identifying assumptions of IV can help you critique a study (even if the you don't fully understand the math)\n\n# {{< fa lightbulb>}} Summary {.inverse}\n\n## What you need to know\n\n- Causal inference in observational and experimental studies is about counterfactual comparisons\n- In observational studies, to make causal claims we generally make some  assumption of conditional independence:\n\n$$\nY_i(1),Y_i(0), \\perp D_i |X_i\n$$\n\n- The credibility of this assumption depends less on the data, and more on how the data were generated.\n- **Selection on Observables** is rarely a credible assumption\n- Observational designs that produce credible causal inference, leverage aspects of the world that create *natural experiments*\n- You should be able to describe the logic and assumptions of common designs in social science \n  - **Difference-in-Differences:** *Parallel Trends* \n  - **Regression Discontiniuity:** *Continuity at the cutoff*\n  - **Instrumental Variables:** Instruments need to be *Relevant and Exogenous*\n\n",
    "supporting": [
      "12-slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}