<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.545">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Your Group Members Names Here">
<meta name="dcterms.date" content="2024-01-24">

<title>POLS 1600 - Comments for Lab 09 - Exploring Russians’ Attitudes About the War in Ukraine with OLS and Logistic Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/clipboard-2.0.6/clipboard.min.js"></script>
<link href="../../site_libs/xaringanExtra-clipboard-0.2.6/xaringanExtra-clipboard.css" rel="stylesheet">
<script src="../../site_libs/xaringanExtra-clipboard-0.2.6/xaringanExtra-clipboard.js"></script>
<script>window.xaringanExtraClipboard(null, {"button":"<i class=\"fa fa-clipboard\"><\/i>","success":"<i class=\"fa fa-check\" style=\"color: #90BE6D\"><\/i>","error":"Press Ctrl+C to Copy"})</script>
<link href="../../site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet">
<link href="../../site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">POLS 1600</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../class/index.html"> 
<span class="menu-text">Class</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../assignments.qmd"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#goals" id="toc-goals" class="nav-link" data-scroll-target="#goals">Goals</a></li>
  <li><a href="#workflow" id="toc-workflow" class="nav-link" data-scroll-target="#workflow">Workflow</a></li>
  <li><a href="#please-knit-this-.rmd-file" id="toc-please-knit-this-.rmd-file" class="nav-link" data-scroll-target="#please-knit-this-.rmd-file">Please knit this .Rmd file</a></li>
  <li><a href="#get-setup-to-work" id="toc-get-setup-to-work" class="nav-link" data-scroll-target="#get-setup-to-work"><span class="header-section-number">1</span> Get setup to work</a>
  <ul class="collapse">
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link" data-scroll-target="#load-packages"><span class="header-section-number">1.1</span> Load Packages</a></li>
  <li><a href="#load-the-data" id="toc-load-the-data" class="nav-link" data-scroll-target="#load-the-data"><span class="header-section-number">1.2</span> Load the data</a></li>
  </ul></li>
  <li><a href="#model-the-relationship-between-demographic-predictors-and-war-support-using-ols-and-logistic-regression." id="toc-model-the-relationship-between-demographic-predictors-and-war-support-using-ols-and-logistic-regression." class="nav-link" data-scroll-target="#model-the-relationship-between-demographic-predictors-and-war-support-using-ols-and-logistic-regression."><span class="header-section-number">2</span> Model the relationship between demographic predictors and war support using OLS and Logistic regression.</a>
  <ul class="collapse">
  <li><a href="#fit-the-models" id="toc-fit-the-models" class="nav-link" data-scroll-target="#fit-the-models"><span class="header-section-number">2.1</span> Fit the models</a></li>
  <li><a href="#display-the-results-in-a-regression-table" id="toc-display-the-results-in-a-regression-table" class="nav-link" data-scroll-target="#display-the-results-in-a-regression-table"><span class="header-section-number">2.2</span> Display the results in a regression table</a></li>
  <li><a href="#produce-predicted-values-from-the-model" id="toc-produce-predicted-values-from-the-model" class="nav-link" data-scroll-target="#produce-predicted-values-from-the-model"><span class="header-section-number">2.3</span> Produce predicted values from the model</a></li>
  <li><a href="#plot-the-predicted-values-and-interpet-the-results" id="toc-plot-the-predicted-values-and-interpet-the-results" class="nav-link" data-scroll-target="#plot-the-predicted-values-and-interpet-the-results"><span class="header-section-number">2.4</span> Plot the predicted values and interpet the results</a></li>
  </ul></li>
  <li><a href="#assess-the-uncertainty-around-your-estimated-coefficients" id="toc-assess-the-uncertainty-around-your-estimated-coefficients" class="nav-link" data-scroll-target="#assess-the-uncertainty-around-your-estimated-coefficients"><span class="header-section-number">3</span> Assess the uncertainty around your estimated coefficients</a>
  <ul class="collapse">
  <li><a href="#take-1000-bootstrap-samples-from-df_drww" id="toc-take-1000-bootstrap-samples-from-df_drww" class="nav-link" data-scroll-target="#take-1000-bootstrap-samples-from-df_drww"><span class="header-section-number">3.1</span> Take 1,000 bootstrap samples from <code>df_drww</code></a></li>
  <li><a href="#estimate-1000-models-from-the-1000-bootstrapped-samples" id="toc-estimate-1000-models-from-the-1000-bootstrapped-samples" class="nav-link" data-scroll-target="#estimate-1000-models-from-the-1000-bootstrapped-samples"><span class="header-section-number">3.2</span> Estimate 1,000 models from the 1,000 bootstrapped samples</a></li>
  <li><a href="#tidy-the-results-of-our-bootstrapping" id="toc-tidy-the-results-of-our-bootstrapping" class="nav-link" data-scroll-target="#tidy-the-results-of-our-bootstrapping"><span class="header-section-number">3.3</span> Tidy the results of our bootstrapping</a></li>
  <li><a href="#plot-the-bootstrapped-sampling-distribution-of-the-coefficient-for-age" id="toc-plot-the-bootstrapped-sampling-distribution-of-the-coefficient-for-age" class="nav-link" data-scroll-target="#plot-the-bootstrapped-sampling-distribution-of-the-coefficient-for-age"><span class="header-section-number">3.4</span> Plot the bootstrapped sampling distribution of the coefficient for age</a></li>
  </ul></li>
  <li><a href="#quantify-the-uncertainy-described-by-your-sampling-distributions" id="toc-quantify-the-uncertainy-described-by-your-sampling-distributions" class="nav-link" data-scroll-target="#quantify-the-uncertainy-described-by-your-sampling-distributions"><span class="header-section-number">4</span> Quantify the uncertainy described by your sampling distributions</a></li>
  <li><a href="#explore-other-relationships-in-the-data." id="toc-explore-other-relationships-in-the-data." class="nav-link" data-scroll-target="#explore-other-relationships-in-the-data."><span class="header-section-number">5</span> Explore other relationships in the data.</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Comments for Lab 09 - Exploring Russians’ Attitudes About the War in Ukraine with OLS and Logistic Regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Your Group Members Names Here </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 24, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level1 unnumbered">
<h1 class="unnumbered">Overview</h1>
<p>Today, we will return to exploring Russians’ support the war in Ukraine using a public opinion survey from Russia conducted by Alexei Miniailo’s <a href="https://www.dorussianswantwar.com/en">“Do Russians Want War”</a> project.</p>
<p>The survey was conducted by phone using a random sample of mobile phone numbers to produce a sample of respondents representative of the population in terms of age, sex, and geography. It was in the field from February 28 to March 2.</p>
<p>First, we will explore how support for the war varies with the demographic predictors <code>age</code>, <code>sex</code> and <code>education</code>. We will compare the results of modeling this relationship using <strong>Ordinary Least Squares</strong> regression and <strong>Logisitic Regression</strong></p>
<p>We’ll talk more about the <a href="https://pols1600.paultesta.org/slides/09-slides.html#116" target="_blank">technical aspects</a> of logistic regression next week. For today we’ll simply compare the results from these two approaches.</p>
<p>Next, we will gain insight into how our estimates from these models might vary using the statistical process of <strong>bootstrapping</strong>. Specifically, we will simulate the idea of <strong>repeated sampling</strong> that is the foundation of frequentist interpretations of probability, by sampling from our sample <strong>with replacement</strong>.</p>
<p>We’ll walk through the mechanics of simulation together. Then you’ll quantify the uncertainty described by these bootstrapped sampling distributions.</p>
<p>Finally, we’ll see what other questions we might ask of these data and practice various skills we’ve developed through out the course.</p>
<p>Plan to spend the following amount of time on each section</p>
<ol type="1">
<li><p>Get set up to work (5 minutes)</p></li>
<li><p>Model the relationship between demographic predictors and war support using OLS and Logistic regression (20 minutes)</p></li>
<li><p>Assess the uncertainty around your estimated coefficients (15 minutes)</p></li>
<li><p>Quantify the uncertainty described by your sampling distributions (10 minutes)</p></li>
<li><p>Explore other relationships in the data. (30 minutes)</p></li>
</ol>
<p>The graded question for today is:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">472022</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>graded_question <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,<span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"Question"</span>,graded_question,<span class="st">"is the graded question for this week"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Question 5 is the graded question for this week"</code></pre>
</div>
</div>
<p>You will work in your assigned groups. Only one member of each group needs to submit the html file produced by knitting the lab.</p>
<p>This lab <strong>must</strong> contain the names of the group members in attendance.</p>
<p>If you are attending remotely, you will submit your labs individually.</p>
<p>You can find your assigned groups in previous <a href="https://pols1600.paultesta.org/labs/06-lab-comments.html" target="_blank">labs</a></p>
</section>
<section id="goals" class="level1 unnumbered">
<h1 class="unnumbered">Goals</h1>
<p>Today’s lab covers a little bit of everything. You will</p>
<ul>
<li><p>learn how to model binary outcomes using logistic regression</p></li>
<li><p>develop an intuition for how to think about uncertainty using simulations to describe what might have happened</p></li>
<li><p>practice formulating, estimating, presenting and interpreting regression models.</p></li>
</ul>
</section>
<section id="workflow" class="level1 unnumbered">
<h1 class="unnumbered">Workflow</h1>
</section>
<section id="please-knit-this-.rmd-file" class="level1 unnumbered">
<h1 class="unnumbered">Please knit this .Rmd file</h1>
<p>As with every lab, you should:</p>
<ul>
<li>Download the file</li>
<li>Save it in your course folder</li>
<li><strong>Update the <code>author:</code> section of the YAML header to include the names of your group members in attendance.</strong></li>
<li>Knit the document</li>
<li>Open the html file in your browser (Easier to read)</li>
<li>Write yourcode in the chunks provided</li>
<li>Comment out or delete any test code you do not need</li>
<li><strong>Knit the document again after completing a section or chunk</strong> (Error checking)</li>
<li>Upload the final lab to <a href="https://canvas.brown.edu/courses/1087979/assignments/7870531?module_item_id=10762404" target="_blank">Canvas</a>.</li>
</ul>
</section>
<section id="get-setup-to-work" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Get setup to work</h1>
<section id="load-packages" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="load-packages"><span class="header-section-number">1.1</span> Load Packages</h2>
<p>First lets load the libraries we’ll need for today.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>the_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## R Markdown</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"kableExtra"</span>,<span class="st">"DT"</span>,<span class="st">"texreg"</span>,<span class="st">"htmltools"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"flair"</span>, <span class="co"># Comments only</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Tidyverse</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyverse"</span>, <span class="st">"lubridate"</span>, <span class="st">"forcats"</span>, <span class="st">"haven"</span>, <span class="st">"labelled"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"modelr"</span>, <span class="st">"purrr"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Extensions for ggplot</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ggmap"</span>,<span class="st">"ggrepel"</span>, <span class="st">"ggridges"</span>, <span class="st">"ggthemes"</span>, <span class="st">"ggpubr"</span>, </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"GGally"</span>, <span class="st">"scales"</span>, <span class="st">"dagitty"</span>, <span class="st">"ggdag"</span>, <span class="st">"ggforce"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Data </span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"COVID19"</span>,<span class="st">"maps"</span>,<span class="st">"mapdata"</span>,<span class="st">"qss"</span>,<span class="st">"tidycensus"</span>, <span class="st">"dataverse"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Analysis</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DeclareDesign"</span>, <span class="st">"boot"</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Define function to load packages</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>ipak <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(new.pkg)) </span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>        <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ipak</span>(the_packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in contrib.url(repos, "source"): trying to use CRAN without setting a mirror</code></pre>
</div>
</div>
<p>There are three packages in particular that we’ll need to maker sure are installed and loaded</p>
<ul>
<li><code>modelr</code></li>
<li><code>purrr</code></li>
<li><code>broom</code></li>
</ul>
<p>If <code>ipak</code> didn’t return <code>TRUE</code> for each of these, please uncomment and run:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("modelr")</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("purrr")</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("broom")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-the-data" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="load-the-data"><span class="header-section-number">1.2</span> Load the data</h2>
<p>Next we’ll load the recoded data for the lab</p>
<p>Our primary outcome of interest (dependent variable) for today is a binary measure of support for war:</p>
<ul>
<li><code>support_war01</code> “Please tell me, do you support or do not support Russia’s military actions on the territory of Ukraine?” (1=yes, 0 = no)</li>
</ul>
<p>Our key predictors (independent variables) are the following demographic variables:</p>
<ul>
<li><p><code>age</code> “How old are you?”</p></li>
<li><p><code>sex</code> “Gender of respondent” (As assessed by the interviewer)</p></li>
<li><p><code>education_n</code> “What is your highest level of education (confirmed by a diploma, certificate)?” (1 = Primary school, 2 = “High School”, 3 = “Vocational School” 4 = “College”, 5 = Graduate Degree)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://pols1600.paultesta.org/files/data/df_drww.rda"</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>df_drww <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">person_id =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">n</span>()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> df_drww</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in df_drww %&gt;% mutate(person_id = 1:n()): could not find function "%&gt;%"</code></pre>
</div>
</div>
</section>
</section>
<section id="model-the-relationship-between-demographic-predictors-and-war-support-using-ols-and-logistic-regression." class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Model the relationship between demographic predictors and war support using OLS and Logistic regression.</h1>
<section id="fit-the-models" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="fit-the-models"><span class="header-section-number">2.1</span> Fit the models</h2>
<p>Please estimate the following models:</p>
<ul>
<li>An OLS regression model called <code>m1</code> using <code>lm()</code></li>
<li>A Logistic regression model called <code>m2</code> using <code>glm()</code> with <code>family=binomial</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OLS</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(support_war01 <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> education_n, df_drww)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Logisitic </span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(support_war01 <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> education_n, df_drww,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="display-the-results-in-a-regression-table" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="display-the-results-in-a-regression-table"><span class="header-section-number">2.2</span> Display the results in a regression table</h2>
<p>Next, please display the results of your regressions in a table using <code>htmlreg()</code></p>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression Table</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(m1,m2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Error in htmlreg(list(m1, m2)): could not find function "htmlreg"</code></pre>
</section>
<section id="produce-predicted-values-from-the-model" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="produce-predicted-values-from-the-model"><span class="header-section-number">2.3</span> Produce predicted values from the model</h2>
<p>The coefficients from a logistic regression aren’t easy to directly interpret.</p>
<p>Instead, we will produce predicted values for each model</p>
<p>To do this, we will need to create a <strong>prediction dataframe</strong> called <code>pred_df</code> Every variable in your model, needs to be represented in your prediction data frame.</p>
<ul>
<li><p>Use <code>expand_grid()</code> to create a data frame where</p>
<ul>
<li><code>age</code> varies from 18 to 99</li>
<li><code>sex</code> is held constant at “Female”</li>
<li><code>education_n</code> is held constant at it’s mean</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Create prediction data frame</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>pred_df <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="dv">18</span> <span class="sc">:</span> <span class="dv">99</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="st">"Female"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">education_n =</span> <span class="fu">mean</span>(df_drww<span class="sc">$</span>education_n, <span class="at">na.rm =</span> T)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in expand_grid(age = 18:99, sex = "Female", education_n = mean(df_drww$education_n, : could not find function "expand_grid"</code></pre>
</div>
</div>
<p>Then you use the <code>predict()</code> function to produce predicted values from each model.</p>
<p>Save the output of <code>predict()</code> for <code>m1</code> to a new column in pred_df called <code>pred_ols</code>.</p>
<p>For <code>m2</code> you need to tell are to transform the predictions from <code>m2</code> back into the units of the <strong>response</strong> (outcome) variable, by setting the argument <code>type = "response"</code>. Save the output of <code>predict()</code> for <code>m1</code> to a new column in pred_df called <code>pred_logit</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># #Predicted values for m1</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>pred_df<span class="sc">$</span>pred_ols <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">newdata =</span> pred_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'pred_df' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted values for m2</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember to add type = "response"</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>pred_df<span class="sc">$</span>pred_logit <span class="ot">&lt;-</span> <span class="fu">predict</span>(m2,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">newdata =</span> pred_df,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">type =</span> <span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'pred_df' not found</code></pre>
</div>
</div>
</section>
<section id="plot-the-predicted-values-and-interpet-the-results" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="plot-the-predicted-values-and-interpet-the-results"><span class="header-section-number">2.4</span> Plot the predicted values and interpet the results</h2>
<p>Now we can compare the predictions of OLS and Logistic regression by plotting the predicted values of support for the war from each model.</p>
<p>To produce this plot you’ll need to</p>
<ul>
<li>specify <code>data</code> (you want to use the values from <code>pred_df</code>)</li>
<li>map values from your data <code>aes</code>thetics in <code>ggplot</code>
<ul>
<li>put <code>age</code> on the x axis and and <code>pred_ols</code> on the y-axis</li>
</ul></li>
<li>specify the <code>geom</code>etries to plot
<ul>
<li>add <em>two</em> <code>geom_line()</code> to the plot</li>
<li>leave the first one empty (e.g.&nbsp;<code>geom_line()</code>)</li>
<li>for the second, specify a new <code>aes</code> of <code>y=pred_logit</code></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>pred_df<span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># aesthetics</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(age, pred_ols, <span class="at">col =</span> <span class="st">"OLS"</span>))<span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># geometries</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> pred_logit, <span class="at">col =</span> <span class="st">"Logistic"</span>))<span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data=</span>df_drww, <span class="fu">aes</span>(age, support_war01),</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"black"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">height =</span> .<span class="dv">05</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> .<span class="dv">5</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> .<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">"Model"</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Values"</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in pred_df %&gt;% ggplot(aes(age, pred_ols, col = "OLS")): could not find function "%&gt;%"</code></pre>
</div>
</div>
<p><strong>How do the predictions of the two models compare</strong></p>
<p>So the predictions from OLS produce impossible values (levels of support above 100 percent) at for very old respondents, while the predictions from logistic regression are constrained to be between 0 and 1.</p>
<p>If we think that logistic regression provides a more credible way of modeling support for the war, then our OLS regression appears to overstate the level of support among young and old, while possibly understating the level of support among the middle age. The differences aren’t huge – a few percentage points – but for a binary outcome we will often prefer to model it with logistic regression.</p>
<p>Also note that marginal effect for age in the logistic regression is not constant. An increase in age from 25 to 26 is associated with a larger increase in support, than an increase in age from 75 to 76.</p>
<hr>
</section>
</section>
<section id="assess-the-uncertainty-around-your-estimated-coefficients" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Assess the uncertainty around your estimated coefficients</h1>
<p>How confident are we that the true relationship between age and support for the war is positive? How different might the coefficient be if we had taken a different random sample of Russians in early March 2022?</p>
<p>In this section, we will explore how we can simulate the idea “repeated” sampling using just the sample we have to quantify uncertainty about the estimates in our model.</p>
<p>To do this we will.</p>
<ol type="1">
<li>Take 1,000 <em>bootstrap</em> samples from <code>df_drww</code> <strong>with replacement</strong> using the <code>bootstrap</code> function from the <code>modelr</code> package.</li>
</ol>
<ul>
<li>By sampling with replacement, we allow the same observation to be included multiple times (or not all), in our bootstrapped sample.</li>
</ul>
<ol start="2" type="1">
<li>For each bootstrap sample, we will estimate the same model as above, using the <code>map</code> function from the <code>purrr</code> package.</li>
</ol>
<ul>
<li>We will end up with 1,000 bootstrapped estimates for each coefficient in our model</li>
<li>These bootstrapped estimates describe the <strong>sampling distribution</strong> of coefficient.</li>
</ul>
<ol start="3" type="1">
<li><p>Put the coefficients from this bootstrapped model into into a <strong>tidy</strong> data frame, using the <code>tidy</code> function from the <code>broom</code> package, and the <code>map_df</code> function from the <code>purrr</code> package.</p></li>
<li><p>Visualize the sampling distribution for coefficients in our model.</p></li>
</ol>
<p>In the code below I demonstrate this process for <code>m1</code>. Then you will repeat this process for <code>m2</code></p>
<section id="take-1000-bootstrap-samples-from-df_drww" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="take-1000-bootstrap-samples-from-df_drww"><span class="header-section-number">3.1</span> Take 1,000 bootstrap samples from <code>df_drww</code></h2>
<p>Below we create 1,000 boostrapped samples</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make sure these packages are loaded</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelr)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(purrr)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set random seed for reproducability</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># 1,000 bootstrap samples</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>boot <span class="ot">&lt;-</span> modelr<span class="sc">::</span><span class="fu">bootstrap</span>(df_drww, <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s take a moment to understand what <code>boot</code> is and why we’re sampling with replacement.</p>
<p>The object <code>boot</code> contains 1,000 bootstrapped samples from <code>df_drww</code>.</p>
<p>If we look at the first bootstrap we see:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>boot<span class="sc">$</span>strap[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;resample [1,807 x 42]&gt; 1308, 1018, 1125, 1004, 623, 905, 645, 934, 400, 900, ...</code></pre>
</div>
</div>
<p>The numbers <code>1308, 1018, 1125, 1004, 623, 905, ...</code> correspond to rows in <code>df_drww</code>. So person <code>1308</code> is the first observation in this boot strap sample, then person <code>1018</code> and so on.</p>
<p>Because we are sampling <strong>with replacement</strong> observations from <code>df_drww</code> can appear multiple times. In our first bootstrap sample:</p>
<ul>
<li>666 observations appeared once</li>
<li>342 appeared twice</li>
<li>105 appeared three times</li>
<li>27 appeared four times</li>
<li>5 appeared five times.</li>
<li>2 appeared six times</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">table</span>(boot<span class="sc">$</span>strap[[<span class="dv">1</span>]]<span class="sc">$</span>idx))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5   6 
666 342 104  27   5   2 </code></pre>
</div>
</div>
<p>Why would we want to sample with replacement?</p>
<p>Well, what we’d really love are 1,000 separate random surveys all drawn from the same population in the same way.</p>
<p>Since that’s not feasible, we instead use the one sample we do have to learn things like how much our estimate might vary in repeated sampling. <a href="https://projecteuclid.org/journals/annals-of-statistics/volume-7/issue-1/Bootstrap-Methods-Another-Look-at-the-Jackknife/10.1214/aos/1176344552.full">Efron (1979)</a> called this procedure “bootstrapping” after the idiom “to pull oneself up by one’s own bootstraps”</p>
<p>We do this by sampling from our sample <strong>with replacement</strong>.</p>
<p>When we sample with replacement, we are sampling from our sample, as our sample was sampled from the population.</p>
<p><strong>With replacement</strong> means that some observations will appear multiple times in our bootstrapped sample (while others will not be included at all).</p>
<p>When an observation appears multiple times in a bootstrap sample, conceptually, we’re using that original observation to represent the other people like that observation in the population who – had we taken a different sample – might have been included in our data.</p>
<p>Note each bootstrap sample is a different random sample with replacement. In our second bootstrap sample, one observation (person 1496) appeared five times.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">table</span>(boot<span class="sc">$</span>strap[[<span class="dv">2</span>]]<span class="sc">$</span>idx))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5   6 
661 342 105  31   1   3 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Person 406</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(boot<span class="sc">$</span>strap[[<span class="dv">2</span>]]<span class="sc">$</span>idx <span class="sc">==</span> <span class="dv">1496</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Person 1 is not in boostrap 2</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(boot<span class="sc">$</span>strap[[<span class="dv">2</span>]]<span class="sc">$</span>idx <span class="sc">==</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
</section>
<section id="estimate-1000-models-from-the-1000-bootstrapped-samples" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="estimate-1000-models-from-the-1000-bootstrapped-samples"><span class="header-section-number">3.2</span> Estimate 1,000 models from the 1,000 bootstrapped samples</h2>
<p>Now let’s estimate our model for each bootstrapped sample, using the <code>map</code> function.</p>
<ul>
<li>In the code below, for every sample in <code>boot</code>, map estimates the model <code>lm(support_war01 ~ age + sex + education_n)</code> plugging in the bootstrap sample into the <code>data=.</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># bootstrap simulations</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>bs_ols <span class="ot">&lt;-</span> purrr<span class="sc">::</span><span class="fu">map</span>(boot<span class="sc">$</span>strap, <span class="sc">~</span> <span class="fu">lm</span>(support_war01 <span class="sc">~</span> age <span class="sc">+</span> sex <span class="sc">+</span> education_n, <span class="at">data =</span>.))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The end result is a large list with 1,000 separate linear regression models estimated on each bootstrapped sample.</p>
<p>The coefficients from each bootstrap vary from one simulation</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First bootstrap</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>bs_ols[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = support_war01 ~ age + sex + education_n, data = .)

Coefficients:
(Intercept)          age      sexMale  education_n  
   0.305019     0.009746     0.081039    -0.024142  </code></pre>
</div>
</div>
<p>to the next:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Second boostrap</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>bs_ols[[<span class="dv">2</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = support_war01 ~ age + sex + education_n, data = .)

Coefficients:
(Intercept)          age      sexMale  education_n  
   0.245000     0.009142     0.095631    -0.009285  </code></pre>
</div>
</div>
<p>Because they’re estimated off of different bootstrapped samples.</p>
<p>We will visualize and quantify that variation to describe the uncertainty associated with our estimates.</p>
<p>But first, we need to transform our large list of linear models, into a more tidy data frame that’s easier to manipulate.</p>
</section>
<section id="tidy-the-results-of-our-bootstrapping" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="tidy-the-results-of-our-bootstrapping"><span class="header-section-number">3.3</span> Tidy the results of our bootstrapping</h2>
<p>In the code below we transform this large list of models into a <code>tidy</code> data frame of coefficients.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy bootstrapp sims</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>bs_ols_df <span class="ot">&lt;-</span> <span class="fu">map_df</span>(bs_ols, tidy, <span class="at">.id =</span> <span class="st">"id"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the resulting data frame the <code>id</code> variable identifies the bootstrap simulation (1 to 1,000), the <code>term</code> variable indentifies the specific coefficient from the model estimated for that simulation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bs_ols_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  id    term        estimate std.error statistic  p.value
  &lt;chr&gt; &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 1     (Intercept)  0.305    0.0522        5.84 6.29e- 9
2 1     age          0.00975  0.000702     13.9  3.31e-41
3 1     sexMale      0.0810   0.0222        3.65 2.73e- 4
4 1     education_n -0.0241   0.0107       -2.26 2.39e- 2
5 2     (Intercept)  0.245    0.0533        4.60 4.61e- 6
6 2     age          0.00914  0.000731     12.5  3.36e-34</code></pre>
</div>
</div>
</section>
<section id="plot-the-bootstrapped-sampling-distribution-of-the-coefficient-for-age" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="plot-the-bootstrapped-sampling-distribution-of-the-coefficient-for-age"><span class="header-section-number">3.4</span> Plot the bootstrapped sampling distribution of the coefficient for age</h2>
<p>Finally, let’s get a sense of how our coefficients could vary.</p>
<p>Specifically, let’s compare the the observed coefficient from <code>m1</code> for age, to the bootstrapped <code>sampling distribution</code> of coefficients in <code>bs_ols_df</code></p>
<ul>
<li>First, we’ll create a basic plot called <code>p_ols_age</code> that shows the distribution of the coefficients for age from our simulation</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>p_ols_age <span class="ot">&lt;-</span> bs_ols_df <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"age"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(estimate))<span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_density</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in ggplot(., aes(estimate)): could not find function "ggplot"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>p_ols_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
</div>
<p>Next we’ll add some additional geometries and labels to our figure</p>
<ul>
<li>First we’ll put a rug to show the individual coefficients</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>p_ols_age <span class="sc">+</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_rug</span>() <span class="ot">-&gt;</span> p_ols_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>p_ols_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
</div>
<ul>
<li>Then we’ll add a vertical line where our observed coefficient on <code>age</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>p_ols_age <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span>  <span class="fu">coef</span>(m1)[<span class="dv">2</span>],</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">linetype =</span> <span class="dv">2</span>) <span class="ot">-&gt;</span> p_ols_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>p_ols_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
</div>
<ul>
<li>Finally, let’s add some nice labels</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>p_ols_age <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">""</span>,</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Bootstrapped Sampling Distribution of Age Coefficient"</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> p_ols_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>p_ols_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
</div>
<p>Congratulations you’ve just produced and visualized your first bootstrapped sampling distribution!</p>
<p>Conceptually, this distribution describes *how much we would expect the coefficient on age in model to vary** from sample to sample.</p>
<p>Just from eyeballing the figure above, it looks like the observed the relationship between age and support for war or 0.009 could be about as high as 0.011, and as low as 0.007.</p>
<p>Of course, as the budding quantitative social scientists that we are, we can do better than just eyeballing the data.</p>
</section>
</section>
<section id="quantify-the-uncertainy-described-by-your-sampling-distributions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Quantify the uncertainy described by your sampling distributions</h1>
<p>Specifically, please calculate the standard deviations, 97.5 and 2.5 percentiles of each coefficient in <code>bs_old_df</code></p>
<p>You’ll want to</p>
<ul>
<li><code>group_by()</code> the <code>term</code> variable in <code>bs_ols_df</code></li>
<li><code>summarize()</code> the output of functions applied to the <code>estimate</code> column in <code>bs_ols_df</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>bs_ols_df <span class="sc">%&gt;%</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(term)<span class="sc">%&gt;%</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_estimate =</span> <span class="fu">mean</span>(estimate),</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(estimate,<span class="at">na.rm=</span>T),</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">p2_5 =</span> <span class="fu">quantile</span>(estimate, <span class="at">prob =</span>.<span class="dv">025</span>),</span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">p97_5 =</span> <span class="fu">quantile</span>(estimate, <span class="at">prob =</span>.<span class="dv">975</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in summarize(., mean_estimate = mean(estimate), sd = sd(estimate, : could not find function "summarize"</code></pre>
</div>
</div>
<p>Please compare these these estimates to those by the following functions</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(m1)</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co"># confint(m1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>They’re similar to a few thousandsth of a decimal place.</p>
<p>In fact, we can approximate the sampling distribution of coefficients two ways:</p>
<ul>
<li><p>Using simulation based approaches like the bootstrap procedure we implemented above</p></li>
<li><p>Using asymptotic theory (i.e the Central Limit Theorem) to derive the theoretical sampling distributions</p></li>
</ul>
<p>Below we see compare the two approaches (bootstrapped distribution in black, asymptotic normal distribution in red dots) and see they look quite similar.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>p_ols_age <span class="sc">+</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> <span class="st">"dnorm"</span>, </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">args =</span> <span class="fu">list</span>(<span class="at">mean =</span><span class="fu">coef</span>(m1)[<span class="dv">2</span>],</span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">sd =</span> <span class="fu">summary</span>(m1)<span class="sc">$</span>coef[<span class="dv">2</span>,<span class="dv">2</span>]),</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">"red"</span>,</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">linetype =</span> <span class="dv">3</span></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'p_ols_age' not found</code></pre>
</div>
</div>
</section>
<section id="explore-other-relationships-in-the-data." class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Explore other relationships in the data.</h1>
<p>Finally, let’s take some time to explore other variables and relationships in the data.</p>
<p>Please do the following:</p>
<ul>
<li><p><strong>Research Question</strong>: Formulate a brief research question here</p></li>
<li><p><strong>Data</strong>: Identify the relevant outcome and predictor variables in the data.</p>
<ul>
<li>Outcome:</li>
<li>Key Predictor:</li>
<li>Covariates:
<ul>
<li>Covariate 1</li>
</ul></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Explore the data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>If necessary, transform and recode the data as needed</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data transformations if necessary</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Models and Expecations</strong> Specify a model or models to test your question in terms of our outcome and predictor variables.</li>
</ul>
<p><span class="math display">\[\text{Outcome} = \beta_0 + \beta_1 \text{Key Predictor} + \beta_2 \text{Covariate}\]</span></p>
<ul>
<li><p><strong>Expectations</strong> Discuss the expected sign and significance of the coefficients in your model. If you think a coefficient could be either positive or negative, explain what each of these results means in the context of your question.</p></li>
<li><p><strong>Estimation</strong> Estimate a model or models to test your question.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Models</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Results</strong> Present and interpret your results using tables and figures.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Regression table</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Figures</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
<ul>
<li><p>Research Question: What effect does social media use have on Russian’s Support for the War? Does the effect of social media vary with age</p></li>
<li><p>Data:</p>
<ul>
<li><p>Outcome: <code>support_war01</code></p></li>
<li><p>Key Predictor: <code>total_social_media_use</code> a count from 0 (none) to 9 social media sites</p></li>
<li><p>Additional predictors:</p>
<ul>
<li>Age</li>
<li>Sex</li>
<li>Education</li>
<li>Employment</li>
</ul></li>
</ul></li>
<li><p>Data transformations: To simplify interpretation, I will create some indicator variables</p>
<ul>
<li><code>under30</code> an indicator that takes a value of 1 the respondent is under 30 and 0 otherwise</li>
</ul></li>
<li><p>Models and Expectations</p></li>
<li><p>Baseline Model:</p></li>
</ul>
<p><span class="math display">\[\text{Support} = \beta_0 + \beta_1 \text{social media}  +\epsilon\]</span> - Expectations:</p>
<ul>
<li><p>If <span class="math inline">\(\beta_1\)</span> is positive this would suggest that higher social media use associated with greater support for the war. Perhaps respondents in russia are more likely to encounter state propaganda</p></li>
<li><p>If <span class="math inline">\(\beta_1\)</span> is negative, this implies that greater social media use is associated with less support. Perhaps sites like Twitter/Facebook/TikTok in early March allowed Russians to encounter non-state media</p></li>
<li><p>Baseline Model with Controls:</p></li>
</ul>
<p><span class="math display">\[\text{Support} = \beta_0 + \beta_1 \text{social media} + X\beta +\epsilon\]</span> - Expectations: - If the coefficient on <span class="math inline">\(\beta_1\)</span> is no longer signficant, this suggests that the bivariate relationship was spurious, driven by factors <span class="math inline">\(X\)</span> that predict both support and social media use. For example, it may be that the educated are more likely to use social media and less likely to support the war. Controlling for education then might remove the association between social media use and support.</p>
<ul>
<li>Interaction Model with Controls:</li>
</ul>
<p><span class="math display">\[\text{Support} = \beta_0 + \beta_1 \text{Social Media} +\beta_2\text{Under 30} + \beta_3\text{SM}\times\text{U30} + X\beta +\epsilon\]</span> - Expectations: - The key coefficient in this model is <span class="math inline">\(\beta_3\)</span> which assesses whether the relationship between social media use and support differs for those under 30 compared to those over 30. It’s possible that young people use social media differently than older folks, and so I’d expect this coefficient to be negative.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ---- Data</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>df_drww <span class="sc">%&gt;%</span></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">under30 =</span> <span class="fu">case_when</span>(</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>      age <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>      T <span class="sc">~</span> <span class="dv">0</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">any_social =</span> <span class="fu">case_when</span>(</span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a>      total_social_media_use <span class="sc">==</span><span class="dv">0</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a>      T <span class="sc">~</span> <span class="dv">1</span></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> df_drww</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in mutate(., under30 = case_when(age &lt; 30 ~ 1, T ~ 0), any_social = case_when(total_social_media_use == : could not find function "mutate"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>m1_ex <span class="ot">&lt;-</span> <span class="fu">glm</span>(support_war01 <span class="sc">~</span> total_social_media_use, </span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>             df_drww, <span class="at">family =</span> binomial)</span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>m2_ex <span class="ot">&lt;-</span> <span class="fu">glm</span>(support_war01 <span class="sc">~</span> total_social_media_use <span class="sc">+</span> </span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>               age <span class="sc">+</span> sex <span class="sc">+</span> education_n <span class="sc">+</span>employ_working, </span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>             df_drww, <span class="at">family =</span> binomial)</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>m3_ex <span class="ot">&lt;-</span> <span class="fu">glm</span>(support_war01 <span class="sc">~</span> total_social_media_use<span class="sc">*</span>under30 <span class="sc">+</span> </span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>               sex <span class="sc">+</span> education_n <span class="sc">+</span> employ_working, </span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>             df_drww, <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(predvars, data, env): object 'under30' not found</code></pre>
</div>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">htmlreg</span>(<span class="fu">list</span>(m1_ex,m2_ex, m3_ex))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Error in htmlreg(list(m1_ex, m2_ex, m3_ex)): could not find function "htmlreg"</code></pre>
<p>Overall, social media use appears to be associated with less support for the war in Ukraine among Russians.</p>
<p>As the first figure below shows, the baseline model, predicting support with only social media use appears to show a dramatic decline of nearly 40 percentage points in support.</p>
<p>Controlling for other factors likely to predict support and social media use, the decrease is less dramatic, but still, going from no social media use to a using a lot (nine) sites is associated with a about a 17 percentage point decrease in support for the war.</p>
<p>Contray to my expectations, the effect of social media doesn’t appear to vary by age cohort. Support decreases with social medial use for both those over and under 30 but the rate of decrease is not statistically different.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex1 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_social_media_use =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">mean</span>(df_drww<span class="sc">$</span>age, <span class="at">na.rm =</span> T),</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="st">"Female"</span>,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">education_n =</span> <span class="fu">mean</span>(df_drww<span class="sc">$</span>education_n, <span class="at">na.rm =</span> T),</span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">employ_working =</span> <span class="dv">1</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in expand_grid(total_social_media_use = 0:9, age = mean(df_drww$age, : could not find function "expand_grid"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex1<span class="sc">$</span>pred_m1 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1_ex, pred_df_ex1, <span class="at">type =</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'pred_df_ex1' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex1<span class="sc">$</span>pred_m2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m2_ex, pred_df_ex1, <span class="at">type =</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'pred_df_ex1' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex1<span class="sc">%&gt;%</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_social_media_use, pred_m1))<span class="sc">+</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">col =</span> <span class="st">"Bivariate"</span>))<span class="sc">+</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pred_m2, <span class="at">col =</span> <span class="st">"Controls"</span>))<span class="sc">+</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">"Model"</span>,</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of Social Media Sites Used"</span>,</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Support for the War"</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in ggplot(., aes(total_social_media_use, pred_m1)): could not find function "ggplot"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex2 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">total_social_media_use =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">9</span>,</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">under30 =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="st">"Female"</span>,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">education_n =</span> <span class="fu">mean</span>(df_drww<span class="sc">$</span>education_n, <span class="at">na.rm =</span> T),</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">employ_working =</span> <span class="dv">1</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in expand_grid(total_social_media_use = 0:9, under30 = c(0, 1), : could not find function "expand_grid"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex2<span class="sc">$</span>pred_m3 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m3_ex, pred_df_ex2, <span class="at">type =</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'm3_ex' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex2<span class="sc">%&gt;%</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="fu">case_when</span>(</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>      under30 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Under 30"</span>,</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>      T <span class="sc">~</span> <span class="st">"30 and Over"</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_social_media_use, pred_m3, <span class="at">col =</span> Age))<span class="sc">+</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()<span class="sc">+</span></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb82-12"><a href="#cb82-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of Social Media Sites Used"</span>,</span>
<span id="cb82-13"><a href="#cb82-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Support for the War"</span></span>
<span id="cb82-14"><a href="#cb82-14" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in ggplot(., aes(total_social_media_use, pred_m3, col = Age)): could not find function "ggplot"</code></pre>
</div>
</div>
<p>Young folk are considerably more likely to use social media</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>df_drww <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="fu">case_when</span>(</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>      under30 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Under 30"</span>,</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>      T <span class="sc">~</span> <span class="st">"30 and Over"</span></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(total_social_media_use,<span class="at">fill =</span>Age))<span class="sc">+</span></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span> ..density..))<span class="sc">+</span></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>Age)<span class="sc">+</span></span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Social Media Sites Used"</span></span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in ggplot(., aes(total_social_media_use, fill = Age)): could not find function "ggplot"</code></pre>
</div>
</div>
<p>If we were to instead compare those over and under 30 by any social media use vs no social media use, we see that the decrease in support is much larger among the young (although not statistically significant…)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>m4_ex <span class="ot">&lt;-</span> <span class="fu">glm</span>(support_war01 <span class="sc">~</span> any_social<span class="sc">*</span>under30 <span class="sc">+</span> </span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>               sex <span class="sc">+</span> education_n <span class="sc">+</span> employ_working, </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>             df_drww, <span class="at">family =</span> binomial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(predvars, data, env): object 'any_social' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4_ex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'm4_ex' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex3 <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">any_social =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">under30 =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex =</span> <span class="st">"Female"</span>,</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">education_n =</span> <span class="fu">mean</span>(df_drww<span class="sc">$</span>education_n, <span class="at">na.rm =</span> T),</span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">employ_working =</span> <span class="dv">1</span></span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in expand_grid(any_social = 0:1, under30 = c(0, 1), sex = "Female", : could not find function "expand_grid"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex3<span class="sc">$</span>pred_m4 <span class="ot">&lt;-</span> <span class="fu">predict</span>(m4_ex, pred_df_ex3, <span class="at">type =</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'm4_ex' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>pred_df_ex3<span class="sc">%&gt;%</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">Age =</span> <span class="fu">case_when</span>(</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>      under30 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Under 30"</span>,</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>      T <span class="sc">~</span> <span class="st">"30 and Over"</span></span>
<span id="cb94-6"><a href="#cb94-6" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb94-7"><a href="#cb94-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Media =</span> <span class="fu">case_when</span>(</span>
<span id="cb94-8"><a href="#cb94-8" aria-hidden="true" tabindex="-1"></a>      any_social <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Social Media"</span>,</span>
<span id="cb94-9"><a href="#cb94-9" aria-hidden="true" tabindex="-1"></a>      T <span class="sc">~</span> <span class="st">"No Social Media"</span></span>
<span id="cb94-10"><a href="#cb94-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb94-11"><a href="#cb94-11" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb94-12"><a href="#cb94-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Media, pred_m4, <span class="at">fill =</span> Age))<span class="sc">+</span></span>
<span id="cb94-13"><a href="#cb94-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>( <span class="at">stat =</span> <span class="st">"identity"</span>)<span class="sc">+</span></span>
<span id="cb94-14"><a href="#cb94-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>Age)<span class="sc">+</span></span>
<span id="cb94-15"><a href="#cb94-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb94-16"><a href="#cb94-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb94-17"><a href="#cb94-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of Social Media Sites Used"</span>,</span>
<span id="cb94-18"><a href="#cb94-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Support for the War"</span></span>
<span id="cb94-19"><a href="#cb94-19" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in ggplot(., aes(Media, pred_m4, fill = Age)): could not find function "ggplot"</code></pre>
</div>
</div>


</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>I think, google translate was a bit unclear. But higher numbers equal more education.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>