{
  "hash": "cdcc575444e4604f2a1e7f1d66125e72",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Week 11:\"\nsubtitle: \"Quantifying Uncertainty with Hypothesis Testing\"\nauthor: \"Paul Testa\"\nformat: \n  revealjs:\n    theme: [default, brownslides.scss]\n    logo: images/pols1600_hex.png\n    footer: \"POLS 1600\"\n    multiplex: false\n    transition: fade\n    slide-number: c\n    incremental: true\n    center: false\n    menu: true\n    scrollable: true\n    highlight-style: github\n    progress: true\n    code-overflow: wrap\n    # include-after-body: title-slide.html\n    title-slide-attributes:\n      align: left\n      data-background-image: images/pols1600_hex.png\n      data-background-position: 90% 50%\n      data-background-size: 40%\nexecute: \n  echo: true\nfilters:\n  - openlinksinnewpage\n---\n\n\n\n\n\n\n\n\n\n\n\nclass: inverse, center, middle \\# Overview\n\n## General Plan\n\n-   Setup\n\n-   Review: Confidence Intervals\n\n-   Lecture : Hypothesis Testing\n\n-   Demo: Final Projects\n\n## Course Plan\n\n-   April 18: Lecture -- Hypothesis Testing\n\n-   April 20 Lab -- Hypothesis Testing and Interval Estimation\n\n-   April 25: Lecture -- Course Review\n\n-   April 27: Workshop:\n\n-   April 30: Take Home Final Exam\n\n-   May ?: Tacos or Pizza with POLS 1140?\n\n-   May 7: Take Home Final Exam due\n\nclass:inverse, middle, center \\# 💪 \\## Get set up to work\n\n## New packages\n\nTo easily load survey data for our question, we'll need the `anesr` package, which loads data from the American National Election Studies into R\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Uncomment to uninstall package to download NES survey data\n# library(devtools)\n# install_github(\"jamesmartherus/anesr\")\nrequire(anser)\n```\n:::\n\n\n\n## Packages for today\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nthe_packages <- c(\n  ## R Markdown\n  \"kableExtra\",\"DT\",\"texreg\",\n  ## Tidyverse\n  \"tidyverse\", \"lubridate\", \"forcats\", \"haven\", \"labelled\",\"purrr\",\n  ## Extensions for ggplot\n  \"ggmap\",\"ggrepel\", \"ggridges\", \"ggthemes\", \"ggpubr\", \n  \"GGally\", \"scales\", \"dagitty\", \"ggdag\", \"ggforce\",\n  # Graphics:\n  \"scatterplot3d\", #<<\n  # Data \n  \"COVID19\",\"maps\",\"mapdata\",\"qss\",\"tidycensus\", \"dataverse\", \n  # Analysis\n  \"DeclareDesign\", \"modelr\", \"zoo\"\n)\n```\n:::\n\n\n\n## Define a function to load (and if needed install) packages\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nipak <- function(pkg){\n    new.pkg <- pkg[!(pkg %in% installed.packages()[, \"Package\"])]\n    if (length(new.pkg)) \n        install.packages(new.pkg, dependencies = TRUE)\n    sapply(pkg, require, character.only = TRUE)\n}\n```\n:::\n\n\n\n## Load packages for today\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nipak(the_packages)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   kableExtra            DT        texreg     tidyverse     lubridate \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      forcats         haven      labelled         purrr         ggmap \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      ggrepel      ggridges      ggthemes        ggpubr        GGally \n         TRUE          TRUE          TRUE          TRUE          TRUE \n       scales       dagitty         ggdag       ggforce scatterplot3d \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      COVID19          maps       mapdata           qss    tidycensus \n         TRUE          TRUE          TRUE          TRUE          TRUE \n    dataverse DeclareDesign        modelr           zoo \n         TRUE          TRUE          TRUE          TRUE \n```\n\n\n:::\n:::\n\n\n\nclass:inverse, middle, center \\# 🔍 \\# Review \\## Confidence Intervals\n\n## Confidence Intervals\n\n-   Statistical inference involves quantifying uncertainty about what could have happened\n\n-   We can describe this uncertainty in terms of a sampling distribution (what could have happened had we had a different sample)\n\n-   The standard deviation of a sampling distribution describes its width (spread) and is called a standard error\n\n-   Standard errors decrease with by the $\\sqrt{N}$ where $N$ is the size of our sample\n\n-   We can estimate standard errors via simulation or analytically.\n\n    -   Simulations require fewer assumptions, but take more time.\n\n    -   Analytic estimates are are quick, but require more assumptions.\n\n-   We use standard errors to construct confidence intervals which we interpret as describing a range of plausible values for the thing we're trying to estimate.\n\n-   Any one 95% confidence interval may or may not contain the truth, but in repeated sampling, 95% of the intervals we construct would contain the truth.\n\n## Standard Errors of Regression Coefficients\n\nLast class, we calculated the standard error of a sample mean using bootstrapping.\n\nWe can take the same approach for regression coefficients:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nload(url(\"https://pols1600.paultesta.org/files/data/df_drww.rda\"))\n\n# Fit model\nm1 <- lm(support_war01 ~ age + education_n + sex, df_drww)\n# set seed\nset.seed(123)\n# 1,000 bootstrap samples\nboot <- modelr::bootstrap(df_drww, 1000)\n# Estimate Boostrapped Models\nm1_bs <- purrr::map(boot$strap, ~ lm(support_war01 ~ age + education_n + sex, data =.))\n# Tidy coefficients\nm1_bs_df <- map_df(m1_bs, tidy, .id = \"id\")\n```\n:::\n\n\n\n## Bootstrapped Standard Errors\n\nThen we simply calculate the standard error of for the sampling distribution of each coefficient\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_bs_df %>%\n  group_by(term)%>%\n  summarize(\n    bs_se = sd(estimate)\n  ) -> m1_bs_se\nm1_bs_se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  term           bs_se\n  <chr>          <dbl>\n1 (Intercept) 0.0564  \n2 age         0.000717\n3 education_n 0.0108  \n4 sexMale     0.0223  \n```\n\n\n:::\n:::\n\n\n\n## Analytic Standard Errors.\n\nAlternatively, we can derive the standard error of the sampling distribution **analytically** using **asymptotic** theory (e.g. the Central Limit Theorem).\n\nThe process starts by defining the quantity we want to know: the variance of our estimated coefficients $\\hat{\\beta}$ around their true values in the population $\\beta$:\n\n$$V(\\hat{\\beta}|X) =(E[(\\hat{\\beta} - \\beta)(\\hat{\\beta} - \\beta)' |X]$$\n\nYour textbook walks through the math to estimate this quantity on pages 375-380 for simple bivariate regression (i.e. a regression with 1 predictor)\n\n[In the notes](https://pols1600.paultesta.org/notes/10-notes.html#Assymptotic_Standard_Errors), you'll find some further discussion of the math for the more general case of with multiple predictors.\n\nThis is also an excellent walk through of the [linear algebra](https://towardsdatascience.com/a-deep-dive-into-the-variance-covariance-matrices-of-classical-linear-regression-models-4322b2cdc8e6)\n\n## Analytic Standard Errors.\n\nEssentially, if you expand terms from:\n\n$$V(\\hat{\\beta}|X) =(E[(\\hat{\\beta} - \\beta)(\\hat{\\beta} - \\beta)' |X]$$\n\nmake substitutions and some assumptions about the distribution of $\\epsilon$, you arrive at a formula for the \"Variance Covariance Matrix\" of the model:\n\n$$V(\\hat{\\beta}|X) = \\sigma^2(X'X)^{-1}$$ Which is a function of\n\n-   $\\sigma^2$ the \"Sum of Square Errors\"\n-   $(X'X)^{-1}$ roughly captures the underlying variance and covariance of the predictors in your model, where:\n    -   $X$ is a matrix of predictors (each row is an observation, each column a variable)\n    -   $X'X$ is a symmetric maxtrix (like squaring a variable, but in linear algerba)\n    -   $X'X^{-1}$ is the inverse of this matrix\n    -   $sigma^2(X'X)^{-1}$ is like dividing $\\sigma^2$ by $X'X$\n\n## Analytic Standard Errors.\n\nThe square root of the elements on the diagonal of $V(\\hat{\\beta}|X)$ provides the standard error for each coefficient, which is larger if:\n\n-   if $\\sigma^2$ is large (When there's a lot of unexplained variance, our uncertainty is high)\n-   the variance of $X$ is small (When predictors don't vary much our uncertainty increases)\n\n## Analytic Standard Errors.\n\nIn practice, you will let your computer calculate these standard errors.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m1)$coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept)  0.277540588 0.0529197543  5.244555 1.797036e-07\nage          0.009216952 0.0007129459 12.927982 2.827291e-36\neducation_n -0.015814493 0.0108357258 -1.459477 1.446491e-01\nsexMale      0.094320479 0.0225358310  4.185356 3.017253e-05\n```\n\n\n:::\n:::\n\n\n\n## Analytic Standard Errors by Hand\n\nJust for fun:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Sum of Squared Residuals\nsigma_2 <- sum(resid(m1)^2)/m1$df.residual\n# X transpose X\nXtXinv <- solve(t(model.matrix(m1))%*%model.matrix(m1))\n# SE is square root of diagonal of Variance Covariance Matrix\nsqrt(diag(sigma_2*XtXinv))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)          age  education_n      sexMale \n0.0529197543 0.0007129459 0.0108357258 0.0225358310 \n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(m1)$coef[,2]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)          age  education_n      sexMale \n0.0529197543 0.0007129459 0.0108357258 0.0225358310 \n```\n\n\n:::\n:::\n\n\n\n## Constructing Confidence Intervals for Regression Coefficients\n\n1.  Estimate the model to obtain coefficients $\\hat{\\beta}$\n\n2.  Calculate Standard Errors using simulation or asymptotic theory\n\n3.  Choose desired confidence level $\\alpha$ with a corresponding critical value $z_{\\alpha/2}$ derived from an approximation of the hypotehtical sampling distribution\n\n4.  Construct a $(1-\\alpha)\\times 100 \\%$ percent confidence interval:\n\n$$CI(\\alpha) = [\\hat{\\beta} - z_{\\alpha/2} \\times \\text{standard error}, \\hat{\\beta} + z_{\\alpha/2} \\times \\text{standard error}]$$\n\n1.  Estimate the model to obtain coefficients $\\hat{\\beta}$\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbeta <- coef(m1)\nbeta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)          age  education_n      sexMale \n 0.277540588  0.009216952 -0.015814493  0.094320479 \n```\n\n\n:::\n:::\n\n\n\n2.  Calculate Standard Errors using simulation or asymptotic theory\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nse <- summary(m1)$coef[,2]\nse\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n (Intercept)          age  education_n      sexMale \n0.0529197543 0.0007129459 0.0108357258 0.0225358310 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Similar to bs\nm1_bs_se\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  term           bs_se\n  <chr>          <dbl>\n1 (Intercept) 0.0564  \n2 age         0.000717\n3 education_n 0.0108  \n4 sexMale     0.0223  \n```\n\n\n:::\n:::\n\n\n\n## Constructing Confidence Intervals for Regression Coefficients\n\n3.  Calculate critical value\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nz_fs <- abs(qt(.05/2, m1$df.residual))\nz_fs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.961591\n```\n\n\n:::\n:::\n\n\n\n-   Note: For finite samples we use a $t$ distribution...\n\n## Constructing Confidence Intervals for Regression Coefficients\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nll <- beta - z_fs *se\nul <- beta + z_fs *se\ncbind(ll,ul)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      ll          ul\n(Intercept)  0.173733660 0.381347516\nage          0.007818443 0.010615460\neducation_n -0.037069758 0.005440772\nsexMale      0.050114390 0.138526568\n```\n\n\n:::\n\n```{.r .cell-code}\n# Compare to R:\nconfint(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                   2.5 %      97.5 %\n(Intercept)  0.173733660 0.381347516\nage          0.007818443 0.010615460\neducation_n -0.037069758 0.005440772\nsexMale      0.050114390 0.138526568\n```\n\n\n:::\n:::\n\n\n\n## Presenting Confidence Intervals in a Regression Table:\n\n````         \n\n```{r, results=\"asis\"}`r''`\ntexreg::htmlreg(m1, \n  digits = 3, \n  ci.force = T)\n```\n````\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntexreg::htmlreg(m1,\n        digits = 3, \n        ci.force = T)\n```\n\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.278<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.174; 0.381]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.009<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.008; 0.011]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">education_n</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[-0.037; 0.005]</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">sexMale</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.094<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">[ 0.050; 0.138]</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.107</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.106</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">1463</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"2\"><sup>&#42;</sup> 0 outside the confidence interval.</td>\n</tr>\n</tfoot>\n</table>\n:::\n\n\n\n## Tidying Regression Models\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1 %>%\n  tidy(., conf.int =  T) -> m1_df\nm1_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 7\n  term        estimate std.error statistic  p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n1 (Intercept)  0.278    0.0529        5.24 1.80e- 7  0.174     0.381  \n2 age          0.00922  0.000713     12.9  2.83e-36  0.00782   0.0106 \n3 education_n -0.0158   0.0108       -1.46 1.45e- 1 -0.0371    0.00544\n4 sexMale      0.0943   0.0225        4.19 3.02e- 5  0.0501    0.139  \n```\n\n\n:::\n:::\n\n\n\n## Coefficient Plots as an Alternative to Regression Tables\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_df %>%\n  filter(term !=  \"(Intercept)\")%>%\n  ggplot(aes(x = estimate, \n             y= term, \n             xmin = conf.low,\n             xmax = conf.high,\n             label = round(estimate,3)\n             ))+\n  geom_pointrange()+\n  geom_text(vjust=-1.5)+\n  geom_vline(xintercept = 0, linetype =2)+\n  theme_bw()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides-old_files/figure-html/unnamed-chunk-20-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Confidence Intervals: Summary\n\n**What is a sampling distribution?**\n\n-   A distribution of values we would have observed upon repeated sampling\n-   Bootstrapping (sampling from a sample) approximates the width of the sampling distribution\n\n**What is a standard error?**\n\n-   Standard deviation of the sampling distribution\n    -   Describes the width or range of plausible observations we would see.\n    -   Decreases as the sample size increases\n\n## Confidence Intervals: Summary\n\n**What is a confidence interval**\n\n-   Coverage interval for a sampling distribution\n    -   \"A confidence interval is a way of expressing the precision or repeatability of a statistic, how much variation would likely be present across the possible different random samples from the population\"\n-   Three components:\n    -   Point Estimate (i.e. a mean, or coefficient)\n    -   Confidence Level (Often 95 percent by convention)\n    -   Margin of Error (+/- some range (typically 2\\*SD for 95 percent CI))\n-   Confidence is about the interval\n    -   95 percent of the intervals construct in this manner would contain the truth.\n\nclass: inverse, center, middle \\# 💡 \\# Hypothesis Testing \\## How likely is it that we would see what did if our hypothesis were true\n\n## What is a hypothesis test\n\n-   A formal way of assessing statistical evidence. Combines\n\n    -   **Deductive reasoning** (distribution of a test statistic, if the a null hypothesis were true )\n\n    -   **Inductive reasoning** (based on the test statistic we observed, how likely is it that we would observe it if the null were true?)\n\n## What is a test statistic?\n\n-   A way of summarizing data\n\n    -   difference of means\n\n    -   coefficients from a linear model\n\n    -   **coefficients from a linear model divded by their standard errors**\n\n    -   R\\^2\n\n## What is a null hypothesis?\n\n-   A statement about the world\n\n    -   Only interesting if we reject it\n\n    -   Would yield a distribution of test statistics \"under the null\"\n\n    -   Typically something like \"X has no effect on Y\" (Null = no effect)\n\n    -   Never accept the null can only reject\n\n## What is a p-value?\n\n-   A p-value is a conditional probability summarizing the likelihood of observing a test statistic as far from our hypothesis or farther, if our hypothesis were true.\n\n-   It's the area in the \"tails of the curve\" of the distribution of the test statistic under the null.\n\n## How do we do hypothesis testing?\n\n0.  Posit a hypothesis (e.g. $\\beta = 0$)\n\n--\n\n1.  Calculate the test statistic (e.g. $(\\hat{\\beta}-\\beta)/se_\\beta$)\n\n--\n\n2.  Derive the distribution of the test statistic under the null via\n\n-   Simulation\n-   Asymptotic theory\n\n--\n\n3.  Compare the test statistic to the distribution under the null\n\n    -   If it's in the tails $\\to$ very unlikely that we would observe what we did if our hypothesis were true\n\n--\n\n4.  Calculate p-value\n    -   Quantify how often we would see test statistics as big or bigger\n    -   Two-side tests: how often do we see test statics as big or bigger in absolute value as our observed test statistic\n    -   One-side test: how often do we see test statistics as extreme as our observed statistic in a particular direction (positive/negative)\n\n--\n\n5.  Reject or fail to reject/retain our hypothesis based on some threshold of statistical significance (e.g. p \\< 0.05)\n\n## Outcomes of Hypothesis Tests\n\n-   Two conclusions from of a hypothesis test: we can reject or fail to reject a hypothesis test.\n\n-   **We never \"accept\" a hypothesis**, since there are, in theory, an infinite number of other hypotheses we could have tested.\n\nOur decision can produce four outcomes and two types of error:\n\n|                | Reject $H_0$   | Fail to Reject $H_0$ |\n|----------------|----------------|----------------------|\n| $H_0$ is true  | False Positive | Correct!             |\n| $H_0$ is false | Correct!       | False Negative       |\n\n## Outcomes of Hypothesis Tests\n\n|                | Reject $H_0$   | Fail to Reject $H_0$ |\n|----------------|----------------|----------------------|\n| $H_0$ is true  | False Positive | Correct!             |\n| $H_0$ is false | Correct!       | False Negative       |\n\nSuppose we chose to reject a hypothesis if our p-value was less than 0.05.\n\nWhat we're saying is that we're willing to falsely reject our hypothesis 5 times out of 100.\n\nTypically we want to minimize this false positive rate (Type 1 error), but there's a trade off:\n\n-   Reducing Type 1 error means, we're more likely to make a Type 2 error -- failing to reject when our null is false.\n\nclass:inverse, middle, center \\# 💪 \\## Application: Hypothesis Testing for Linear Models\n\n## 0. Posit a Null Hypothesis\n\n-   Typically, we will test a null hypothesis that the coefficient for variable $X$ equals 0 (e.g. $H_0: \\beta_x = 0$ )\n\n-   Our alternative hypothesis in a two sided test then is that $\\beta_0$ doesn't equal 0 ($H_1: \\beta_x \\neq 0$)\n\n-   In a one-sided test, our alternative is directional ($H_1: \\beta_x > 0$ or $H_1: \\beta_x < 0$ )\n\n    -   One-sided tests are rare in practice -- need a strong substantive reason for directional expectation\n\n## 1. Calculate the test statistic\n\nFor a linear regression, we could use the $\\hat{\\beta}$ as our test statistic.\n\nIn practice, we we use a \"t-stat\" which is our observed coefficiet, $\\hat{\\beta}$ minus our hypothesized value $\\beta$ (e.g. 0), divided by the standard error of $\\hat{\\beta}$.\n\n$$t= \\frac{\\hat\\beta-\\beta}{\\widehat{SE}_{\\hat{\\beta}}} \\sim \\text{Students's } t \\text{ with } n-k \\text{ degrees of freedom}$$ Fisher showed that this statistic from a regression follows a $t$ distribution -- which looks like a normal distribution but with \"fatter tails\" (e.g. more probability assigned to extreme values)\n\n## 1. Calculate the test statistic in R\n\nWe can caclulate test statistics from our model by dividing the coefficients by their standard errors\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt_stat <- coef(m1) / summary(m1)$coef[,2]\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age education_n     sexMale \n   5.244555   12.927982   -1.459477    4.185356 \n```\n\n\n:::\n:::\n\n\n\nWhich is exactly what the third column of `summary()` shows\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m1)$coef\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Estimate   Std. Error   t value     Pr(>|t|)\n(Intercept)  0.277540588 0.0529197543  5.244555 1.797036e-07\nage          0.009216952 0.0007129459 12.927982 2.827291e-36\neducation_n -0.015814493 0.0108357258 -1.459477 1.446491e-01\nsexMale      0.094320479 0.0225358310  4.185356 3.017253e-05\n```\n\n\n:::\n:::\n\n\n\n## 2. Derive the distribution of the test statistic under the null via\n\nTwo approaches:\n\n-   Simulation: Calculate test statistics in a world where $H_0$ is true\n\n-   Asymptotic theory: Use statistics to approximate this distribution\n\n## 2. Derive the distribution of the test statistic under the null\n\nWe can make the null true, by **randomly permuting** (sampling without replacement) the outcome of our model:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# One perumtation\nset.seed(123)\ndf_drww$support_war01_null <- sample(df_drww$support_war01)\n```\n:::\n\n\n\nOur permuted outcome is now uncorrelated with any predictors, it's just a random sample of 0s, and 1s.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(df_drww$support_war01, df_drww$age, use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3093656\n```\n\n\n:::\n\n```{.r .cell-code}\ncor(df_drww$support_war01_null, df_drww$age, use = \"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.0005132924\n```\n\n\n:::\n:::\n\n\n\n## 2. Derive the distribution of the test statistic under the null\n\nAs such when we estimate a model with data where we have made our null hypothesis true (e.g $\\beta = 0$ for all predictors), we get coefficients that are close to 0. Of course, by chance some might be a little negative, or a little positive.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_null <- lm(support_war01_null ~ age + education_n + sex, df_drww)\n\ntidy(m1_null)%>%mutate_if(is.numeric, round,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)     0.74      0.05     13.6     0   \n2 age             0         0        -0.07    0.94\n3 education_n    -0.01      0.01     -0.8     0.43\n4 sexMale         0.02      0.02      0.65    0.52\n```\n\n\n:::\n:::\n\n\n\n## 2. Derive the distribution of the test statistic under the null\n\nThe logic of hypothesis testing is to compare what we observed, to what we could have observed when our null is true.\n\nBy repeatedly permuting our outcome, estimating models, caclulating test statistics to generate the distributions **under the null**\n\nTo do this, we'll write a function to make our life easier:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmy_null_fn <- function(\n  df=df_drww, \n  y = \"support_war01\", \n  f = formula(m1)\n  ){\n  df[, y] <- sample(df[,y])\n  m <- lm(f, df)\n  stat <- summary(m)$coef[,3]\n  return(stat)\n}\nmy_null_fn()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age education_n     sexMale \n 11.0493734   1.8113230   0.9787517   0.6637328 \n```\n\n\n:::\n\n```{.r .cell-code}\nmy_null_fn()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)         age education_n     sexMale \n 13.8126681   0.3840811  -1.4405531  -0.9781048 \n```\n\n\n:::\n:::\n\n\n\n## 2. Derive the distribution of the test statistic under the null\n\nThen we'll use the `replicate()` function to repeat this process 1000, saving the distribution of test statistics $((\\hat{\\beta}-\\beta)/se_\\beta)$ to an object called `m1_null`\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(123)\nm1_null <- data.frame(t(\n  replicate(1000, my_null_fn(df_drww, \"support_war01\",formula(m1)))))\nhead(m1_null)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  X.Intercept.         age education_n    sexMale\n1     13.58601 -0.06917489  -0.7952217  0.6460818\n2     11.04937  1.81132298   0.9787517  0.6637328\n3     13.81267  0.38408113  -1.4405531 -0.9781048\n4     13.15015  0.04525689  -0.9986349  1.0681923\n5     13.41492 -0.59487147   0.4026906 -1.5637179\n6     13.43857 -1.11574477   0.3126860 -0.7188458\n```\n\n\n:::\n:::\n\n\n\n## 2. Derive the distribution of the test statistic under the null\n\nWe can visualize this distribution of test statistics for the `education_n`:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_null %>%\n  ggplot(aes(education_n))+\n  geom_density()+\n  geom_rug()+\n  geom_vline(xintercept = 0, linetype =2)+\n  theme_bw()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides-old_files/figure-html/unnamed-chunk-29-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## 2. Compare Permutation Distribution to Asymptotic t-Distribution\n\nThis simulated distribution (grey) can be approximated by a $t$ distribution (black), with $n$ (the number of observations) minus $k$ (the number of coefficients in our model) degrees of freedom.\n\n-   Roughly, you can think of \"degrees of freedom\" as a way of reflecting the fact that we have to estimate parameters of the distribution, and so we use up pieces of information (degrees of freedom),\n-   Because we're estimating parameters our uncertainty (the spread of the distribution) increases as the degrees of freedom decreases\n-   For a small $N$ reducing degrees of freedom, can increase uncertainty a lot\n-   For a large $N$ the differences are minute\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_null %>%\n  ggplot(aes(education_n))+\n  geom_density(col = \"grey\")+\n  geom_rug()+\n  geom_vline(xintercept = 0, linetype =2)+\n  stat_function(fun =dt,args =list(df = m1$df.residual), #<<\n                xlim =c(-3.5,3.5))+ #<<\n  theme_bw()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides-old_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## 3. Compare the test statistic to the distribution assuming the null were true\n\nNext we'll compare our observed test statistic -1.45 to its hypothesized distribution under the null\n\n-   For a two sided test, we interested in absolute distance from the null, so we'll put lines at both -1.45 and 1.45\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_null %>%\n  ggplot(aes(education_n))+\n  geom_density(col = \"grey\")+\n  geom_rug()+\n  geom_vline(xintercept = 0, linetype =2)+\n  stat_function(fun =dt,args =list(df = m1$df.residual),\n                xlim =c(-3.5,3.5))+\n  geom_vline(xintercept =t_stat[\"education_n\"], linetype = 3)+ #<<\n  geom_vline(xintercept =t_stat[\"education_n\"]*-1, linetype = 3)+ #<<\n  theme_bw()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides-old_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## 4. Calculate p-value\n\nTo quantify how often we would see test statistics as big or bigger, we can simply take the mean of a logical comparison of the absolute value of the test statistics under the null greater than the absolute value of our observed test statistic\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Simulation\nmean(abs(m1_null$education_n) > abs(t_stat[\"education_n\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.145\n```\n\n\n:::\n:::\n\n\n\nOr, we can calculate the area under the curve for a $t$-distribution, as with 1459 degrees of freedom, that is less than -1.45 and multiply this by 2 (because the distribution is symetric), to get the p-value\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Asymptotic\n2*pt(t_stat[\"education_n\"], m1$df.residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neducation_n \n  0.1446491 \n```\n\n\n:::\n:::\n\n\n\n## 4. Calculate p-value\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Asymptotic\n2*pt(t_stat[\"education_n\"], m1$df.residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\neducation_n \n  0.1446491 \n```\n\n\n:::\n:::\n\n\n\nOs exactly what R's `summary()` function returns:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# R's summary\nsummary(m1)$coef[4,]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Estimate   Std. Error      t value     Pr(>|t|) \n9.432048e-02 2.253583e-02 4.185356e+00 3.017253e-05 \n```\n\n\n:::\n:::\n\n\n\nVisually, these calculations look like this:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_null %>%\n  ggplot(aes(education_n))+\n  geom_density(col=\"grey\")+\n  geom_rug(col = ifelse(abs(m1_null$education_n) >= abs(t_stat[\"education_n\"]), \"red\",\"black\"))+ #<<\n  geom_vline(xintercept =0, linetype = 2)+\n  geom_vline(xintercept =t_stat[\"education_n\"], linetype = 3)+\n  geom_vline(xintercept =t_stat[\"education_n\"]*-1, linetype = 3)+\n  stat_function(fun =dt,args =list(df = m1$df.residual),\n                xlim =c(-3.5,3.5))+\n  stat_function(fun =dt,args =list(df = m1$df.residual), #<<\n                geom =\"area\", xlim = c(-3.5,t_stat[\"education_n\"]),#<<\n                alpha = .5,fill =\"red\")+#<<\n  stat_function(fun =dt, args =list(df = m1$df.residual), #<<\n                geom =\"area\", xlim = c(abs(t_stat[\"education_n\"]),3.5),#<<\n                alpha = .5, fill =\"red\")+#<<\n  theme_bw()\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides-old_files/figure-html/unnamed-chunk-39-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Reject or fail to reject/retain our hypothesis\n\nFor an estimated p-value of 0.145 for coefficient on `education_n` and a significance threshold of p \\< 0.05, we would...\n\n--\n\nFail to reject the null hypothesis that $H_0: \\beta_{education} = 0$\n\nBecause in a world where the truth was $\\beta_{education} = 0$ test statistics reflecting coefficients as far as $t-stat = |-1.459|$ about 14.5 percent of the time.\n\nIf we were to reject the null, 14.5 percent of the time, we would be making a Type-1 error \\| False Positive \\| concluding there was a relationship when in fact their wasn't.\n\nclass:inverse, middle, center \\# Break\n\nclass:inverse, middle, center \\# Final Projects\n\n## Timelines: This Week\n\n**NOTE: I'm leaving these slides in for nw**\n\n-   Feedback on Data today\n\n-   Questions/office hours today tomorrow/by appointment\n\n-   Thursday: Work on analyzing your data\n\n-   Drafts are still due April 24th.\n\n-   Your draft need not, and probably will not, be a completed project.\n\n-   At a minimum what you want is:\n\n    -   A clean data set\n    -   Exploratory descriptives\n    -   Initial results\n\n-   The rest can come later. Our goal on Thursday is to move you from the data portions of your projects, into the analysis.\n\n## Timelines: Next Week\n\n-   Tuesday, April 26: Workshop: Review and Presentations\n\n-   Thursday April 28: Workshop: Producing Presentations\n\n    -   7-10 Slides\n    -   Drafts/Analysis, just need to fill those slides\n\n-   Sunday, May 1: Presentations due (Monday at the latests)\n\n## Timelines: First Week of May:\n\n-   Tuesday, May 3: Presentations\n\n-   Thursday, May 5: Last class and Food?\n\n    -   Class at Dolores at 5pm?\n    -   Bagels/Treats in class\n\n-   Sunday May 8: Final Papers Due\n\n## Strucutre of Final Paper and Drafts:\n\nSeven sections:\n\n1.  Introduction (5 percent, \\~ 4 paragraphs)\n2.  Theory and Expectations (10 percent, \\~4+ paragraphs)\n3.  Data (20 percent \\~ 4+ paragraphs)\n4.  Design (25 percent \\~ 5+ paragraphs)\n5.  Results (25 percent \\~ 5+ paragraphs)\n6.  Conclusion (5 percent \\~ 3+ paragraphs)\n7.  Appendix (10 percent \\~ Variable codebook and all the R code for your project)\n\n## Focus on for Sunday\n\nSeven sections:\n\n1.  Introduction (5 percent, \\~ 4 paragraphs)\n2.  Theory and Expectations (10 percent, \\~4+ paragraphs)\n3.  **Data** (20 percent \\~ 4+ paragraphs)\n4.  *Design* (25 percent \\~ 5+ paragraphs)\n5.  **Results** (25 percent \\~ 5+ paragraphs)\n6.  Conclusion (5 percent \\~ 3+ paragraphs)\n7.  Appendix (10 percent \\~ Variable codebook and all the R code for your project)\n\n## Motivating Questions:\n\nIn the reset of today's class, we'll get some practice putting together the various skills you need for your drafts by exploring the following:\n\n-   How does partisanship shape American's perceptions of vaccines?\n\n-   Who is skeptical of the benefits of vaccination?\n\n-   Have these perceptions about vaccines changed over time?\n\n## Tasks:\n\nTo explore these questions, we need to\n\n-   Get setup to work\n\n-   Load our data\n\n-   Recode our data\n\n-   Summarize our data\n\n-   Specify our expectations\n\n-   Estimate models to test these expectations\n\n-   Present and interpret results using\n\n    -   Tables\n    -   Figures\n    -   Confidence intervals (review)\n    -   Hypothesis tests (new!)\n\nclass:inverse, middle, center \\# 💪 \\## Get set up to work\n\n## New packages\n\nTo easily load survey data for our question, we'll need the `anesr` package, which loads data from the American National Election Studies into R\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Uncomment to uninstall package to download NES survey data\n# library(devtools)\n# install_github(\"jamesmartherus/anesr\")\nrequire(anesr)\n```\n:::\n\n\n\n## Packages for today\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nthe_packages <- c(\n  ## R Markdown\n  \"kableExtra\",\"DT\",\"texreg\",\n  ## Tidyverse\n  \"tidyverse\", \"lubridate\", \"forcats\", \"haven\", \"labelled\",\"purrr\",\n  ## Extensions for ggplot\n  \"ggmap\",\"ggrepel\", \"ggridges\", \"ggthemes\", \"ggpubr\", \n  \"GGally\", \"scales\", \"dagitty\", \"ggdag\", \"ggforce\",\n  # Graphics:\n  \"scatterplot3d\", #<<\n  # Data \n  \"COVID19\",\"maps\",\"mapdata\",\"qss\",\"tidycensus\", \"dataverse\", \n  # Analysis\n  \"DeclareDesign\", \"modelr\", \"zoo\"\n)\n```\n:::\n\n\n\n## Define a function to load (and if needed install) packages\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nipak <- function(pkg){\n    new.pkg <- pkg[!(pkg %in% installed.packages()[, \"Package\"])]\n    if (length(new.pkg)) \n        install.packages(new.pkg, dependencies = TRUE)\n    sapply(pkg, require, character.only = TRUE)\n}\n```\n:::\n\n\n\n## Load packages for today\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nipak(the_packages)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   kableExtra            DT        texreg     tidyverse     lubridate \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      forcats         haven      labelled         purrr         ggmap \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      ggrepel      ggridges      ggthemes        ggpubr        GGally \n         TRUE          TRUE          TRUE          TRUE          TRUE \n       scales       dagitty         ggdag       ggforce scatterplot3d \n         TRUE          TRUE          TRUE          TRUE          TRUE \n      COVID19          maps       mapdata           qss    tidycensus \n         TRUE          TRUE          TRUE          TRUE          TRUE \n    dataverse DeclareDesign        modelr           zoo \n         TRUE          TRUE          TRUE          TRUE \n```\n\n\n:::\n:::\n\n\n\nclass:inverse, center, middle \\# 💪 \\## Loading Data\n\n## Data\n\nNow that we have `anesr` installed, let's load data from the 2016 and 2020 National Election Studies:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load data\ndata(timeseries_2016, package = \"anesr\")\ndata(timeseries_2020, package = \"anesr\")\n```\n:::\n\n\n\nAnd copy those data frames into new dataframes with shorter names\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Rename datasets\nnes16 <- timeseries_2016\nnes20 <- timeseries_2020\n```\n:::\n\n\n\nclass:inverse, center, middle \\# 💪 \\## Recoding Data\n\n## Finding variables of interest\n\nOur primary outcome of interest are beliefs about vaccines.\n\nVariables `V162162x` in the 2016 NES and `V202383x` in the 2020 NES will serve as our primary outcome of interest, summarizing respondents answer to the following question:\n\n> Do the health benefits of vaccinations generally outweigh the risks, do the risks outweigh the benefits, or is there no difference?\n\nSimilarly, `V161158x` in the 2016 NES and `V201231x` in the 2020 NES will serve our key predictor (respondent's partisanship).\n\nFinally, we'll control respondents' age, using `V161267` in the 2016 NES and `V201507x` in the 2020 NES\n\nLet's take a look at the values and distributions of these raw variables and think about what we need to do to recode these data so that they are suitable for analysis\n\n## Look at the distribution and coding of our outcome: Vaccine Beliefs\n\nThe variables in the NES datasets are of a class `labelled` which allows numeric values to have substantive labels\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nclass(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"haven_labelled\"\n```\n\n\n:::\n:::\n\n\n\nOur outcome variable has the following labels:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlabelled::val_labels(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                                   -9. Refused \n                                            -9 \n                                -8. Don't know \n                                            -8 \n-7. No post data, deleted due to incomplete IW \n                                            -7 \n                -6. No post-election interview \n                                            -6 \n                      1. Benefits much greater \n                                             1 \n                2. Benefits moderately greater \n                                             2 \n                  3. Benefits slightly greater \n                                             3 \n                              4. No difference \n                                             4 \n                     5. Risks slightly greater \n                                             5 \n                   6. Risks moderately greater \n                                             6 \n                         7. Risks much greater \n                                             7 \n```\n\n\n:::\n:::\n\n\n\nAnd distribution of responses:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(nes16$V162162x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  -9   -8   -7   -6    1    2    3    4    5    6    7 \n  21   28   86  536 1687  726  258  539   96  211   82 \n```\n\n\n:::\n:::\n\n\n\n## Recoding our outcome variable\n\nWhat transformations do we need to make to `V162162x` in `nes16` and `V202383x` in `nes20` so that these variables are suitable for analysis?\n\n--\n\n-   Recode negative values to be `NA`\n\n--\n\n-   Reverse code so that higher values indicate greater belief in the benefits of vaccines\n\n--\n\n-   Create an indicator of people who are skeptical of the benefits of vaccines\n\n## Recoding V162162x in 2016 NES\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnes16 %>%\n  mutate(\n    # Make Negative values NA, Reverse Code So Higher Values = Benefits > Risks\n    vaccine_benefits = ifelse(V162162x < 0, NA, (V162162x-8)*-1),\n    # Indicator of vaccine skepticism (Risks > Benefits)\n    vaccine_skeptic01 = case_when(\n      vaccine_benefits > 4 ~ 0,\n      vaccine_benefits <= 4 ~ 1,\n      TRUE ~ NA_real_\n    )\n  ) -> nes16 # Save recodes to nes16\n```\n:::\n\n\n\n## Recoding V202383x in 2020 NES\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnes20 %>%\n  mutate(\n    # Make Negative values NA, Reverse Code So Higher Values = Benefits > Risks\n    vaccine_benefits = ifelse(V202383x < 0, NA, (V202383x-8)*-1),\n    # Indicator of vaccine skepticism (Risks > Benefits)\n    vaccine_skeptic01 = case_when(\n      vaccine_benefits > 4 ~ 0,\n      vaccine_benefits <= 4 ~ 1,\n      TRUE ~ NA_real_\n    )\n  ) -> nes20 # Save recodes to nes20\n```\n:::\n\n\n\n## Recoding Predictors\n\nNow we repeat this process for our key predictor, partisanship.\n\n-   Recode the the summary partisanship variables `V161158x` in `nes16` and `V201231x` in `nes20`\n\n-   Create indicators from this recoded variable that classify partisanship as categorical variable (with Democrats as the reference category)\n\nAnd our covariate, age variables `V161267` in `nes16` and `V201507x` in `nes20`\n\n-   Recode negative values to be `NA`\n\n## Recoding Partisanship (V161158x) in 2016 NES\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnes16 %>%\n  mutate(\n    pid = ifelse(V161158x < 0, NA, V161158x),\n    pid3cat = case_when(\n      pid < 4 ~ \"Democrat\",\n      pid == 4 ~ \"Independent\",\n      pid > 4 ~ \"Republican\",\n      TRUE ~ \"Independent\"\n    ) %>% factor(., levels = c(\"Democrat\",\"Independent\",\"Republican\")),\n    age = ifelse(V161267 < 0, NA, V161267)\n  ) -> nes16\n```\n:::\n\n\n\n## Recoding Partisanship (V201231x) in 2020 NES\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnes20 %>%\n  mutate(\n    pid = ifelse(V201231x < 0, NA, V201231x),\n    pid3cat = case_when(\n      pid < 4 ~ \"Democrat\",\n      pid == 4 ~ \"Independent\",\n      pid > 4 ~ \"Republican\",\n      TRUE ~ \"Independent\"\n    ) %>% factor(., levels = c(\"Democrat\",\"Independent\",\"Republican\")),\n    age = ifelse(V201507x < 0, NA, V201507x)\n  ) -> nes20\n```\n:::\n\n\n\n## Progress Report\n\nTo explore these questions, we need to\n\n-   *Get setup to work* ✅\n\n-   *Load our data* ✅\n\n-   *Recode our data* ✅\n\n-   **Summarize our data**📥\n\n-   Specify our expectations\n\n-   Estimate models to test these expectations\n\n-   Presenting and interpreting results using\n\n    -   Tables\n    -   Figures\n    -   Confidence intervals (review)\n    -   Hypothesis tests (new!)\n\nclass:inverse, center, middle \\# 💪 \\## Summarizing data\n\n## Tables of descriptive statistics\n\n1.  Create a object with the names of the variables you want to summarize\n\n2.  Select these variables\n\n3.  Pivot the data\n\n4.  Calculate summary statistics\n\n5.  Format as an html table\n\n## Tables of descriptive statistics\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Create a object with the names of the variables you want to summarize\nthe_vars <- c(\"vaccine_skeptic01\",\"pid\",\"age\")\n# 2. Select these variables\nnes16 %>%\n  select(all_of(the_vars)) %>%\n# 3. Pivot the data\n  pivot_longer(\n    cols = all_of(the_vars),\n    names_to = \"Variable\"\n  )%>%\n  mutate(\n    Variable = factor(Variable, levels = the_vars)\n  )%>%\n  arrange(Variable)%>%\n  dplyr::group_by(Variable)%>%\n  # 3. Calculate summary statistics\n  dplyr::summarise(\n    min = min(value, na.rm=T),\n    p25 = quantile(value, na.rm=T, prob = 0.25),\n    Median = quantile(value, na.rm=T, prob = 0.5),\n    mean = mean(value, na.rm=T),\n    p75 = quantile(value, na.rm=T, prob = 0.25),\n    max = max(value, na.rm=T),\n    missing = sum(is.na(value))\n  ) -> sum_tab\n```\n:::\n\n\n\n## Format Table\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nknitr::kable(sum_tab,\n             caption = \"Descriptive Statistics\",\n             digits = 2) %>%\n  kableExtra::kable_styling() %>%\n  kableExtra::pack_rows(\"Outcome\", start_row = 1, end_row =1) %>%\n  kableExtra::pack_rows(\"Key Predictors\", start_row = 2, end_row =2) %>%\n  kableExtra::pack_rows(\"Covariates\", start_row = 3, end_row =3)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Descriptive Statistics</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> min </th>\n   <th style=\"text-align:right;\"> p25 </th>\n   <th style=\"text-align:right;\"> Median </th>\n   <th style=\"text-align:right;\"> mean </th>\n   <th style=\"text-align:right;\"> p75 </th>\n   <th style=\"text-align:right;\"> max </th>\n   <th style=\"text-align:right;\"> missing </th>\n  </tr>\n </thead>\n<tbody>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Outcome</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> vaccine_skeptic01 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 0.26 </td>\n   <td style=\"text-align:right;\"> 0 </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 671 </td>\n  </tr>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Key Predictors</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> pid </td>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:right;\"> 3.86 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n  </tr>\n  <tr grouplength=\"1\"><td colspan=\"8\" style=\"border-bottom: 1px solid;\"><strong>Covariates</strong></td></tr>\n<tr>\n   <td style=\"text-align:left;padding-left: 2em;\" indentlevel=\"1\"> age </td>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 50 </td>\n   <td style=\"text-align:right;\"> 49.58 </td>\n   <td style=\"text-align:right;\"> 34 </td>\n   <td style=\"text-align:right;\"> 90 </td>\n   <td style=\"text-align:right;\"> 121 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n## Progress Report\n\nTo explore these questions, we need to\n\n-   *Get setup to work* ✅\n\n-   *Load our data* ✅\n\n-   *Recode our data* ✅\n\n-   *Summarize our data* ✅\n\n-   **Specify our expectations** 📥\n\n-   Estimate models to test these expectations\n\n-   Presenting and interpreting results using\n\n    -   Tables\n    -   Figures\n    -   Confidence intervals (review)\n    -   Hypothesis tests (new!)\n\nclass:inverse, center, middle \\# 💪 \\## Specificying Expecations\n\n## Specificying Expecations\n\nConsider our first two motivating questions\n\n-   How does partisanship shape American's perceptions of vaccines?\n\n-   Who is skeptical of the benefits of vaccination?\n\nAnd some illustrative stereotypes:\n\n-   \"Republicans are *anti-science*\"\n-   \"Liberal always for Goopy *pseudo-science*\"\n-   \"Independents love to *do their own research*\"\n\nWhat are the empirical implications of these claims?\n\n## Specificying Expecations\n\nSimilarly, consider our third question:\n\n-   Have these perceptions about vaccines changed over time?\n\nAnd some similar simplified claims:\n\n-   \"The Covid-19 vaccine is a miracle of modern science\"\n-   \"Social media is rife with misinformation about the Covid-19 vaccine\"\n-   \"Politicians are politicizing vaccine politics for political benefits\"\n\nWhat are the empirical implications of these claims?\n\n## Specificying Expecations\n\nOur goal is to take claims/conventional wisdom/theories, and derive their empirical implications:\n\n-   **H1: Partisan Differences in Vaccine Skepticism**\n    -   **H1a:** Republicans will be the most skeptical of vaccines\n    -   **H1b:** Democrats will be the most skeptical of vaccines\n    -   **H1a:** Independents will be the most skeptical of vaccines\n-   **H2: Temporal Differences in Vaccine Skepticism**\n    -   **H2a:** Vaccine skepticism will decrease from 2016 to 2020 with the widespread roll out of the Covid-19 vaccine\n    -   **H2b:** Vaccine skepticism will increase from 2016 to 2020 with increased amounts of misinformation about the Covid-19 vaccine\n-   **H3: Partisan Difference in Vaccine Skepticism Over Time** Partisan differences in Vaccine Skepticism will increase from 2016 to 2020 with the politicization of Covid-19 policies\n\n## Motivating your expectations.\n\nIn your papers, unlike in these slides, your expectations should be grounded in existing theory, research, and evidence. For the present question, we might cite sources such as:\n\n-   Enders, Adam M., and Steven M. Smallpage. \"Informational cues, partisan-motivated reasoning, and the manipulation of conspiracy beliefs.\" Political Communication 36.1 (2019): 83-102.\n\n-   Stecula, Dominik A., and Mark Pickup. \"How populism and conservative media fuel conspiracy beliefs about COVID-19 and what it means for COVID-19 behaviors.\" Research & Politics 8.1 (2021): 2053168021993979.\n\n-   Jennings, Will, et al. \"Lack of trust, conspiracy beliefs, and social media use predict COVID-19 vaccine hesitancy.\" Vaccines 9.6 (2021): 593.\n\n-   Hollander, Barry A. \"Partisanship, individual differences, and news media exposure as predictors of conspiracy beliefs.\" Journalism & Mass Communication Quarterly 95.3 (2018): 691-713.\n\n## Model Specification\n\nTranslate these expectations into empirical models requires choices about **how to specify our models**\n\n--\n\n-   How should we measure/operationalize our outcome\n\n    -   Should we measure beliefs about vaccines with 7-point ordinal scale or as a binary indicator of vaccine skepticism\n\n-   How should we measure/operationalize our key predictor(s)\n\n    -   Should we measure partisanship using a 7 point scale or as categorical variable?\n\n-   What should we control for in our model?\n\n    -   Factors likely to predict both our outcome and our key predictor of interest\n\n--\n\n-   There are rarely definitive answers to these questions.\n\n-   In practice, we will often estimate **multiple models** to try and show that our findings are **robust** to alternative modeling strategies/specifications\n\n## Model Specification\n\nFor your projects, every group will almost surely estimate some form of the following:\n\n1.  Baseline bivariate model: The simplest test of the relationship between your outcome and key predictor\n\n2.  Multiple regression model: A test of the robustness of this relationship, controlling for alternative explanations\n\nIn practice, I suspect you may estimate multiple regression models such as:\n\n-   Alternative specifications/operationalizations of outcomes and predictors\n\n-   Interaction models to test conditional relationships\n\n-   Polynomial models to test non-linear relationships\n\n## Translating Theoretical Expectations into Empirical Models\n\nBefore we estimate our models in R, we will write down our models formally and empirical implications of our theoretical expectations in terms of the coefficients of our model.\n\nFor example, test for partisan differences in vaccine skepticism, we might fit the following baseline model:\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{7pt} + X\\beta + \\epsilon$$ - If $\\beta_1$ is positive this is consistent with **H1a** (greater skepticism among Republicans), - If $\\beta_2$ is negative this is consistent with **H1b** (greater skepticism among Democrats),\n\nBut how could we test **H1c** -- greater skepticism among Independents, who are \"4s\" on $\\text{PID}_{7pt}$?\n\n## Translating Theoretical Expectations into Empirical Models\n\nWe could fit a polynomial regression, including both partisanship and partinaship squared to allow the relationship between partisanship and vaccine skepticism to vary non-linearly\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{7pt} +  \\beta_2 \\text{PID}_{7pt}^2+ X\\beta+ \\epsilon$$ Or we could estimate a model treating Partisanship as a **categorical** variable rather than an **ordinal interval** variable. In our recoding, we set `\"Democrat\"` to be the first level of the variable `pid3cat`, so the model R will estimate by default is:\n\n$$\\text{Vaccine Skepticism} = \\beta_0 + \\beta_1 \\text{PID}_{Ind} +  \\beta_2 \\text{PID}_{Rep}+ X\\beta + \\epsilon$$\n\n## Testing differences over time.\n\nTesting Hypotheses 2 and 3 involve making comparisons across models estimated on data from different surveys.\n\nFormally, testing these expectations is a little more complicated\n\n-   we could pool our two surveys together include an interaction term for survey year\n\nFor our purposes, we'll treat these as more qualitative/exploratory hypotheses:\n\n-   H2a/b implies overall rates of vaccine skepticism will be lower/higher in 2020 compared to 2016\n\n-   H3 implies that whatever partisan differences we find in 2016 should be larger in 2020.\n\n## Progress Report\n\nTo explore these questions, we need to\n\n-   *Get setup to work* ✅\n\n-   *Load our data* ✅\n\n-   *Recode our data* ✅\n\n-   *Specify our expectations* ✅\n\n-   **Estimate models to test these expectations** 📥\n\n-   Presenting and interpreting results using\n\n    -   Tables\n    -   Figures\n    -   Confidence intervals (review)\n    -   Hypothesis tests (new!)\n\nclass:inverse, center, middle \\# 💪 \\## Estimating Empirical Models\n\n## Estimating Empirical Models\n\nHaving derived empirical implications of our theoretical expectations expressed in terms of linear regressions, now we simply have to estimate our models in R.\n\nWhen estimating the **same model** on **different datasets** we can write the formulas once\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf1 <- formula(vaccine_skeptic01 ~ pid + age)\nf2 <- formula(vaccine_skeptic01 ~ pid + I(pid^2) + age)\nf3 <- formula(vaccine_skeptic01 ~ pid3cat + age)\n```\n:::\n\n\n\n## Estimating Empirical Models\n\nAnd then pass it to `lm()` with different `data` arguments:\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1_2016 <- lm(formula = f1, data = nes16)\nm1_2020 <- lm(formula = f1, data = nes20)\nm2_2016 <- lm(formula = f2, data = nes16)\nm2_2020 <- lm(formula = f2, data = nes20)\nm3_2016 <- lm(formula = f3, data = nes16)\nm3_2020 <- lm(formula = f3, data = nes20)\n```\n:::\n\n\n\n## Estimating Empirical Models\n\nIf you've\n\n-   coded your data correctly\n\n-   developed clear testable implications from your theoretical expectations\n\nSpecifying and estimating empirical models is straightforward. Literally a few lines of code.\n\n## Progress Report\n\nTo explore these questions, we need to\n\n-   *Get setup to work* ✅\n\n-   *Load our data* ✅\n\n-   *Recode our data* ✅\n\n-   *Specify our expectations* ✅\n\n-   *Estimate models to test these expectations* ✅\n\n-   *Present our results* 📥\n\n    -   Tables\n    -   Figures\n    -   Confidence intervals (review)\n    -   Hypothesis testing (new!)\n\nclass:inverse, center, middle \\# 💪 \\## Presenting and Interpreting Your Results\n\n## Presenting and Interpreting Your Results\n\nPresenting and interpreting your results is requires both art and science.\n\nYour goal is to tell a story with your results, walking your reader through the substantive and statsitical interpretation of tables and figures.\n\nLet's start by producing a regression table, which provides a concise summary of multiple regression models.\n\nLike figures, producing a good regression table is an interactive process.\n\n## Regression Tables with htmlreg\n\nThe following code produces a basic regression table.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntexreg::htmlreg(\n  list(m1_2016,m2_2016,m3_2016,\n       m1_2020,m2_2020,m3_2020)\n)\n```\n:::\n\n\n\n## Regression Tables with htmlreg\n\n\n\n::: {.cell layout-align=\"center\"}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Statistical models</caption>\n<thead>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 2</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 3</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 4</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 5</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Model 6</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.46<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.35<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.42<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.34<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.32<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.35<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.04)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.06<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.01)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid^2</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.01<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.00</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.00)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid3catIndependent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.17<sup>&#42;&#42;&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.20<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">pid3catRepublican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.10<sup>&#42;&#42;&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.02)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.01)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.05</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.02</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.03</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.04</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;&#42;&#42;</sup>p &lt; 0.001; <sup>&#42;&#42;</sup>p &lt; 0.01; <sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n:::\n\n\n\n## Customizing our Regression Table\n\nLet's make this regression table more reader friendly and informative by:\n\n-   Giving the variables in substantive names\n\n-   Reporting coefficients to 3 decimal places\n\n-   Using a single significance threshold of $p < 0.05$\n\n-   Giving the models custom names\n\n-   Adding a header to group models by year\n\n-   Changing the caption of the table\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntexreg::htmlreg(\n  list(m1_2016,m2_2016,m3_2016,\n       m1_2020,m2_2020,m3_2020),\n  # Reporting coefficients to 3 decimal places\n  digits = 3,\n  # Using a single significance threshold \n  stars = 0.05,\n  # Giving the variables in substantive names\n  custom.coef.names = c(\n    \"(Intercept)\",\n    \"PID (7pt)\",\n    \"Age\",\n    \"PID<sup>2</sup> (7pt)\",\n    \"Independent\",\n    \"Republican\"\n  ),\n  # Giving the models custom names\n  custom.model.names = paste(\"Model\",c(1:3,1:3)),\n  # Adding a header to group models by year\n  custom.header = list(\"NES 2016\" = 1:3, \"NES 2020\" = 4:6),\n  # Changing the caption of the table\n  caption = \"Partisanship and Vaccine Skepticism\"\n)\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Partisanship and Vaccine Skepticism</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2016</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2020</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 2</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 3</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 4</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 5</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 6</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.458<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.350<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.417<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.343<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.318<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.352<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.025)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.035)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.018)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.024)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.064<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.021<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.037<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.003)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID<sup>2</sup> (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.009<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.002</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Independent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.175<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.200<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Republican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.100<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.023</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.028</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.022</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.027</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n:::\n\n\n\n## Telling a Story with Regression\n\nFirst, provide an overview the models presented in the table\n\n-   Explain what each model is doing conceptually\n\nThen, start with your simplest model (Typically the first column in your table).\n\n-   Use this as a chance to explain core concepts from the course\n    -   What is regression\n    -   How should I interpret a coefficient substantively\n    -   How should I interepret the statistical signficance of a give coefficient\n-   As you move from left to right (simple to more complex)\n    -   you need not interpret every single coefficient in the model\n    -   instead highlight the factors that are important for the reader to note (e.g. a comparison between one coefficient in model or another.)\n\n\n\n::: {.cell layout-align=\"center\"}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Partisanship and Vaccine Skepticism</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2016</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2020</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 2</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 3</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 4</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 5</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 6</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.458<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.350<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.417<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.343<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.318<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.352<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.025)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.035)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.018)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.024)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.064<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.021<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.037<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.003)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID<sup>2</sup> (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.009<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.002</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Independent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.175<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.200<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Republican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.100<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.023</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.028</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.022</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.027</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n:::\n\n\n\n## Overview\n\n-   Table 1 presents the results of three specifications exploring the relationship between partisanship and vaccine skepticism using data from the 2016 (Models 1-3) and 2020 (Models 4-5) National Election Studies.\n\n-   Models 1 and 4 operationalize partisanship as a 7-point scale, where 1 corresponds to Strong Democrats, 4 to Indepndents, and 7 to Strong Republicans in the 2016 (Model 1) and 2020 (Model 2) surveys.\n\n-   Models 2 and 5 allow the relationship between partisanship and vaccine skepticism to vary non-linear again for the 2016 (Model 2) and 2020 (Model 5) elections.\n\n-   Models 3 and 6 treat partisanship as categorical variable, describing how Independents and Republicans differ from Democrats, the reference category in these models.\n\n-   All models control age, since (put in substantive justification for controlling for age here)\n\n## Story: Testing for Partisan Differences\n\n-   The results from Model 1 provide little initial evidence for partisan differences in vaccine skepticism in the 2016 Election.\n\n    -   The coefficient on the partisanship variable is -0.005, suggesting that a unit increase in partisanship (going from being a Strong Democrat to just a Democrat, or an Independent to an independent who leans Republican), is associated with just a 0.5 percentage point increase in the probability of being a vaccine skeptic (believing that the risks of vaccination outweigh the benefits or that their is no difference in the risks versus benefits).\n\n-   Furthermore the 95-percent confidence interval for this estimate (-0.011, 0.002) brackets 0, suggesting the true population estimate from this model could be either positive or negative. Similarly, we fail to reject the null hypothesis that the true coefficient on partisanship in this model is 0 as the test statistic for this estimate ( -1.38) corresponds to a p-value of 0.168 suggesting that we would see test statistics this large or larger fairly often when the true relationship was 0.\n\n-   In some the results from Model 1 provide little support for any of the expectations described by *H1*\n\n## Testing for Partisan Differences: Model 2\n\n-   While coefficients from Model 1 suggest little evidence of partisan differences in vaccine skepticism, the coefficients on both partisanship, and partisanship squared are statistically significant (p \\< 0.05).\n\n## Interpreting Model 2\n\n-   The coefficients from polynomial regressions can be difficult to interpret jointly and so Figure 1 presents the predicted values from Model 2, holding age constant at its sample mean.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npred_df_m2 <- expand_grid(\n  pid = 1:7,\n  age = mean(nes16$age, na.rm=T)\n)\npred_df_m2 <- cbind(pred_df_m2, predict(m2_2016,pred_df_m2, interval =\"confidence\"))\npred_df_m2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  pid      age       fit       lwr       upr\n1   1 49.58231 0.2366157 0.2082979 0.2649335\n2   2 49.58231 0.2743408 0.2551659 0.2935157\n3   3 49.58231 0.2945841 0.2729532 0.3162151\n4   4 49.58231 0.2973457 0.2738012 0.3208902\n5   5 49.58231 0.2826255 0.2611041 0.3041469\n6   6 49.58231 0.2504236 0.2300546 0.2707925\n7   7 49.58231 0.2007398 0.1688900 0.2325897\n```\n\n\n:::\n:::\n\n\n\n## Interpreting Model 2\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npred_df_m2 %>%\n  ggplot(aes(pid, fit, ymin =lwr, ymax =upr))+\n  geom_line()+\n  geom_ribbon(alpha=.2, fill=\"grey\")+\n  theme_bw()+\n  labs(x = \"Partisanship\",\n       y = \"Predicted Vaccine Skepticism\",\n       title = \"Independents are the most skeptical of vaccines\",\n       subtitle = \"Data: 2016 NES\"\n       )\n```\n:::\n\n\n\n## Interpreting Model 2\n\n-   We see from Model 2 that 29.7 percent \\[27.3%, 32.1%\\] of Independents in the 2016 NES were predicted to be vaccine skeptics compared to 23.7 percent \\[20.8%, 26.5%\\] of Strong Democrats and only 20.1 percent \\[16.9%, 23.3%\\] of Strong Republicans.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](11-slides-old_files/figure-html/unnamed-chunk-65-1.png){fig-align='center' width=80%}\n:::\n:::\n\n\n\n## Testing for Partisan Differences: Model 3\n\nModel 3 tells a similar story to model 2. Again, adjusting for differences in vaccine skepticism explained by age, Model 3 predicts that 41.7 percent \\[37.7%, 45.6%\\] of Independents in the 2016 NES are vaccine skeptics compared to 24.2 percent \\[22.1%, 26.2%\\] of Democrats, and 22.6 percent \\[20.4%, 24.8%\\] of Republicans.\n\nNote the coefficients from Model 3 imply that the differences between Independents and Democrats are statistically significant ($\\beta_{Ind} = 0.175, p < 0.05$), the differences between Republicans and Democrats are not ($\\beta_{Rep} = -0.004, p = 0.31$)\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npred_df_m3 <- expand_grid(\n  pid3cat = c(\"Democrat\", \"Independent\",\"Republican\"),\n  age = mean(nes16$age, na.rm=T)\n)\npred_df_m3 <- cbind(pred_df_m3, predict(m3_2016,pred_df_m3, interval =\"confidence\"))\npred_df_m3\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      pid3cat      age       fit       lwr       upr\n1    Democrat 49.58231 0.2419547 0.2211228 0.2627867\n2 Independent 49.58231 0.4169043 0.3773539 0.4564547\n3  Republican 49.58231 0.2261496 0.2038046 0.2484947\n```\n\n\n:::\n:::\n\n\n\n## Testing for Differences Over Time\n\nThe results for the 2016 NES suggest political independents are most skeptical of vaccines.\n\nThe results for 2020 suggest the relationship between partisanship and vaccine skepticism has changed overtime.\n\n\n\n::: {.cell layout-align=\"center\"}\n<table class=\"texreg\" style=\"margin: 10px auto;border-collapse: collapse;border-spacing: 0px;caption-side: bottom;color: #000000;border-top: 2px solid #000000;\">\n<caption>Partisanship and Vaccine Skepticism</caption>\n<thead>\n<tr>\n<th>&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2016</th>\n<th style=\"padding-left: 5px;padding-right: 5px;border-bottom: 1px solid #000000;\" colspan=\"3\">NES 2020</th>\n</tr>\n<tr>\n<th style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 1</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 2</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 3</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 4</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 5</th>\n<th style=\"padding-left: 5px;padding-right: 5px;\">Mod 6</th>\n</tr>\n</thead>\n<tbody>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">(Intercept)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.458<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.350<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.417<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.343<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.318<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.352<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.025)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.035)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.018)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.024)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.005</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.064<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.021<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.037<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.003)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Age</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.004<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.003<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.000)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">PID<sup>2</sup> (7pt)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.009<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.002</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.002)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.001)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Independent</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.175<sup>&#42;</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.200<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.023)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Republican</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">-0.016</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.100<sup>&#42;</sup></td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.016)</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">&nbsp;</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">(0.011)</td>\n</tr>\n<tr style=\"border-top: 1px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.023</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.028</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr>\n<td style=\"padding-left: 5px;padding-right: 5px;\">Adj. R<sup>2</sup></td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.022</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.027</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.042</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.032</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">0.045</td>\n</tr>\n<tr style=\"border-bottom: 2px solid #000000;\">\n<td style=\"padding-left: 5px;padding-right: 5px;\">Num. obs.</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3494</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">3507</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7041</td>\n<td style=\"padding-left: 5px;padding-right: 5px;\">7052</td>\n</tr>\n</tbody>\n<tfoot>\n<tr>\n<td style=\"font-size: 0.8em;\" colspan=\"7\"><sup>&#42;</sup>p &lt; 0.05</td>\n</tr>\n</tfoot>\n</table>\n:::\n\n\n\n-   The coefficient on partisanship in model 4 is now positive and statistically significant (p \\< 0.05), suggesting that as respondents become more Republican, they are more likely to be skeptical of vaccines\n\n-   The coefficients from Model 5 suggest the relationship between partisanship skepticism is non linear, which is confirmed by model 6.\n\n-   In Model 6, we see that independents remain the most skeptical of vaccines in 2020 $(\\beta = 0.20,\\, p <0.05)$, but that Republicans now tend to be more skeptical of vaccines than Democrats $(\\beta = 0.10,\\, p <0.05)$\n",
    "supporting": [
      "11-slides-old_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint/kePrint.js\"></script>\n<link href=\"../site_libs/lightable/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}