<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Paul Testa">

<title>POLS 1600 - Week 05:</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/htmlwidgets/htmlwidgets.js"></script>
<link href="../site_libs/datatables-css/datatables-crosstalk.css" rel="stylesheet">
<script src="../site_libs/datatables-binding/datatables.js"></script>
<script src="../site_libs/jquery/jquery-3.6.0.min.js"></script>
<link href="../site_libs/dt-core/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="../site_libs/dt-core/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="../site_libs/dt-core/js/jquery.dataTables.min.js"></script>
<link href="../site_libs/crosstalk/css/crosstalk.min.css" rel="stylesheet">
<script src="../site_libs/crosstalk/js/crosstalk.min.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">POLS 1600</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../class/index.html"> 
<span class="menu-text">Class</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments/index.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="05-slides.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 05:</h1>
<p class="subtitle lead">Prediction with Linear Regression</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Paul Testa </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>Overview</h1>
<section id="general-plan" class="level2">
<h2 class="anchored" data-anchor-id="general-plan">General Plan</h2>
<ul>
<li>Group Assignment 1: Research Questions</li>
<li>Setup
<ul>
<li>Packages</li>
<li>Data</li>
</ul></li>
<li>Feedback</li>
<li>Review
<ul>
<li>Casual inference</li>
<li>Covariate Adjustment</li>
</ul></li>
<li>Linear Models
<ul>
<li>Conceptual</li>
<li>Practical</li>
<li>Technical</li>
<li>Theoretical</li>
</ul></li>
<li>Three Common Observational Designs
<ul>
<li>Difference in Difference</li>
<li>Regression Discontinuity</li>
<li>Instrumental Variable Designs</li>
</ul></li>
</ul>
<p>class: inverse, center, middle # Research Questions</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<ul>
<li><p>Template <a href="https://pols1600.paultesta.org/files/assignments/A1_research_questions.docx" target="_blank">here</a></p></li>
<li><p>Upload to <a href="https://canvas.brown.edu/courses/1087979/assignments/7870538?module_item_id=10762418" target="_blank">Canvas</a> this Sunday</p></li>
<li><p>3 Research questions:</p>
<ul>
<li><p>One-sentence research question</p></li>
<li><p>Why do we care</p></li>
<li><p>Ideal experiment</p></li>
<li><p>Observational study</p></li>
<li><p>Feasibility</p></li>
</ul></li>
</ul>
<p>class:inverse, middle, center # 💪 ## Get set up to work</p>
</section>
<section id="new-packages" class="level2">
<h2 class="anchored" data-anchor-id="new-packages">New packages</h2>
<p>Hopefully, you were all able to install the following packages</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"dataverse"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidycensus"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"easystats"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"DeclareDesign"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="census-api" class="level2">
<h2 class="anchored" data-anchor-id="census-api">Census API:</h2>
<p>Additionally, I hope you have all followed the steps <a href="https://pols1600.paultesta.org/slides/04-packages.html#3_Install_a_Census_API_tidycensus_package" target="_blank">here</a>:</p>
<ol type="1">
<li>Install the <code>tidycensus</code> package</li>
<li>Load the installed package</li>
<li>Request an API key from the Census</li>
<li>Check your email</li>
<li>Activate your key</li>
<li>Install your API key in R</li>
<li>Check that everything worked</li>
</ol>
<p>To install the an API key so we can download data directly from the US Census</p>
</section>
<section id="packages-for-today" class="level2">
<h2 class="anchored" data-anchor-id="packages-for-today">Packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>the_packages <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## R Markdown</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"kableExtra"</span>,<span class="st">"DT"</span>,<span class="st">"texreg"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Tidyverse</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"tidyverse"</span>, <span class="st">"lubridate"</span>, <span class="st">"forcats"</span>, <span class="st">"haven"</span>, <span class="st">"labelled"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Extensions for ggplot</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"ggmap"</span>,<span class="st">"ggrepel"</span>, <span class="st">"ggridges"</span>, <span class="st">"ggthemes"</span>, <span class="st">"ggpubr"</span>, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"GGally"</span>, <span class="st">"scales"</span>, <span class="st">"dagitty"</span>, <span class="st">"ggdag"</span>, <span class="st">"ggforce"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Data </span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"COVID19"</span>,<span class="st">"maps"</span>,<span class="st">"mapdata"</span>,<span class="st">"qss"</span>,<span class="st">"tidycensus"</span>, <span class="st">"dataverse"</span>, <span class="co">#&lt;&lt;</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Analysis</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"DeclareDesign"</span>, <span class="st">"easystats"</span>, <span class="st">"zoo"</span><span class="co">#&lt;&lt;</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="define-a-function-to-load-and-if-needed-install-packages" class="level2">
<h2 class="anchored" data-anchor-id="define-a-function-to-load-and-if-needed-install-packages">Define a function to load (and if needed install) packages</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>ipak <span class="ot">&lt;-</span> <span class="cf">function</span>(pkg){</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    new.pkg <span class="ot">&lt;-</span> pkg[<span class="sc">!</span>(pkg <span class="sc">%in%</span> <span class="fu">installed.packages</span>()[, <span class="st">"Package"</span>])]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(new.pkg)) </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">install.packages</span>(new.pkg, <span class="at">dependencies =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sapply</span>(pkg, require, <span class="at">character.only =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-packages-for-today" class="level2">
<h2 class="anchored" data-anchor-id="load-packages-for-today">Load packages for today</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ipak</span>(the_packages)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   kableExtra            DT        texreg     tidyverse     lubridate 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      forcats         haven      labelled         ggmap       ggrepel 
         TRUE          TRUE          TRUE          TRUE          TRUE 
     ggridges      ggthemes        ggpubr        GGally        scales 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      dagitty         ggdag       ggforce       COVID19          maps 
         TRUE          TRUE          TRUE          TRUE          TRUE 
      mapdata           qss    tidycensus     dataverse DeclareDesign 
         TRUE          TRUE          TRUE          TRUE          TRUE 
    easystats           zoo 
         TRUE          TRUE </code></pre>
</div>
</div>
<p>class:inverse, center, middle # 💪 ## Load Data for today</p>
</section>
<section id="load-the-covid-19-data" class="level2">
<h2 class="anchored" data-anchor-id="load-the-covid-19-data">Load the Covid-19 Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># covid &lt;- COVID19::covid19(</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   country = "US",</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   level = 2,</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   verbose = F</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># )</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://pols1600.paultesta.org/files/data/covid.rda"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="filter-covid-19-data-to-us-states" class="level2">
<h2 class="anchored" data-anchor-id="filter-covid-19-data-to-us-states">Filter Covid-19 Data to US States</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vector containing of US territories</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>territories <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"American Samoa"</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Guam"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Northern Mariana Islands"</span>,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Puerto Rico"</span>,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Virgin Islands"</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter out Territories and create state variable</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>covid_us <span class="ot">&lt;-</span> covid <span class="sc">%&gt;%</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>administrative_area_level_2 <span class="sc">%in%</span> territories)<span class="sc">%&gt;%</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> administrative_area_level_2</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mutate-calculate-new-cases" class="level2">
<h2 class="anchored" data-anchor-id="mutate-calculate-new-cases">Mutate: Calculate New Cases</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">new_cases =</span> confirmed <span class="sc">-</span> <span class="fu">lag</span>(confirmed),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">new_cases_pc =</span> new_cases <span class="sc">/</span> population <span class="sc">*</span><span class="dv">100000</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">new_cases_pc_7da =</span> zoo<span class="sc">::</span><span class="fu">rollmean</span>(new_cases_pc, </span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">k =</span> <span class="dv">7</span>, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">align =</span> <span class="st">"right"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">fill=</span><span class="cn">NA</span> )</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    ) <span class="ot">-&gt;</span> covid_us</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="calculating-a-rolling-average-new-cases" class="level2">
<h2 class="anchored" data-anchor-id="calculating-a-rolling-average-new-cases">Calculating a Rolling Average New Cases</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(date <span class="sc">&gt;</span> <span class="st">"2020-03-05"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date,new_cases_pc,new_cases_pc_7da)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 52,580 × 4
# Groups:   state [51]
   state     date       new_cases_pc new_cases_pc_7da
   &lt;chr&gt;     &lt;date&gt;            &lt;dbl&gt;            &lt;dbl&gt;
 1 Minnesota 2020-03-06      NA               NA     
 2 Minnesota 2020-03-07       0               NA     
 3 Minnesota 2020-03-08       0.0177          NA     
 4 Minnesota 2020-03-09       0               NA     
 5 Minnesota 2020-03-10       0.0177          NA     
 6 Minnesota 2020-03-11       0.0355          NA     
 7 Minnesota 2020-03-12       0.0709          NA     
 8 Minnesota 2020-03-13       0.0887           0.0329
 9 Minnesota 2020-03-14       0.124            0.0507
10 Minnesota 2020-03-15       0.248            0.0836
# ℹ 52,570 more rows</code></pre>
</div>
</div>
</section>
<section id="new-case-per-capita" class="level2">
<h2 class="anchored" data-anchor-id="new-case-per-capita">New Case Per Capita</h2>
<p>.pull-left[</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(date <span class="sc">&gt;</span> <span class="st">"2020-03-05"</span>, </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>         state <span class="sc">==</span> <span class="st">"Minnesota"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>         new_cases_pc,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>         new_cases_pc_7da)<span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(date,new_cases_pc ))<span class="sc">+</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">col=</span><span class="st">"Daily"</span>))<span class="sc">+</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">"bottom"</span>)<span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>( <span class="at">col =</span> <span class="st">"Measure"</span>,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"New Cases Per 100k"</span>, <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Minnesota"</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> fig_covid_mn </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>]</p>
<p>.pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/plotmean2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>]</p>
</section>
<section id="new-case-per-capita-vs-7-day-average" class="level2">
<h2 class="anchored" data-anchor-id="new-case-per-capita-vs-7-day-average">New Case Per Capita vs 7-day average</h2>
<p>.pull-left[</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>fig_covid_mn <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> new_cases_pc_7da,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">col =</span> <span class="st">"7-day average"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>            ) <span class="ot">-&gt;</span> fig_covid_mn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>]</p>
<p>.pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/plotmean7d2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>]</p>
</section>
<section id="facemask-policy" class="level2">
<h2 class="anchored" data-anchor-id="facemask-policy">Facemask Policy</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Recode facial_coverings to create face_masks</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">face_masks =</span> <span class="fu">case_when</span>(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>      facial_coverings <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"No policy"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">abs</span>(facial_coverings) <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"Recommended"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">abs</span>(facial_coverings) <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="st">"Some requirements"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">abs</span>(facial_coverings) <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="st">"Required shared places"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">abs</span>(facial_coverings) <span class="sc">==</span> <span class="dv">4</span> <span class="sc">~</span> <span class="st">"Required all times"</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Turn face_masks into a factor with ordered policy levels</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">face_masks =</span> <span class="fu">factor</span>(face_masks,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"No policy"</span>,<span class="st">"Recommended"</span>,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Some requirements"</span>,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Required shared places"</span>,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Required all times"</span>)</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    ) <span class="ot">-&gt;</span> covid_us</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="mutate-dates-and-vaccinations" class="level2">
<h2 class="anchored" data-anchor-id="mutate-dates-and-vaccinations">Mutate: Dates and Vaccinations</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="fu">year</span>(date),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">month =</span> <span class="fu">month</span>(date),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">year_month =</span> <span class="fu">paste</span>(year, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                       <span class="fu">str_pad</span>(month, <span class="at">width =</span> <span class="dv">2</span>, <span class="at">pad=</span><span class="dv">0</span>), </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                       <span class="at">sep =</span> <span class="st">"-"</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">percent_vaccinated =</span> people_fully_vaccinated<span class="sc">/</span>population<span class="sc">*</span><span class="dv">100</span>  </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    ) <span class="ot">-&gt;</span> covid_us</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data-on-presidential-elections" class="level2">
<h2 class="anchored" data-anchor-id="load-data-on-presidential-elections">Load Data on Presidential Elections</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Try this code first</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Sys.setenv</span>(<span class="st">"DATAVERSE_SERVER"</span> <span class="ot">=</span> <span class="st">"dataverse.harvard.edu"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>pres_df <span class="ot">&lt;-</span> <span class="fu">get_dataframe_by_name</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"1976-2020-president.tab"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"doi:10.7910/DVN/42MVDX"</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># If the code above fails, comment out and uncomment the code below:</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># load(url("https://pols1600.paultesta.org/files/data/pres_df.rda"))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hlo-of-presidential-elections-data" class="level2">
<h2 class="anchored" data-anchor-id="hlo-of-presidential-elections-data">HLO of Presidential Elections Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pres_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 15
   year state   state_po state_fips state_cen state_ic office       candidate   
  &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;       
1  1976 ALABAMA AL                1        63       41 US PRESIDENT "CARTER, JI…
2  1976 ALABAMA AL                1        63       41 US PRESIDENT "FORD, GERA…
3  1976 ALABAMA AL                1        63       41 US PRESIDENT "MADDOX, LE…
4  1976 ALABAMA AL                1        63       41 US PRESIDENT "BUBAR, BEN…
5  1976 ALABAMA AL                1        63       41 US PRESIDENT "HALL, GUS" 
6  1976 ALABAMA AL                1        63       41 US PRESIDENT "MACBRIDE, …
# ℹ 7 more variables: party_detailed &lt;chr&gt;, writein &lt;lgl&gt;,
#   candidatevotes &lt;dbl&gt;, totalvotes &lt;dbl&gt;, version &lt;dbl&gt;, notes &lt;lgl&gt;,
#   party_simplified &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="transform-data-to-get-just-2020-election" class="level2">
<h2 class="anchored" data-anchor-id="transform-data-to-get-just-2020-election">Transform Data to get just 2020 Election</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>pres_df <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">year_election =</span> year,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">str_to_title</span>(state),</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Fix DC</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="fu">ifelse</span>(state <span class="sc">==</span> <span class="st">"District Of Columbia"</span>, <span class="st">"District of Columbia"</span>, state)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(party_simplified <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"DEMOCRAT"</span>,<span class="st">"REPUBLICAN"</span>))<span class="sc">%&gt;%</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2020</span>) <span class="sc">%&gt;%</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, state_po, year_election, party_simplified, candidatevotes, totalvotes</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> party_simplified,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> candidatevotes) <span class="sc">%&gt;%</span></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">dem_voteshare =</span> DEMOCRAT<span class="sc">/</span>totalvotes <span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">rep_voteshare =</span> REPUBLICAN<span class="sc">/</span>totalvotes<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">winner =</span> forcats<span class="sc">::</span><span class="fu">fct_rev</span>(<span class="fu">factor</span>(<span class="fu">ifelse</span>(rep_voteshare <span class="sc">&gt;</span> dem_voteshare,<span class="st">"Trump"</span>,<span class="st">"Biden"</span>)))</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="ot">-&gt;</span> pres2020_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="transform-data-to-get-just-2020-election-1" class="level2">
<h2 class="anchored" data-anchor-id="transform-data-to-get-just-2020-election-1">Transform Data to get just 2020 Election</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pres2020_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  state      state_po year_election totalvotes DEMOCRAT REPUBLICAN dem_voteshare
  &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 Alabama    AL                2020    2323282   849624    1441170          36.6
2 Alaska     AK                2020     359530   153778     189951          42.8
3 Arizona    AZ                2020    3387326  1672143    1661686          49.4
4 Arkansas   AR                2020    1219069   423932     760647          34.8
5 California CA                2020   17500881 11110250    6006429          63.5
6 Colorado   CO                2020    3279980  1804352    1364607          55.0
# ℹ 2 more variables: rep_voteshare &lt;dbl&gt;, winner &lt;fct&gt;</code></pre>
</div>
</div>
</section>
<section id="load-data-on-median-state-income-from-the-census" class="level2">
<h2 class="anchored" data-anchor-id="load-data-on-median-state-income-from-the-census">Load Data on Median State Income from the Census</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>acs_df <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(<span class="at">geography =</span> <span class="st">"state"</span>, </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">variables =</span> <span class="fu">c</span>(<span class="at">med_income =</span> <span class="st">"B19013_001"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">med_age =</span> <span class="st">"B01002_001"</span>), </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">year =</span> <span class="dv">2019</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="hlo-census-data" class="level2">
<h2 class="anchored" data-anchor-id="hlo-census-data">HLO: Census Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(acs_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  GEOID NAME    variable   estimate    moe
  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;         &lt;dbl&gt;  &lt;dbl&gt;
1 01    Alabama med_age        39      0.2
2 01    Alabama med_income  50536    304  
3 02    Alaska  med_age        34.3    0.1
4 02    Alaska  med_income  77640   1015  
5 04    Arizona med_age        37.7    0.2
6 04    Arizona med_income  58945    266  </code></pre>
</div>
</div>
</section>
<section id="tidy-census-data" class="level2">
<h2 class="anchored" data-anchor-id="tidy-census-data">Tidy Census Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>acs_df <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> NAME,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, variable, estimate) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> variable,</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> estimate) <span class="ot">-&gt;</span> acs_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="tidy-census-data-1" class="level2">
<h2 class="anchored" data-anchor-id="tidy-census-data-1">Tidy Census Data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(acs_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  state      med_age med_income
  &lt;chr&gt;        &lt;dbl&gt;      &lt;dbl&gt;
1 Alabama       39        50536
2 Alaska        34.3      77640
3 Arizona       37.7      58945
4 Arkansas      38.1      47597
5 California    36.5      75235
6 Colorado      36.7      72331</code></pre>
</div>
</div>
</section>
<section id="merge-election-data-and-covid-data-into-single-df" class="level2">
<h2 class="anchored" data-anchor-id="merge-election-data-and-covid-data-into-single-df">Merge election data and covid data into single <code>df</code></h2>
<p>.pull-left[ - We’re going to take our <code>covid_us</code> data and <strong>merge</strong> into this data on the 2020 election from <code>pres2020_df</code> using the common <code>state</code> variable in each data set for a <code>left_join()</code></p>
<ul>
<li><p>Always check the matches in your joining variable (i.e.&nbsp;<code>state</code>)</p></li>
<li><p>Below we see that our recoding of state to title case in created a mismatch</p></li>
</ul>
<p>]</p>
<p>.pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Should be 51</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(pres2020_df<span class="sc">$</span>state <span class="sc">%in%</span> covid_us<span class="sc">$</span>state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the mismatch:</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>pres2020_df<span class="sc">$</span>state[<span class="sc">!</span>pres2020_df<span class="sc">$</span>state <span class="sc">%in%</span> covid_us<span class="sc">$</span>state]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>character(0)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fix</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>pres2020_df<span class="sc">$</span>state[pres2020_df<span class="sc">$</span>state <span class="sc">==</span> <span class="st">"District Of Columbia"</span>] <span class="ot">&lt;-</span> <span class="st">"District of Columbia"</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Problem Solved</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(pres2020_df<span class="sc">$</span>state <span class="sc">%in%</span> covid_us<span class="sc">$</span>state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51</code></pre>
</div>
</div>
<p>]</p>
</section>
<section id="merge-election-data-into-covid-data" class="level2">
<h2 class="anchored" data-anchor-id="merge-election-data-into-covid-data">Merge election data into Covid data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(covid_us)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53678    56</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(pres2020_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51  9</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="ot">&lt;-</span> covid_us <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  pres2020_df,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"state"</span> <span class="ot">=</span> <span class="st">"state"</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(covid_us) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53678    64</code></pre>
</div>
</div>
</section>
<section id="merge-census-data-into-covid-data" class="level2">
<h2 class="anchored" data-anchor-id="merge-census-data-into-covid-data">Merge Census data into Covid data</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(covid_us)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53678    64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(acs_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52  3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>covid_us <span class="ot">&lt;-</span> covid_us <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  acs_df,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"state"</span> <span class="ot">=</span> <span class="st">"state"</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(covid_us)  <span class="co"># Same number of rows as covid_us w/ 2 additional columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53678    66</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./images/05_covid.png" class="quarto-figure quarto-figure-center figure-img" style="width:80.0%;height:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://www.nytimes.com/2022/02/18/briefing/red-covid-partisan-deaths-vaccines.html" target="_blank">Red Covid, an Update</a> <em>New York Times</em>, 18 February, 2022</p>
</section>
<section id="preview-of-the-lab" class="level2">
<h2 class="anchored" data-anchor-id="preview-of-the-lab">Preview of the Lab</h2>
<p>Conceptually, this lab is designed to help reinforce the relationship between linear models like <span class="math inline">\(y=\beta_0 + \beta_1x\)</span> and the conditional expectation function <span class="math inline">\(E[Y|X]\)</span>.</p>
<ul>
<li><p>Questions 1-5 are designed to reinforce your <strong>data wrangling</strong> skills. In particular, you will get practice:</p>
<ul>
<li>Creating and recoding variables using <code>mutate()</code></li>
<li>Calculating a <a href="https://en.wikipedia.org/wiki/Moving_average" target="_blank">moving average</a> or rolling mean using the <code>rollmean()</code> function from the <code>zoo</code> package</li>
<li>Transforming the data on presidential elections so that it can be merged with the data on Covid-19 using the <code>pivot_wider()</code> function.</li>
<li><a href="https://r4ds.had.co.nz/relational-data.html" target="_blank">Merging data</a> together using the <code>left_join()</code> function.</li>
</ul></li>
<li><p>In question 6, you will see how calculating conditional means provides a simple test of “Red Covid” claim.</p></li>
<li><p>In question 7, you will see how a linear model returns the same information as these conditional means (in a sligthly different format)</p></li>
<li><p>In question 8, you will get practice interpreting linear models with continuous predictors (i.e.&nbsp;predictors that take on a range of values)</p></li>
<li><p>In question 9, you will get practice visualizing these models and using the figures help interpret your results substantively.</p></li>
<li><p>Question 10 asks you to play the role of a skeptic and consider what other factors might explain the relationships we found in Questions 6-9. We will explore these factors in next week’s lab.</p></li>
</ul>
<p>class: inverse, center, middle background-image: url(“https://i.pinimg.com/originals/a2/05/b6/a205b689caf19f3287b1544cbe0e6b7b.jpg”) background-size: contain # 📢 ## Feedback</p>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 29
   StartDate           EndDate             Status         IPAddress     Progress
   &lt;dttm&gt;              &lt;dttm&gt;              &lt;dbl+lbl&gt;      &lt;chr&gt;            &lt;dbl&gt;
 1 2023-02-23 13:47:36 2023-02-23 13:49:09 0 [IP Address] 128.148.206.…      100
 2 2023-02-23 13:47:34 2023-02-23 13:49:13 0 [IP Address] 128.148.207.…      100
 3 2023-02-23 13:47:30 2023-02-23 13:49:17 0 [IP Address] 128.148.204.…      100
 4 2023-02-23 13:47:32 2023-02-23 13:49:26 0 [IP Address] 128.148.204.…      100
 5 2023-02-23 13:47:50 2023-02-23 13:49:35 0 [IP Address] 128.148.205.…      100
 6 2023-02-23 13:47:17 2023-02-23 13:49:38 0 [IP Address] 192.91.235.1…      100
 7 2023-02-23 13:48:03 2023-02-23 13:49:42 0 [IP Address] 128.148.205.…      100
 8 2023-02-23 13:47:14 2023-02-23 13:49:48 0 [IP Address] 128.148.206.…      100
 9 2023-02-23 13:47:33 2023-02-23 13:49:54 0 [IP Address] 128.148.207.…      100
10 2023-02-23 13:47:49 2023-02-23 13:49:54 0 [IP Address] 128.148.207.…      100
# ℹ 11 more rows
# ℹ 24 more variables: Duration__in_seconds_ &lt;dbl&gt;, Finished &lt;dbl+lbl&gt;,
#   RecordedDate &lt;dttm&gt;, ResponseId &lt;chr&gt;, RecipientLastName &lt;chr&gt;,
#   RecipientFirstName &lt;chr&gt;, RecipientEmail &lt;chr&gt;, ExternalReference &lt;chr&gt;,
#   LocationLatitude &lt;chr&gt;, LocationLongitude &lt;chr&gt;, DistributionChannel &lt;chr&gt;,
#   UserLanguage &lt;chr&gt;, Likes &lt;chr&gt;, Dislikes &lt;chr&gt;, code_skills &lt;chr&gt;,
#   code_challenge &lt;chr&gt;, eval_1 &lt;dbl&gt;, eval_2 &lt;dbl&gt;, eval_3 &lt;dbl&gt;, …</code></pre>
</div>
</div>
</section>
<section id="what-we-liked-and-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-we-liked-and-learned">What we liked and learned</h2>
<p>–</p>
<ul>
<li>Causal Inference!</li>
<li>Data Viz</li>
<li>Programming</li>
<li>Review</li>
<li>Dank Memes</li>
</ul>
</section>
<section id="what-we-liked" class="level2">
<h2 class="anchored" data-anchor-id="what-we-liked">What we liked</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="htmlwidget-b5a840e22738d802b72d" style="width:100%;height:90%;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-b5a840e22738d802b72d">{"x":{"filter":"none","vertical":false,"fillContainer":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21"],["","Getting to work/meet lab partners I have not communicated with yet in this class!","I found our lab quite interesting last week. It was quite rewarding to be able to analyze the data and apply the skills we already learnt","","The Clueless meme\n","The comparisons and examples with real-life studies (like the sophomore problem).","I appreciated the content of today's lecture\n","I found interesting the different ways to interept data and how useful that information is when coding.","lab breakdown of working with our groups but still coming back to working as one large group to make sure we're all on the same page","I've been enjoying the tutorials a lot!","I enjoyed the lab! I appreciated having the comments guide me along the way whenever I needed it. It is especially useful now.","I liked working in groups! It was very interesting to see the way other people work and the troubleshoot with each other. I am looking forward to continuing to work with and learn from my peers.","The mapping concepts to code made the entire process seem a bit more straightforward.","I liked having the time to work with my lab group to just play around with the code.","This is silly but copy and paste is fun lol","We didn't get to it in lab, but did my own experimenting to plot the results of the study. Felt very fulfilling.","I liked the causal questions lecture, especially the section where we got to brainstorm a question with our peers. I think showing us how to understand what's going on in chunks of code was useful. Copy pasting large chunks of code still feels confusing but I think we're getting the skills to get the general picture.","I enjoyed working on replicating published figures from data sets. I think having an end goal/figure helped in understanding the steps we were taking and how to get there.","I liked the lab. I think that having to work through it is the most useful for learning and getting better at coding.\n","I liked during the lab last week when I understood what I was doing and was able to correct my code independently- that felt good.\nI found that taking my time on the tutorials and following in my textbook was useful.","I have enjoyed going over many of the terms that I have heard used when discussing social science research in my previous courses. I also enjoyed going through the different lines of code so we can get a better understanding of what each function and operation is actually doing."]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Likes<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":3,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Likes","targets":1}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[3,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="what-weve-learned" class="level2">
<h2 class="anchored" data-anchor-id="what-weve-learned">What we’ve learned</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> [1] ""                                                                                                               
 [2] "Separate my code effectively into useful code chunks!\n"                                                        
 [3] "I'm not entirely sure"                                                                                          
 [4] "putting data$ something in the tutorials"                                                                       
 [5] "the basics I have down pretty well, setting up loading and the basic adjustments"                               
 [6] "I think I am learning pretty well to discern commands and explain what each line does."                         
 [7] "organizing my code into chunks that make sense for me\n"                                                        
 [8] "Creating different code chunks and labelling them."                                                             
 [9] "setting up workspace and staying organized while coding"                                                        
[10] "It's really satisfying making graphs!"                                                                          
[11] "Loading them packages."                                                                                         
[12] "follow instructions"                                                                                            
[13] "I feel like I am good at understanding what things do"                                                          
[14] "Set up data/loading libraries, simple filtering of data and making graphs"                                      
[15] "Making things organized"                                                                                        
[16] "Simple arithmetic functions, basic plotting"                                                                    
[17] "Make chunks, load packages, paste things"                                                                       
[18] "using summary on data tables"                                                                                   
[19] "I think I've gotten comfortable with getting the workspace set up and looking over and cleaning data."          
[20] "I am good at FAAFing O"                                                                                         
[21] "I feel confident using the commands to look at the data! But not quite yet confident on how to mutate the data."
attr(,"label")
[1] "What's one thing you do really well in R?"
attr(,"format.spss")
[1] "A2000"
attr(,"display_width")
[1] 15</code></pre>
</div>
<div class="cell-output-display">
<div id="htmlwidget-494fcca211bfa60ce667" style="width:100%;height:90%;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-494fcca211bfa60ce667">{"x":{"filter":"none","vertical":false,"fillContainer":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21"],["","Separate my code effectively into useful code chunks!\n","I'm not entirely sure","putting data$ something in the tutorials","the basics I have down pretty well, setting up loading and the basic adjustments","I think I am learning pretty well to discern commands and explain what each line does.","organizing my code into chunks that make sense for me\n","Creating different code chunks and labelling them.","setting up workspace and staying organized while coding","It's really satisfying making graphs!","Loading them packages.","follow instructions","I feel like I am good at understanding what things do","Set up data/loading libraries, simple filtering of data and making graphs","Making things organized","Simple arithmetic functions, basic plotting","Make chunks, load packages, paste things","using summary on data tables","I think I've gotten comfortable with getting the workspace set up and looking over and cleaning data.","I am good at FAAFing O","I feel confident using the commands to look at the data! But not quite yet confident on how to mutate the data."]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>code_skills<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":4,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"code_skills","targets":1}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[4,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="what-we-disliked-or-struggled-with" class="level2">
<h2 class="anchored" data-anchor-id="what-we-disliked-or-struggled-with">What we disliked or struggled with</h2>
<ul>
<li>Stats
<ul>
<li>DAGs</li>
<li>Regression</li>
</ul></li>
<li>Pacing</li>
<li>Keeping track of various concepts and skills</li>
<li>Lack of breaks</li>
<li>Too much review</li>
</ul>
</section>
<section id="what-we-disliked" class="level2">
<h2 class="anchored" data-anchor-id="what-we-disliked">What we disliked</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="htmlwidget-b96047b10f7b5ce9b27d" style="width:100%;height:90%;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-b96047b10f7b5ce9b27d">{"x":{"filter":"none","vertical":false,"fillContainer":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21"],["","My computer malfunctioning during lab lol","The concepts can be quite hard. The tutorials are important, but sometime it requires a lot of depth","","Needed slightly more time in group work for the lab","","n/a\n","I am still confused about counterfacturals. I also am unsure how all the math equations are relevant, like what/how are we suppose to think about them.","the tutorials are not my favorite, I don't find them super helpful (yet at least) and they're tedious \n","Maybe before labs, we could go over the experiment we are working on a bit more in-depth? I got a bit lost during the lab not because of the coding, but because I wasn't sure what information I was trying to find and how that fit into the experiment we were looking at","There are a lot of concepts and mathematical jargon that can kinda get confusing and clunky and makes me get lost at times.","Although I liked working in groups, I found the lab difficult and was thankful for help from my peers and Prof Testa.","The concepts are a bit technical, and my code has been difficult to load recently because of oftentimes granular and difficult-to-spot errors.","","It is hard to keep up with the group when we are using one person's computer and just doing a few things on our own to see if we are following (basically the speed of info recall)","","The pace is still a bit fast.","I think my brain turns off for some of the more theoretical interpretations of descriptive statistics, but that's not really the focus of the class.","I find the amount of slides confusing because if I need to go back to the slides to remember something it is difficult to find what I am looking for because there are so many and we don't usually go over all of them.","I had trouble understanding the mathematical notations that were used last week (really just in reference to the slides and explanations). But it is just frustrating when I semi-grasp the subject and can see the potential","I still feel confused working with R. I don't feel like I have a strong enough understanding of the language to be able to do labs independently/in a group setting."]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Dislikes<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":4,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Dislikes","targets":1}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[4,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
</section>
<section id="what-weve-struggled-with" class="level2">
<h2 class="anchored" data-anchor-id="what-weve-struggled-with">What we’ve struggled with</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="htmlwidget-f9233d388f0e17076163" style="width:100%;height:90%;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-f9233d388f0e17076163">{"x":{"filter":"none","vertical":false,"fillContainer":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21"],["transforming data","Understanding how to read / comprehend code more effectively!\n","How to design a graph, and choose the type of graph","I wish I had a better understanding of what types of functions I should use when I want to do something","Wish I understood the long chunks more deeply","More time to digest the topics and methods.","Learning how to write out multiple lines of code at once","I just wish I understood the functions more. I feel like there is always so many functions to keep track up that it gets confusing. I would like a list or something that could maybe explain them better.","I just don't think i understand a lot of the functions super well yet in terms of how to write them myself. like I understand broadly what they're doing, but not how to format them to get them to do those things","Data wrangling is still confusing to me","In the course, I wish to understand the theories and mathematical concepts better with practice or examples.","I often have a hard time locating my mistakes when I have errors.","I struggle to properly set up R and understand the language from scratch.","I would like to understand visually how the columns transform so I can see what the code does.","How we are going to do our own research and find credible data","the less intuitive function names","Mutate function, ggplot","pivot_wider and pivot_longer often confuse me in how to best transpose data.","Knowing how to make graphs has been a bit confusing because we use ggplot in class and something different in the tutorials.","The individual panels and their functions/relations to one another","The syntax behind mutating data, as well as the math behind descriptive statistics."]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>code_challenge<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":4,"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"code_challenge","targets":1}],"order":[],"autoWidth":false,"orderClasses":false,"lengthMenu":[4,10,25,50,100]}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code> [1]  0 NA NA NA NA NA  0 NA  0 NA  0 NA NA NA NA NA NA  9 NA NA 10
attr(,"label")
[1] "How do you think we're doing? Please provide a rough assessment of the performance of: - President Donald Trump"
attr(,"format.spss")
[1] "F40.2"
attr(,"display_width")
[1] 5</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/unnamed-chunk-36-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>class:inverse, middle, center # 🔍 ## Review</p>
</section>
<section id="review" class="level2">
<h2 class="anchored" data-anchor-id="review">Review</h2>
<ul>
<li><p>Casual Inference</p></li>
<li><p>Covariate Adjustment</p></li>
</ul>
<p>class:inverse, middle, center # 🔍 ## Causal Inference</p>
</section>
<section id="review-causal-inference" class="level2">
<h2 class="anchored" data-anchor-id="review-causal-inference">Review: Causal Inference</h2>
<ul>
<li>Causal inference is about counterfactual comparisons</li>
</ul>
<p>–</p>
<ul>
<li>Some counterfactuals are easier to imagine or create than others</li>
</ul>
<p>–</p>
<ul>
<li>Randomization solves the fundamental problem of causal inference allowing us to estimate average treatment effects free from selection bias</li>
</ul>
<p>–</p>
<ul>
<li>Randomization is not always possible, desirable, or ethical</li>
</ul>
<p>–</p>
<ul>
<li>Observational designs that try to estimate causal effects need to justify assumptions about conditional independence:</li>
</ul>
<p><span class="math display">\[
Y_i(1),Y_i(0) \perp D_i |X_i
\]</span></p>
<p>–</p>
<ul>
<li>This assumption goes by many, jargony names: Selection on Observables, Conditional Independence, No unmeasured confounders.</li>
</ul>
<p>–</p>
<ul>
<li>Credibility of this assumption depends less on having a lot of data, and more on how your data were generated.</li>
</ul>
<p>–</p>
<ul>
<li>Observational designs estimate the effect of <span class="math inline">\(D\)</span> conditional on <span class="math inline">\(X\)</span> using covariate adjustment.</li>
</ul>
<p>class:inverse, middle, center # 🔍 ## Covariate Adjustment</p>
</section>
<section id="review-covariate-adjustment" class="level2">
<h2 class="anchored" data-anchor-id="review-covariate-adjustment">Review: Covariate Adjustment</h2>
<ul>
<li>Covariate adjustment are a set of statistical procedures that allow us to estimate conditional values
<ul>
<li><span class="math inline">\(e.g.(E[Y|X=x]), E[Happiness| leetCoder == T]\)</span></li>
</ul></li>
<li>We adjust for covariates to improve our predictions and make credible comparisons
<ul>
<li><span class="math inline">\(E[\text{New Covid-19 cases}|\text{Face mask policy}]\)</span> vs <span class="math inline">\(E[\text{New Covid-19 cases}|\text{Face mask policy |June 2020 },]\)</span></li>
<li><span class="math inline">\(ATE = E[Y| D = 1] - E[Y | D=0]\)</span></li>
</ul></li>
<li>Three approaches:
<ul>
<li>Subclassification</li>
<li>Matching</li>
<li>Regression</li>
</ul></li>
</ul>
</section>
<section id="subclassification" class="level2">
<h2 class="anchored" data-anchor-id="subclassification">Subclassification</h2>
<ul>
<li><p>Subclassification is a simple way to adjust for a covariate</p>
<ul>
<li>Subset the data to include only the values you want (<span class="math inline">\(X=x\)</span>, <span class="math inline">\(D=1\)</span>, <span class="math inline">\(Interverntion = Treated\)</span>) and calculate the quantity of interest (e.g.&nbsp;a conditional mean, <code>mean(df$income[df$age &lt;30])</code>)</li>
</ul></li>
</ul>
<p>–</p>
<ul>
<li><p>But what if we want to control for more than one variable?</p></li>
<li><p>What if our variables aren’t categorical like sex, but continuous like height?</p></li>
</ul>
<p>–</p>
<ul>
<li><p><strong>The Curse of Dimensionality</strong> as you attempt to adjust for more covariates (add more dimensions), the space of possible combinations grows exponentially</p>
<ul>
<li>Assumption of Common Support likely to be violated <span class="math inline">\(0 &lt; Pr(D_i = 1|X_i) &lt; 1\)</span></li>
</ul></li>
</ul>
</section>
<section id="matching" class="level2">
<h2 class="anchored" data-anchor-id="matching">Matching</h2>
<ul>
<li><p>Matching refers to a broad set of procedures that try to recreate what randomization provides: <strong>covariate balance</strong></p>
<ul>
<li><strong>covariate balance</strong> is a fancy term for saying that in the aggregate, two groups look similar accept on group received the <em>treatment</em> <span class="math inline">\((D=1)\)</span> while another group did not <span class="math inline">\((D=0)\)</span></li>
</ul></li>
</ul>
<p>–</p>
<ul>
<li>There are many ways to try to match observations:
<ul>
<li><strong>Exact matching:</strong> Find exact matches between treatment and control observations for all covariates <span class="math inline">\(X\)</span>. Only works for a few covariates.</li>
<li><strong>Coarsened exact matching:</strong> Find approximate matches within ranges of values for <span class="math inline">\(X\)</span></li>
<li><strong>Matching on summaries of the covariates</strong> calculating a single measure of the similarility of observations and matching on this summary to produce covariate balance.</li>
</ul></li>
</ul>
<p>–</p>
<ul>
<li>Matching:
<ul>
<li>Conceptually appealing (mirrors the logic of an experiment)</li>
<li>Technically complex (complicated algorithms, finicky software)</li>
<li>Only provides balance on <strong>observed covariates</strong></li>
</ul></li>
</ul>
<p>class: inverse, center, middle # 💡<br>
# Linear Regression ## The Basics</p>
</section>
<section id="understanding-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="understanding-linear-regression">Understanding Linear Regression</h2>
<ul>
<li><strong>Conceptual</strong>
<ul>
<li>Simple linear regression estimates “a line of best fit” that summarizes relationships between two variables</li>
</ul></li>
</ul>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1x_i + \epsilon_i
\]</span></p>
<ul>
<li><strong>Practical</strong>
<ul>
<li>We estimate linear models in R using the <code>lm()</code> function</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><em>Technical/Definitional</em>
<ul>
<li>Linear regression chooses <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> to minimize the Sum of Squared Residuals (SSR):</li>
</ul></li>
</ul>
<p><span class="math display">\[\textrm{Find }\hat{\beta_0},\,\hat{\beta_1} \text{ arg min}_{\beta_0, \beta_1} \sum (y_i-(\beta_0+\beta_1x_i))^2\]</span></p>
<ul>
<li><em>Theoretical</em>
<ul>
<li>Linear regression provides a <strong>linear</strong> estimate of the conditional expectation function (CEF): <span class="math inline">\(E[Y|X]\)</span></li>
</ul></li>
</ul>
<p>class: inverse, center, middle # 💡<br>
# Conceptual: Linear Regression ## Linear Regression Provides an Estimate of the Line of Best Fit</p>
</section>
<section id="conceptual-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="conceptual-linear-regression">Conceptual: Linear Regression</h2>
<ul>
<li><p>Regression is a tool for describing relationships.</p>
<ul>
<li><p>How does some outcome we’re interested in tend to change as some predictor of that outcome changes?</p></li>
<li><p>How does economic development vary with democracy?</p></li>
<li><p>How does economic development vary with democracy, adjusting for natural resources like oil and gas</p></li>
</ul></li>
<li><p>Formally:</p></li>
</ul>
<p><span class="math display">\[
y_i = f(x_i) + \epsilon
\]</span></p>
<ul>
<li><p>Y is a function of X plus some error, <span class="math inline">\(\epsilon\)</span></p></li>
<li><p>Linear regression assumes that relationship between an outcome and a predictor can be by a <a href="https://en.wikipedia.org/wiki/Linearity" target="_blank">linear</a> function</p></li>
</ul>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon
\]</span></p>
</section>
<section id="linear-regression-and-the-line-of-best-fit" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-and-the-line-of-best-fit">Linear Regression and the Line of Best Fit</h2>
<ul>
<li>The goal of linear regression is to choose coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> to summarizes the relationship between <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span></li>
</ul>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon
\]</span></p>
<ul>
<li><p>To accomplish this we need some sort of criteria.</p></li>
<li><p>For linear regression, that criteria is minimizing the error between what our model predicts <span class="math inline">\(\hat{y_i} = \beta_0 + \beta_1 x_i\)</span> and what we actually observed <span class="math inline">\((y_i)\)</span></p></li>
<li><p>More on this to come. But first…</p></li>
</ul>
</section>
<section id="regression-notation" class="level2">
<h2 class="anchored" data-anchor-id="regression-notation">Regression Notation</h2>
<ul>
<li><p><span class="math inline">\(y_i\)</span> an <strong>outcome variable</strong> or thing we’re trying to explain</p>
<ul>
<li>AKA: The dependent variable, The response Variable, The left hand side of the model</li>
</ul></li>
<li><p><span class="math inline">\(x_i\)</span> a <strong>predictor variables</strong> or things we think explain variation in our outcome</p>
<ul>
<li><p>AKA: The independent variable, covariates, the right hand side of the model.</p></li>
<li><p>Cap or No Cap: I’ll use <span class="math inline">\(X\)</span> (should be <span class="math inline">\(\mathbf{X}\)</span>) to denote a set (matrix) of predictor variables. <span class="math inline">\(y\)</span> vs <span class="math inline">\(Y\)</span> can also have technical distinctions (Sample vs Population, observed value vs Random Variable, …)</p></li>
</ul></li>
<li><p><span class="math inline">\(\beta\)</span> a set of <strong>unknown parameters</strong> that describe the relationship between our outcome <span class="math inline">\(y_i\)</span> and our predictors <span class="math inline">\(x_i\)</span></p></li>
<li><p><span class="math inline">\(\epsilon\)</span> the <strong>error term</strong> representing variation in <span class="math inline">\(y_i\)</span> not explained by our model.</p></li>
</ul>
</section>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<p>Let’s return to the simple (bivariate) linear regressions we introduced last week:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon
\]</span></p>
<ul>
<li><p>We call this a bivariate regression, because there are only two variables.</p></li>
<li><p>We call this a linear regression, because <span class="math inline">\(y_i = \beta_0 + \beta_1 x_i\)</span> is the equation for a line, where:</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> corresponds to the <span class="math inline">\(y\)</span> intercept, or the model’s prediction when <span class="math inline">\(x = 0\)</span>.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> corresponds to the slope, or how <span class="math inline">\(y\)</span> is predicted to change as <span class="math inline">\(x\)</span> changes.</p></li>
</ul></li>
</ul>
</section>
<section id="linear-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-1">Linear Regression</h2>
<ul>
<li>If you find this notation confusing, try plugging in substantive concepts for what <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> represent</li>
<li>Say we wanted to know how attitudes to transgender people varied with age in the baseline survey from Lab 03.</li>
</ul>
<p>The generic linear model</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_i + \epsilon\]</span></p>
<p>Reflects:</p>
<p><span class="math display">\[\text{Transgender Feeling Thermometer}_i = \beta_0 + \beta_1\text{Age}_i + \epsilon_i\]</span></p>
</section>
<section id="practical-estimating-a-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="practical-estimating-a-linear-regression">Practical: Estimating a Linear Regression</h2>
<ul>
<li>We estimate linear regressions in <code>R</code> using the <code>lm()</code> function.</li>
<li><code>lm()</code> requires two arguments:
<ul>
<li>a <code>formula</code> argument of the general form <code>y ~ x</code> read as “Y modeled by X” or below “Transgender Feeling Thermometer (<code>y</code>) modeled by (<code>~</code>) Age (<code>x</code>)</li>
<li>a <code>data</code> argument telling R where to find the variables in the formula</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://pols1600.paultesta.org/files/data/03_lab.rda"</span>))</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(therm_trans_t0 <span class="sc">~</span> vf_age, <span class="at">data =</span> df)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = therm_trans_t0 ~ vf_age, data = df)

Coefficients:
(Intercept)       vf_age  
    62.8196      -0.2031  </code></pre>
</div>
</div>
<p>The coefficients from <code>lm()</code> are saved in object called <code>m1</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>m1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = therm_trans_t0 ~ vf_age, data = df)

Coefficients:
(Intercept)       vf_age  
    62.8196      -0.2031  </code></pre>
</div>
</div>
<p><code>m1</code> actually contains a lot of information</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "coefficients"  "residuals"     "effects"       "rank"         
 [5] "fitted.values" "assign"        "qr"            "df.residual"  
 [9] "na.action"     "xlevels"       "call"          "terms"        
[13] "model"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>m1<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      vf_age 
 62.8195994  -0.2030711 </code></pre>
</div>
</div>
</section>
<section id="practical-interpreting-a-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="practical-interpreting-a-linear-regression">Practical: Interpreting a Linear Regression</h2>
<p>We can extract the intercept and slope from this simple bivariate model, using the <code>coef()</code> function</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All the coefficients</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept)      vf_age 
 62.8195994  -0.2030711 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just the intercept</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">1</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
    62.8196 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just the slope</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    vf_age 
-0.2030711 </code></pre>
</div>
</div>
</section>
<section id="practical-interpreting-a-linear-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="practical-interpreting-a-linear-regression-1">Practical: Interpreting a Linear Regression</h2>
<p>The two coefficients from <code>m1</code> define a line of best fit, summarizing how feelings toward transgender individuals change with age</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 x_i + \epsilon\]</span></p>
<p><span class="math display">\[\text{Transgender Feeling Thermometer}_i = \beta_0 + \beta_1\text{Age}_i + \epsilon_i\]</span></p>
<p><span class="math display">\[\text{Transgender Feeling Thermometer}_i = 62.82 + -0.2 \text{Age}_i + \epsilon_i\]</span></p>
</section>
<section id="practical-predicted-values-from-a-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="practical-predicted-values-from-a-linear-regression">Practical: Predicted values from a Linear Regression</h2>
<ul>
<li><p>Often it’s useful for interpretation to obtain predicted values from a regression.</p></li>
<li><p>To obtain predicted vales <span class="math inline">\((\hat{y})\)</span>, we simply plug in a value for <span class="math inline">\(x\)</span> (In this case, <span class="math inline">\(Age\)</span>) and evaluate our equation.</p></li>
<li><p>For example, might we expect attitudes to differ among an 18-year-old college student and their 68-year-old grandparent?</p></li>
</ul>
<p><span class="math display">\[\hat{FT}_{x=18} = 62.82 + -0.2 \times 18  = 59.16\]</span> <span class="math display">\[\hat{FT}_{x=65} = 62.82 + -0.2 \times 68  = 49.01\]</span></p>
</section>
<section id="practical-predicted-values-from-a-linear-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="practical-predicted-values-from-a-linear-regression-1">Practical: Predicted values from a Linear Regression</h2>
<p>We could do this by hand</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m1)[<span class="dv">2</span>] <span class="sc">*</span> <span class="dv">18</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   59.16432 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(m1)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(m1)[<span class="dv">2</span>] <span class="sc">*</span> <span class="dv">68</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   49.01076 </code></pre>
</div>
</div>
</section>
<section id="practical-predicted-values-from-a-linear-regression-2" class="level2">
<h2 class="anchored" data-anchor-id="practical-predicted-values-from-a-linear-regression-2">Practical: Predicted values from a Linear Regression</h2>
<p>More often we will:</p>
<ul>
<li>Make a prediction data frame (called <code>pred_df</code> below) with the values of interests</li>
<li>Use the <code>predict()</code> function with our linear model (<code>m1</code>) and <code>pred_df</code></li>
<li>Save the predicted values to our new column in our prediction data frame</li>
</ul>
</section>
<section id="practical-predicted-values-from-a-linear-regression-3" class="level2">
<h2 class="anchored" data-anchor-id="practical-predicted-values-from-a-linear-regression-3">Practical: Predicted values from a Linear Regression</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make prediction data frame</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>pred_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">vf_age =</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">68</span>)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict FT for 18 and 68 year-olds</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(m1, <span class="at">newdata =</span> pred_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2 
59.16432 49.01076 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save predictions to data frame</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>pred_df<span class="sc">$</span>ft_trans_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1, <span class="at">newdata =</span> pred_df)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>pred_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  vf_age ft_trans_hat
1     18     59.16432
2     68     49.01076</code></pre>
</div>
</div>
</section>
<section id="practical-visualizing-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="practical-visualizing-linear-regression">Practical: Visualizing Linear Regression</h2>
<p>We can visualize simple regression by:</p>
<ul>
<li><p>plotting a scatter plot of the outcome (y-axis) and predictors (x-axis)</p></li>
<li><p>overlaying the line defined by <code>lm()</code></p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>fig_lm <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(vf_age,therm_trans_t0))<span class="sc">+</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span>.<span class="dv">5</span>, <span class="at">alpha=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(m1)[<span class="dv">1</span>],</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">slope =</span> <span class="fu">coef</span>(m1)[<span class="dv">2</span>],</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">col =</span> <span class="st">"blue"</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>              )<span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>,<span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">100</span>)<span class="sc">+</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"point"</span>,</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>           <span class="at">x =</span> <span class="dv">0</span>, <span class="at">y =</span> <span class="fu">coef</span>(m1)[<span class="dv">1</span>],</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>           <span class="at">col=</span> <span class="st">"red"</span>,</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>           )<span class="sc">+</span></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>,</span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(beta[<span class="dv">0</span>],<span class="st">"= 62.81"</span> )),</span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>           <span class="at">x =</span> <span class="dv">1</span>, <span class="at">y =</span> <span class="fu">coef</span>(m1)[<span class="dv">1</span>]<span class="sc">+</span><span class="dv">5</span>,</span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">hjust =</span> <span class="st">"left"</span>,</span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a>           )<span class="sc">+</span></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Feeling Thermometer toward</span><span class="sc">\n</span><span class="st">Transgender People"</span></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a>fig_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/fig_lm_plot-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/figlm1code-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/figlm1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>background-image:url(“https://i.imgflip.com/66mx9d.jpg”) background-size:contain</p>
<p>class: inverse, center, middle # 💡<br>
# Technical: Linear Regression ## The Mechanics of Minimizing the Sum of Squared Errors</p>
</section>
<section id="how-did-lm-choose-beta_0-and-beta_1" class="level2">
<h2 class="anchored" data-anchor-id="how-did-lm-choose-beta_0-and-beta_1">How did <code>lm()</code> choose <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span></h2>
<p>–</p>
<ul>
<li>P: By minimizing the sum of squared errors, in procedure called Ordinary Least Squares (OLS) regression</li>
</ul>
<p>–</p>
<ul>
<li><p>Q: Ok, that’s not really that helpful…</p>
<ul>
<li>What’s an error?</li>
<li>Why would we square and sum them</li>
<li>How do we minimize them.</li>
</ul></li>
</ul>
<p>P: Good questions!</p>
</section>
<section id="whats-an-error" class="level2">
<h2 class="anchored" data-anchor-id="whats-an-error">What’s an error?</h2>
<p>An error, <span class="math inline">\(\epsilon_i\)</span> is simply the difference between the observed value of <span class="math inline">\(y_i\)</span> and what our model would predict, <span class="math inline">\(\hat{y_i}\)</span> given some value of <span class="math inline">\(x_i\)</span>. So for a model:</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1 x_{i} + \epsilon_i\]</span></p>
<p>We simply subtract our model’s prediction <span class="math inline">\(\beta_0+\beta_1 x_{i}\)</span> from the the observed value, <span class="math inline">\(y_i\)</span></p>
<p><span class="math display">\[\hat{\epsilon_i}=y_i-\hat{y_i}=(Y_i-(\beta_0+\beta_1 x_{i}))\]</span></p>
<p>To get <span class="math inline">\(\epsilon_i\)</span></p>
</section>
<section id="why-are-we-squaring-and-summing-epsilon" class="level2">
<h2 class="anchored" data-anchor-id="why-are-we-squaring-and-summing-epsilon">Why are we squaring and summing <span class="math inline">\(\epsilon\)</span></h2>
<p>There are more mathy reasons for this, but at intuitive level, the Sum of Squared Residuals (SSR)</p>
<ul>
<li><p>Squaring <span class="math inline">\(\epsilon\)</span> treats positive and negative residuals equally.</p></li>
<li><p>Summing produces single value summarizing our models overall performance.</p></li>
</ul>
<p>There are other criteria we could use (e.g.&nbsp;minimizing the sum of absolute errors), but SSR has some nice properties</p>
</section>
<section id="how-do-we-minimize-sum-epsilon2" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-minimize-sum-epsilon2">How do we minimize <span class="math inline">\(\sum \epsilon^2\)</span></h2>
<p>OLS chooses <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> to minimize <span class="math inline">\(\sum \epsilon^2\)</span>, the Sum of Squared Residuals (SSR)</p>
<p><span class="math display">\[\textrm{Find }\hat{\beta_0},\,\hat{\beta_1} \text{ arg min}_{\beta_0, \beta_1} \sum (y_i-(\beta_0+\beta_1x_i))^2\]</span></p>
</section>
<section id="how-did-lm-choose-beta_0-and-beta_1-1" class="level2">
<h2 class="anchored" data-anchor-id="how-did-lm-choose-beta_0-and-beta_1-1">How did <code>lm()</code> choose <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span></h2>
<p>In an intro stats course, we would walk through the process of finding</p>
<p><span class="math display">\[\textrm{Find }\hat{\beta_0},\,\hat{\beta_1} \text{ arg min}_{\beta_0, \beta_1} \sum (y_i-(\beta_0+\beta_1x_i))^2\]</span> Which involves a little bit of calculus. The big payoff is that</p>
<p><span class="math display">\[\beta_0 = \bar{y} - \beta_1 \bar{x}\]</span> And</p>
<p><span class="math display">\[ \beta_1 = \frac{Cov(x,y)}{Var(x)}\]</span> Which is never quite the epiphany, I think we think it is…</p>
<p>The following slides walk you through the mechanics of this exercise. We’re gonna skip through them in class, but they’re there for your reference</p>
</section>
<section id="how-do-we-minimize-sum-epsilon2-1" class="level2">
<h2 class="anchored" data-anchor-id="how-do-we-minimize-sum-epsilon2-1">How do we minimize <span class="math inline">\(\sum \epsilon^2\)</span></h2>
<p>To understand what’s going on under the hood, you need a broad understanding of some basic calculus.</p>
<p>The next few slides provide a brief review of derivatives and differential calculus.</p>
</section>
<section id="derivatives" class="level2">
<h2 class="anchored" data-anchor-id="derivatives">Derivatives</h2>
<p>The derivative of <span class="math inline">\(f\)</span> at <span class="math inline">\(x\)</span> is its rate of change at <span class="math inline">\(x\)</span></p>
<ul>
<li>For a line: the slope</li>
<li>For a curve: the slope of a line tangent to the curve</li>
</ul>
<p>You’ll see two notations for derivatives:</p>
<ol type="1">
<li>Leibniz notation:</li>
</ol>
<p><span class="math display">\[
\frac{df}{dx}(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{(x+h)-x}
\]</span></p>
<ol start="2" type="1">
<li>Lagrange: <span class="math inline">\(f^{\prime}(x)\)</span></li>
</ol>
</section>
<section id="some-useful-facts-about-derivatives" class="level2">
<h2 class="anchored" data-anchor-id="some-useful-facts-about-derivatives">Some useful Facts about Derivatives</h2>
<p>Derivative of a constant</p>
<p><span class="math display">\[
f^{\prime}(c)=0
\]</span></p>
<p>Derivative of a line f(x)=2x</p>
<p><span class="math display">\[
f^{\prime}(2x)=2
\]</span></p>
<p>Derivative of <span class="math inline">\(f(x)=x^2\)</span></p>
<p><span class="math display">\[
f^{\prime}(x^2)=2x
\]</span></p>
<p>Chain rule: y= f(g(x)). The derivative of y with respect to x is</p>
<p><span class="math display">\[
\frac{d}{dx}(f(g(x)))=f^{\prime}(g(x))g^{\prime}(x)
\]</span></p>
<p>The derivative of the “outside” times the derivative of the “inside,” remembering that the derivative of the outside function is evaluated at the value of the inside function.</p>
</section>
<section id="finding-a-local-minimums" class="level2">
<h2 class="anchored" data-anchor-id="finding-a-local-minimums">Finding a Local Minimums</h2>
<p>.pull-left[ Local minimum:</p>
<p><span class="math display">\[
f^{\prime}(x)=0 \text{ and } f^{\prime\prime}(x)&gt;0
\]</span> ]</p>
<p>.pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://copingwithcalculus.com/SecondDeriv1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://copingwithcalculus.com/SecondDerivativeTest.html" target="_blank">Source</a> ]</p>
</section>
<section id="partial-derivatives" class="level2">
<h2 class="anchored" data-anchor-id="partial-derivatives">Partial Derivatives</h2>
<p>Let <span class="math inline">\(f\)</span> be a function of the variables <span class="math inline">\((x, \dots, X_n)\)</span>. The partial derivative of <span class="math inline">\(f\)</span> with respect to <span class="math inline">\(X_i\)</span> is</p>
<p><span class="math display">\[\begin{align*}
\frac{\partial f(x, \dots, X_n)}{\partial X_i}=\lim_{h\to0}\frac{f(x, \dots X_i+h \dots, X_n)-f(x, \dots X_i \dots, X_n)}{h}
\end{align*}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://miro.medium.com/max/766/1*dToo8pNrhBmYfwmPLp6WrQ.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://towardsdatascience.com/linear-regression-detailed-view-ea73175f6e86" target="_blank">Source</a></p>
</section>
<section id="minimizing-the-sum-of-squared-errors" class="level2">
<h2 class="anchored" data-anchor-id="minimizing-the-sum-of-squared-errors">Minimizing the sum of squared errors</h2>
<p>Our model</p>
<p><span class="math display">\[y_i =\beta_0+\beta_1x_{i}+\epsilon_i\]</span></p>
<p>Finds coefficients <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> to to minimize the sum of squared residuals, <span class="math inline">\(\hat{\epsilon}_i\)</span>:</p>
<p><span class="math display">\[\begin{aligned}
\sum \hat{\epsilon_i}^2 &amp;= \sum (y_i-\beta_0-\beta_1 x_{i})^2
\end{aligned}\]</span></p>
</section>
<section id="minimizing-the-sum-of-squared-errors-1" class="level2">
<h2 class="anchored" data-anchor-id="minimizing-the-sum-of-squared-errors-1">Minimizing the sum of squared errors</h2>
<p>We solve for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, by taking the partial derivatives with respect to <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, and setting them equal to zero</p>
<p><span class="math display">\[\begin{aligned}
\frac{\partial \sum \hat{\epsilon_i}^2}{\partial \beta_0} &amp;= -2\sum (y_i-\beta_0-\beta_1 x_{i})=0 &amp; f'(-x^2) = -2x\\
\frac{\partial \sum \hat{\epsilon_i}^2}{\partial\beta_1} &amp;= -2\sum (y_i-\beta_0-\beta_1 x_{i})x_{i}=0 &amp; \text{chain rule}
\end{aligned}\]</span></p>
</section>
<section id="solving-for-beta_0" class="level2">
<h2 class="anchored" data-anchor-id="solving-for-beta_0">Solving for <span class="math inline">\(\beta_0\)</span></h2>
<p>First, we’ll solve for <span class="math inline">\(\beta_0\)</span>, by multiplying both sides by -1/2 and distributing the <span class="math inline">\(\sum\)</span>:</p>
<p><span class="math display">\[\begin{aligned}
0 &amp;= -2\sum (y_i-\beta_0-\beta_1 x_{i})\\
\sum \beta_0 &amp;= \sum y_i - \sum \beta_1 x_{i}\\
N \beta_0 &amp;= \sum y_i -\sum \beta_1 x_{i}\\
\beta_0 &amp;= \frac{\sum y_i}{N} - \frac{\beta_1 \sum x_{i}}{N}\\
\beta_0 &amp;= \bar{y} - \beta_1 \bar{x}
\end{aligned}\]</span></p>
</section>
<section id="solving-for-beta_1" class="level2">
<h2 class="anchored" data-anchor-id="solving-for-beta_1">Solving for <span class="math inline">\(\beta_1\)</span></h2>
<p>Now, we can solve for <span class="math inline">\(\beta_1\)</span> plugging in <span class="math inline">\(\beta_0\)</span>.</p>
<p><span class="math display">\[\begin{aligned}
0 &amp;= -2\sum [(y_i-\beta_0-\beta_1 x_{i})x_{i}]\\
0 &amp;= \sum [y_ix_i-(\bar{y} - \beta_1 \bar{x})x_{i}-\beta_1 x_{i}^2]\\
0 &amp;= \sum [y_ix_i-\bar{y}x_{i} + \beta_1 \bar{x}x_{i}-\beta_1 x_{i}^2]
\end{aligned}\]</span></p>
</section>
<section id="solving-for-beta_1-1" class="level2">
<h2 class="anchored" data-anchor-id="solving-for-beta_1-1">Solving for <span class="math inline">\(\beta_1\)</span></h2>
<p>Now we’ll rearrange some terms and pull out an <span class="math inline">\(x_{i}\)</span> to get</p>
<p><span class="math display">\[\begin{aligned}
0 &amp;= \sum [(y_i -\bar{y} + \beta_1 \bar{x}-\beta_1 x_{i})x_{i}]
\end{aligned}\]</span></p>
<p>Dividing both sides by <span class="math inline">\(x_{i}\)</span> and distributing the summation, we can isolate <span class="math inline">\(\beta_1\)</span></p>
<p><span class="math display">\[\begin{aligned}
\beta_1 \sum (x_{i}-\bar{x}) &amp;= \sum (y_i -\bar{y})
\end{aligned}\]</span></p>
<p>Dividing by <span class="math inline">\(\sum (x_{i}-\bar{x})\)</span> to get</p>
<p><span class="math display">\[\begin{aligned}
\beta_1  &amp;= \frac{\sum (y_i -\bar{y})}{\sum (x_{i}-\bar{x})}
\end{aligned}\]</span></p>
</section>
<section id="solving-for-beta_1-2" class="level2">
<h2 class="anchored" data-anchor-id="solving-for-beta_1-2">Solving for <span class="math inline">\(\beta_1\)</span></h2>
<p>Finally, by multiplying by <span class="math inline">\(\frac{(x_{i}-\bar{x})}{(x_{i}-\bar{x})}\)</span> we get</p>
<p><span class="math display">\[\begin{aligned}
\beta_1  &amp;= \frac{\sum (y_i -\bar{y})(x_{i}-\bar{x})}{\sum (\bar{x}-x_{i})^2}
\end{aligned}\]</span></p>
<p>Which has a nice interpretation:</p>
<p><span class="math display">\[\begin{aligned}
\beta_1 &amp;= \frac{Cov(x,y)}{Var(x)}
\end{aligned}\]</span></p>
<p>So the coefficient in a simple linear regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X\)</span> is simply the ratio of the covariance between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> over the variance of <span class="math inline">\(X\)</span>. Neat!</p>
<p>class: inverse, center, middle # 💡<br>
# Theoretical: Linear Regression ## OLS provides a linear estimate of CEF: E[Y|X]</p>
</section>
<section id="linear-regression-is-a-many-splendored-thing" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-is-a-many-splendored-thing">Linear Regression is a many splendored thing</h2>
<p><a href="https://www.timlrx.com/tags/ols" target="_blank">Timothy Lin</a> provides a great overview of the various interpretations/motivations for linear regression.</p>
<ul>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-ols" target="_blank">least squares estimator</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-geometry" target="_blank">linear projection</a> of <span class="math inline">\(y\)</span> on the subspace spanned by <span class="math inline">\(X\beta\)</span></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-method-of-moments" target="_blank">method of moments estimator</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-maximum-likelihood" target="_blank">maximum likelihood estimator</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-singular-vector-decomposition" target="_blank">singular vector decomposition</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-approximation-of-the-conditional-expectation-function#fn1" target="_blank">linear approximation of the conditional expectation function</a></p></li>
</ul>
</section>
<section id="linear-regression-is-a-many-splendored-thing-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-is-a-many-splendored-thing-1">Linear Regression is a many splendored thing</h2>
<p><a href="https://www.timlrx.com/tags/ols" target="_blank">Timothy Lin</a> provides a great overview of various interpretations/motivations for linear regression.</p>
<ul>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-ols" target="_blank">least squares estimator</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-geometry" target="_blank">linear projection</a> of <span class="math inline">\(y\)</span> on the subspace spanned by <span class="math inline">\(X\beta\)</span></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-method-of-moments" target="_blank">method of moments estimator</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-maximum-likelihood" target="_blank">maximum likelihood estimator</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-singular-vector-decomposition" target="_blank">singular vector decomposition</a></p></li>
<li><p>A <a href="https://www.timlrx.com/blog/notes-on-regression-approximation-of-the-conditional-expectation-function#fn1" target="_blank"><strong>linear approximation of the conditional expectation function</strong></a></p></li>
</ul>
</section>
<section id="the-conditional-expectation-function" class="level2">
<h2 class="anchored" data-anchor-id="the-conditional-expectation-function">The Conditional Expectation Function</h2>
<p>Of all the functions we could choose to describe the relationship between <span class="math inline">\(Y\)</span> and <span class="math inline">\(X\)</span>,</p>
<p><span class="math display">\[
Y_i = f(X_i) + \epsilon_i
\]</span></p>
<p>the conditional expectation of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span> <span class="math inline">\((E[Y|X])\)</span>, has some appealing properties</p>
<p><span class="math display">\[
Y_i = E[Y_i|X_i] + \epsilon
\]</span></p>
<p>The error, by definition, is uncorrelated with X and <span class="math inline">\(E[\epsilon|X]=0\)</span></p>
<p><span class="math display">\[
E[\epsilon|X] = E[Y - E[Y|X]|X]= E[Y|X] - E[Y|X] = 0
\]</span></p>
<p>Of all the possible functions <span class="math inline">\(g(X)\)</span>, we can show that $E[Y_i|X_i] $ is the best predictor in terms of minimizing <strong>mean squared error</strong></p>
<p><span class="math display">\[
E[ (Y - g(Y))^2] \geq E[(Y - E[Y|X])^2]
\]</span></p>
</section>
<section id="linear-approximations-to-the-conditional-expectation-function" class="level2">
<h2 class="anchored" data-anchor-id="linear-approximations-to-the-conditional-expectation-function">Linear Approximations to the Conditional Expectation Function</h2>
<ul>
<li>We can then show (in a different class) that linear regression provides the best linear predictor of the CEF
<ul>
<li>Chapter 3, of <a href="https://bruknow.library.brown.edu/permalink/01BU_INST/9mvq88/alma991028523169706966" target="_blank">Mostly Harmless Econometrics</a></li>
<li>Chapter 4 of <a href="https://bruknow.library.brown.edu/permalink/01BU_INST/9mvq88/alma991000736119706966" target="_blank">Foundations of Agnostic Statistics</a></li>
</ul></li>
<li>Furthermore, when the CEF is linear, it’s equal exactly to OLS regression</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(vf_age,therm_trans_t0))<span class="sc">+</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span>.<span class="dv">5</span>, <span class="at">alpha=</span>.<span class="dv">5</span>)<span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"point"</span>, <span class="fu">aes</span>(<span class="at">col=</span><span class="st">"CEF"</span>))<span class="sc">+</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">geom=</span><span class="st">"line"</span>, <span class="fu">aes</span>(<span class="at">col=</span><span class="st">"CEF"</span>))<span class="sc">+</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Feeling Thermometer toward</span><span class="sc">\n</span><span class="st">Transgender People"</span>,</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> <span class="st">""</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>() <span class="ot">-&gt;</span> plot_cef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/cef1-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>plot_cef<span class="sc">+</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se=</span>F, <span class="fu">aes</span>(<span class="at">col =</span> <span class="st">"OLS"</span>)) <span class="ot">-&gt;</span> plot_cef</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>plot_cef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/cef2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>plot_cef<span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se=</span>F, <span class="fu">aes</span>(<span class="at">col =</span> <span class="st">"OLS"</span>)) <span class="ot">-&gt;</span> plot_cef</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>plot_cef</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/cef3-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="what-you-need-to-know-about-regression" class="level2">
<h2 class="anchored" data-anchor-id="what-you-need-to-know-about-regression">What you need to know about Regression</h2>
<ul>
<li><strong>Conceptual</strong>
<ul>
<li>Simple linear regression estimates a line of best fit that summarizes relationships between two variables</li>
</ul></li>
</ul>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1x_i + \epsilon_i
\]</span></p>
<ul>
<li><strong>Practical</strong>
<ul>
<li>We estimate linear models in R using the <code>lm()</code> function</li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><em>Technical/Definitional</em>
<ul>
<li>Linear regression chooses <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> to minimize the Sum of Squared Residuals (SSR):</li>
</ul></li>
</ul>
<p><span class="math display">\[\textrm{Find }\hat{\beta_0},\,\hat{\beta_1} \text{ arg min}_{\beta_0, \beta_1} \sum (y_i-(\beta_0+\beta_1x_i))^2\]</span></p>
<ul>
<li><em>Theoretical</em>
<ul>
<li>Linear regression provides a <strong>linear</strong> estimate of the conditional expectation function (CEF): <span class="math inline">\(E[Y|X]\)</span></li>
</ul></li>
</ul>
<p>class: center, middle background-image:url(https://www.memecreator.org/static/images/memes/5312518.jpg) background-size:contain</p>
<p>class: inverse, center, middle # 💡<br>
# Three Designs for Causal Inference in Observational Studies</p>
</section>
<section id="credible-cauasal-inference-in-observational-studies" class="level2">
<h2 class="anchored" data-anchor-id="credible-cauasal-inference-in-observational-studies">Credible Cauasal Inference in Observational Studies</h2>
<p>Subclassification, matching, and regression all require an assumption of selection on observables:</p>
<p><span class="math display">\[
Y_i(1),Y_i(0) \perp D_i |x_i
\]</span></p>
<p>But how do we know if we’ve got the right model or we’ve controlled for the right variables?</p>
<p>–</p>
<p>Typically, we don’t</p>
</section>
<section id="credible-cauasal-inference-in-observational-studies-1" class="level2">
<h2 class="anchored" data-anchor-id="credible-cauasal-inference-in-observational-studies-1">Credible Cauasal Inference in Observational Studies</h2>
<p>Instead, social scientists look for situations where the credibility of</p>
<p><span class="math display">\[
Y_i(1),Y_i(0) \perp D_i |X_i
\]</span></p>
<p>depends less on how much data you have and much more on how your data were generated.</p>
<p>class: middle</p>
<p>.pull-left[ &gt; Empirical microeconomics has experienced a credibility revolution, with a consequent increase in policy relevance and scientific impact. … [T]he primary engine driving improvement has been a focus on the <strong>quality of empirical research designs.</strong> (p.&nbsp;4)</p>
<p>]</p>
<p>.pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./images/04_cred.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.24.2.3" target="_blank">Source</a></p>
<p>]</p>
<p>class: middle</p>
<p>.pull-left[ &gt; Design-based studies are distinguished by their prima facie credibility and by the attention investigators devote to making both an <strong>institutional</strong> and a <strong>data-driven</strong> case for causality (p.&nbsp;5)</p>
<p>]</p>
<p>.pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./images/04_cred.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.24.2.3" target="_blank">Source</a> ]</p>
<p>class: middle</p>
<p>.pull-left[ &gt; The econometric methods that feature most prominently in quasi-experimental studies are <strong>instrumental variables</strong>, <strong>regression discontinuity</strong> methods,and <strong>differences-in-differences</strong>-style policy analysis. … The best of today’s design-based studies make a strong institutional case, backed up with empirical evidence, for the variation thought to generate a useful <strong>natural experiment</strong>.(p.&nbsp;12)</p>
<p>]</p>
<p>.pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./images/04_cred.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.24.2.3" target="_blank">Source</a> ]</p>
</section>
<section id="three-designs-for-causal-inference-in-observational-studies" class="level2">
<h2 class="anchored" data-anchor-id="three-designs-for-causal-inference-in-observational-studies">Three Designs for Causal Inference in Observational Studies</h2>
<ul>
<li><p>Difference in Differences</p></li>
<li><p>Regression Discontinuity</p></li>
<li><p>Instrumental Variables</p></li>
</ul>
<p>class: inverse, center, middle # 💡 Difference in Differences</p>
<p>class: inverse, center, middle background-image:url(https://www.finebooksmagazine.com/sites/default/files/styles/gallery_item/public/media-images/2020-11/map-lead-4.jpg?h=2ded5a3f&amp;itok=Mn-K5rQc) background-size: cover ## London in the Time of Cholera</p>
</section>
<section id="motivating-example-what-causes-cholera" class="level2">
<h2 class="anchored" data-anchor-id="motivating-example-what-causes-cholera">Motivating Example: What causes Cholera?</h2>
<ul>
<li><p>In the 1800s, cholera was thought to be transmitted through the air.</p></li>
<li><p>John Snow (the physician, not the snack), to explore the origins eventunally concluding that cholera was transmitted through living organisms in water.</p></li>
<li><p>Leveraged a <strong>natural experiment</strong> in which one water company in London moved its pipes further upstream (reducing contamination for Lambeth), while other companies kept their pumps serving Southwark and Vauxhall in the same location.</p></li>
</ul>
</section>
<section id="notation" class="level2">
<h2 class="anchored" data-anchor-id="notation">Notation</h2>
<p>Let’s adopt a little notation to help us think about the logic of Snow’s design:</p>
<ul>
<li><p><span class="math inline">\(D\)</span>: treatment indicator, 1 for treated neighborhoods (Lambeth), 0 for control neighborhoods (Southwark and Vauxhall)</p></li>
<li><p><span class="math inline">\(T\)</span>: period indicator, 1 if post treatment (1854), 0 if pre-treatment (1849).</p></li>
<li><p><span class="math inline">\(Y_{di}(t)\)</span> the potential outcome of unit <span class="math inline">\(i\)</span></p>
<ul>
<li><p><span class="math inline">\(Y_{1i}(t)\)</span> the potential outcome of unit <span class="math inline">\(i\)</span> when treated between the two periods</p></li>
<li><p><span class="math inline">\(Y_{0i}(t)\)</span> the potential outcome of unit <span class="math inline">\(i\)</span> when control between the two periods</p></li>
</ul></li>
</ul>
</section>
<section id="causal-effects" class="level2">
<h2 class="anchored" data-anchor-id="causal-effects">Causal Effects</h2>
<p>The individual causal effect for unit i at time t is:</p>
<p><span class="math display">\[\tau_{it} = Y_{1i}(t) − Y_{0i}(t)\]</span></p>
<p>What we observe is</p>
<p><span class="math display">\[Y_i(t) = Y_{0i}(t)\cdot(1 − D_i(t)) + Y_{1i}(t)\cdot D_i(t)\]</span></p>
<p><span class="math inline">\(D\)</span> only equals 1, when <span class="math inline">\(T\)</span> equals 1, so we never observe <span class="math inline">\(Y_0i(1)\)</span> for the treated units.</p>
<p>In words, we don’t know what Lambeth’s outcome would have been in the second period, had they not been treated.</p>
</section>
<section id="average-treatment-on-treated" class="level2">
<h2 class="anchored" data-anchor-id="average-treatment-on-treated">Average Treatment on Treated</h2>
<p>Our goal is to estimate the average effect of treatment on treated (ATT):</p>
<p><span class="math display">\[\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]\]</span></p>
<p>That is, what would have happened in Lambeth, had their water company not moved their pipes</p>
</section>
<section id="average-treatment-on-treated-1" class="level2">
<h2 class="anchored" data-anchor-id="average-treatment-on-treated-1">Average Treatment on Treated</h2>
<p>Our goal is to estimate the average effect of treatment on treated (ATT):</p>
<p>We we can observe is:</p>
<div class="line-block">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| Post-Period (T=1) | Pre-Period (T=0) |</div>
<p>||–|-| | Treated <span class="math inline">\(D_{i}=1\)</span> | <span class="math inline">\(E[Y_{1i}(1)\vert D_i = 1]\)</span> | <span class="math inline">\(E[Y_{0i}(0)\vert D_i = 1]\)</span> | | Control <span class="math inline">\(D_i=0\)</span> | <span class="math inline">\(E[Y_{0i}(1)\vert D_i = 0]\)</span> | <span class="math inline">\(E[Y_{0i}(0)\vert D_i = 0]\)</span> |</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Because potential outcomes notation is abstract, let’s consider a modified description of the Snow’s cholera death data from <a href="https://mixtape.scunning.com/difference-in-differences.html" target="_blank">Scott Cunningham</a>:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Company</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1854 (T=1)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1849 (T=0)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Lambeth (D=1)</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">85</td>
</tr>
<tr class="even">
<td style="text-align: left;">Southwark and Vauxhall (D=0</td>
<td style="text-align: right;">147</td>
<td style="text-align: right;">135</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="how-can-we-estimate-the-effect-of-moving-pumps-upstream" class="level2">
<h2 class="anchored" data-anchor-id="how-can-we-estimate-the-effect-of-moving-pumps-upstream">How can we estimate the effect of moving pumps upstream?</h2>
<p>Recall, our goal is to estimate the effect of the the treatment on the treated:</p>
<p><span class="math display">\[\tau_{ATT} = E[Y_{1i}(1) -  Y_{0i}(1)|D=1]\]</span></p>
<p>Let’s conisder some strategies Snow could take to estimate this quantity:</p>
</section>
<section id="before-vs-after-comparisons" class="level2">
<h2 class="anchored" data-anchor-id="before-vs-after-comparisons">Before vs after comparisons:</h2>
<ul>
<li><p>Snow could have compared Labmeth in 1854 <span class="math inline">\((E[Y_i(1)|D_i = 1] = 19)\)</span> to Lambeth in 1849 <span class="math inline">\((E[Y_i(0)|D_i = 1]=85)\)</span>, and claimed that moving the pumps upstream led to 66 fewer cholera deaths.</p></li>
<li><p>This comparison assumes Lambeth’s pre-treatment outcomes in 1849 are a good proxy for what its outcomes would have been in 1954 if the pumps hadn’t moved (<span class="math inline">\(E[Y_{0i}(1)|D_i = 1]\)</span>).</p></li>
<li><p>A skeptic might argue that Lambeth in 1849 <span class="math inline">\(\neq\)</span> Lambeth in 1854</p></li>
</ul>
</section>
<section id="treatment-control-comparisons-in-the-post-period" class="level2">
<h2 class="anchored" data-anchor-id="treatment-control-comparisons-in-the-post-period">Treatment-Control comparisons in the post period</h2>
<ul>
<li><p>Snow could have compared outcomes between Lambeth and S&amp;V in 1954 (<span class="math inline">\(E[Yi(1)|Di = 1] − E[Yi(1)|Di = 0]\)</span>), concluding that the change in pump locations led to 128 fewer deaths.</p></li>
<li><p>Here the assumption is that the outcomes in S&amp;V and in 1854 provide a good proxy for what would have happened in Lambeth in 1954 had the pumps not been moved (<span class="math inline">\(E[Y_{0i}(1)|D_i = 1]\)</span>)</p></li>
<li><p>Again, our skeptic could argue Lambeth <span class="math inline">\(\neq\)</span> S&amp;V</p></li>
</ul>
</section>
<section id="difference-in-differences" class="level2">
<h2 class="anchored" data-anchor-id="difference-in-differences">Difference in Differences</h2>
<p>To address these concerns, Snow employed what we now call a difference-in-differences design,</p>
<p>There are two, equivalent ways to view this design.</p>
<p><span class="math display">\[\underbrace{\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\}}_{\text{1. Treat-Control |Post }}− \overbrace{\{E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}=0 ]}^{\text{Treated-Control|Pre}}\]</span></p>
<ul>
<li>Difference 1: Average change between Treated and Control in Post Period</li>
<li>Difference 2: Average change between Treated and Control in Pre Period</li>
</ul>
<p>Which is equivalent to:</p>
<p><span class="math display">\[\underbrace{\{E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(0)|D_{i} = 1]\}}_{\text{Post - Pre |Treated }}− \overbrace{\{E[Y_{i}(1)|D_{i} = 0] − E[Y_{i}(0)|D_{i}=0 ]}^{\text{Post-Pre|Control}}\]</span></p>
<ul>
<li>Difference 1: Average change between Treated over time</li>
<li>Difference 2: Average change between Control over time</li>
</ul>
</section>
<section id="difference-in-differences-1" class="level2">
<h2 class="anchored" data-anchor-id="difference-in-differences-1">Difference in Differences</h2>
<p>You’ll see the DiD design represented both ways, but they produce the same result:</p>
<p><span class="math display">\[
\tau_{ATT} = (19-147) - (85-135) = -78
\]</span></p>
<p><span class="math display">\[
\tau_{ATT} = (19-85) - (147-135) = -78
\]</span></p>
</section>
<section id="identifying-assumption-of-a-difference-in-differences-design" class="level2">
<h2 class="anchored" data-anchor-id="identifying-assumption-of-a-difference-in-differences-design">Identifying Assumption of a Difference in Differences Design</h2>
<p>The key assumption in this design is what’s known as the parallel trends assumption: <span class="math inline">\(E[Y_{0i}(1) − Y_{0i}(0)|D_i = 1] = E[Y_{0i}(1) − Y_{0i}(0)|D_i = 0]\)</span></p>
<ul>
<li>In words: If Lambeth hadn’t moved its pumps, it would have followed a similar path as S&amp;V</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/paralleltrends-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Where:</p>
<ol type="1">
<li><span class="math inline">\(E[Y_{i}(1)|D_{i} = 1] − E[Y_{i}(1)|D_{i} = 0]\)</span></li>
<li><span class="math inline">\(E[Y_{i}(0)|D_{i} = 1] − E[Y_{i}(0)|D_{i}\} = 0]\)</span></li>
<li><span class="math inline">\(E[Y_{1i}(1) − Y_{0i}(1)|D_{i} = 1]\)</span></li>
</ol>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<ul>
<li><p>A Difference in Differences (DiD, or diff-in-diff) design combines a pre-post comparison, with a treated and control comparison</p>
<ul>
<li><p>Taking the pre-post difference removes any fixed differences between the units</p></li>
<li><p>Then taking the difference between treated and control differences removes any common differences over time</p></li>
</ul></li>
<li><p>The key identifying assumption of a DiD design is the “assumption of parallel trends”</p>
<ul>
<li>Absent treatment, treated and control groups would see the same changes over time.</li>
<li>Hard to prove, possible to test</li>
</ul></li>
</ul>
</section>
<section id="extensions-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="extensions-and-limitations">Extensions and limitations</h2>
<ul>
<li>DiD easy to estimate with linear regression</li>
<li>Generalizes to multiple periods and treatment interventions
<ul>
<li>More pre-treatment periods allow you assess “parallel trends” assumption</li>
</ul></li>
<li>Alternative methods
<ul>
<li>Synthetic control</li>
<li>Event Study Designs</li>
</ul></li>
<li>What if you have multiple treatments or treatments that come and go?
<ul>
<li>Panel Matching</li>
<li>Generalized Synthetic control</li>
</ul></li>
</ul>
</section>
<section id="applications" class="level2">
<h2 class="anchored" data-anchor-id="applications">Applications</h2>
<ul>
<li><p><a href="https://www.nber.org/papers/w4509" target="_blank">Card and Krueger (1994)</a> What effect did raising the minimum wage in NJ have on employment</p></li>
<li><p><a href="https://onlinelibrary.wiley.com/doi/full/10.1111/ajps.12116?casa_token=_ceCu4SwzTEAAAAA%3AP9aeaZpT_Zh1VdWKXx_tEmzaJTtMJ1n0eG7EaYlvJZYN000re33cfMAI2O8N8htFJjOsln2GyVeQql4" target="_blank">Abadie, Diamond, &amp; Hainmueller (2014)</a> What effect did German Unification have on economic development in West Germany</p></li>
<li><p><a href="https://www.cambridge.org/core/journals/american-political-science-review/article/impact-of-recentralization-on-public-services-a-differenceindifferences-analysis-of-the-abolition-of-elected-councils-in-vietnam/3477854BAAFE152DC93C594169D64F58" target="_blank">Malesky, Nguyen and Tran (2014)</a> How does decentralization influence public services?</p></li>
</ul>
<p>class: inverse, center, middle # 💡 Regression Discontinuity Design</p>
</section>
<section id="motivating-example" class="level2">
<h2 class="anchored" data-anchor-id="motivating-example">Motivating Example</h2>
<p>.pull-left[ - Do Members of Parliament in the UK get richer from holding office (QSS Chapter 4.3.4)] .pull-right[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./images/04_eggers.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://www.cambridge.org/core/journals/american-political-science-review/article/abs/mps-for-sale-returns-to-office-in-postwar-british-politics/E4C2B102194AA1EA0D2F1F777EAE3C08" target="_blank">Eggers and Hainmueller (2009)</a> ]</p>
</section>
<section id="logic-of-the-regression-discontinuity-design-rdd" class="level2">
<h2 class="anchored" data-anchor-id="logic-of-the-regression-discontinuity-design-rdd">Logic of the Regression Discontinuity Design (RDD)</h2>
<ul>
<li><p>What’s the effect of holding elected office in the UK on personal wealth?</p></li>
<li><p>People who win elections differ in many ways from people who lose elections.</p></li>
<li><p>Logic of an RDD:</p>
<ul>
<li><p>Just look at the wealth of individuals who either narrowly won or lost elections.</p></li>
<li><p>Candidates close to 50 percent cutoff (discontinuity) should be more comparable (better counterfactuals)</p></li>
</ul></li>
</ul>
</section>
<section id="data-from-eggers-and-hainmueller-2009" class="level2">
<h2 class="anchored" data-anchor-id="data-from-eggers-and-hainmueller-2009">Data from Eggers and Hainmueller (2009)</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(qss)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(MPs)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(MPs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 427
Columns: 10
$ surname    &lt;chr&gt; "Llewellyn", "Morris", "Walker", "Walker", "Waring", "Brown…
$ firstname  &lt;chr&gt; "David", "Claud", "George", "Harold", "John", "Ronald", "Le…
$ party      &lt;chr&gt; "tory", "labour", "tory", "labour", "tory", "labour", "tory…
$ ln.gross   &lt;dbl&gt; 12.13591, 12.44809, 12.42845, 11.91845, 13.52022, 12.46052,…
$ ln.net     &lt;dbl&gt; 12.135906, 12.448091, 10.349009, 12.395034, 13.520219, 9.63…
$ yob        &lt;int&gt; 1916, 1920, 1914, 1927, 1923, 1921, 1907, 1912, 1905, 1920,…
$ yod        &lt;int&gt; 1992, 2000, 1999, 2003, 1989, 2002, 1987, 1984, 1998, 2004,…
$ margin.pre &lt;dbl&gt; NA, NA, -0.057168204, -0.072508894, -0.269689620, 0.3409586…
$ region     &lt;chr&gt; "Wales", "South West England", "North East England", "Yorks…
$ margin     &lt;dbl&gt; 0.05690404, -0.04973833, -0.04158868, 0.02329524, -0.230005…</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-0bd698fa55adaa1e52a6" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-0bd698fa55adaa1e52a6">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10"],["surname","firstname","party","ln.gross","ln.net","yob","yod","margin.pre","region","margin"],["surname of the candidate","first name of the candidate","party of the candidate (labour or tory)","log gross wealth at the time of death","log net wealth at the time of death","year of birth of the candidate","year of death of the candidate","margin of the candidate’s party in the previous election electoral","region","margin of victory (vote share)"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Variable<\/th>\n      <th>Description<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Variable","targets":1},{"name":"Description","targets":2}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>MPs <span class="sc">%&gt;%</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(margin, ln.net))<span class="sc">+</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span>party)<span class="sc">+</span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span>MPs <span class="sc">%&gt;%</span></span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(margin <span class="sc">&lt;</span><span class="dv">0</span>),</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">data =</span>MPs <span class="sc">%&gt;%</span></span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(margin <span class="sc">&gt;</span><span class="dv">0</span>),</span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">method =</span> <span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="ot">-&gt;</span> fig_rdd</span>
<span id="cb79-12"><a href="#cb79-12" aria-hidden="true" tabindex="-1"></a>fig_rdd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/rddfig-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="rdd-notation" class="level2">
<h2 class="anchored" data-anchor-id="rdd-notation">RDD Notation</h2>
<ul>
<li><span class="math inline">\(X\)</span> is a <strong>forcing</strong> variable</li>
<li>Treatment <span class="math inline">\(D\)</span> is a determined by <span class="math inline">\(X\)</span></li>
</ul>
<p><span class="math display">\[
D_i = 1\{X_i &gt; c\}
\]</span></p>
<ul>
<li><p><span class="math inline">\(X\)</span> is the <code>margin</code> variable in the example data, and <span class="math inline">\(D=1\)</span> if <code>margin</code> is greater than 0 (i.e.&nbsp;the candidate won the election)</p></li>
<li><p>Interested in the differences in the outcome at the threshold</p></li>
</ul>
<p><span class="math display">\[\lim_{x \downarrow  c} E[Y_i|X=x] - \lim_{x \uparrow  c} E[Y_i|X=x]\]</span></p>
</section>
<section id="causal-identification-with-an-rdd" class="level2">
<h2 class="anchored" data-anchor-id="causal-identification-with-an-rdd">Causal Identification with an RDD</h2>
<p>If we assume <span class="math inline">\(E[Y_i(0)|X=x]\)</span> and <span class="math inline">\(E[Y_i(1)|X=x]\)</span> are continuous in x, then we can estimate a (local) ATE at the threshold:</p>
<p><span class="math display">\[\begin{align}
ATE_{RDD} &amp;= E[Y(1)-Y(0)|X_i=c] \\
&amp;=  E[Y(1)|X_i=c] -  E[Y(0)|X_i=c]\\
&amp;= \lim_{x \downarrow  c} E[Y_i|X=x] - \lim_{x \uparrow  c} E[Y_i|X=x] \\
\end{align}\]</span></p>
</section>
<section id="continuity-assumption" class="level2">
<h2 class="anchored" data-anchor-id="continuity-assumption">Continuity Assumption</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://mixtape.scunning.com/graphics/rdd_simul_ex.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://mixtape.scunning.com/regression-discontinuity.html#continuity-assumption" target="_blank">Cunningham (2022)</a></p>
</section>
<section id="causal-identification-with-an-rdd-1" class="level2">
<h2 class="anchored" data-anchor-id="causal-identification-with-an-rdd-1">Causal Identification with an RDD</h2>
<ul>
<li><p>The continuity assumption is a formal way of saying that observations close to the threshold are good counterfactuals for each other</p></li>
<li><p>We can’t prove this assumption</p></li>
<li><p>But if it holds, we should observe</p>
<ul>
<li><p>no sorting around the cutoff (no self selection)</p></li>
<li><p>similar distributions of covariates around the cutoff (balance tests)</p></li>
<li><p>no effect of treatment on things measured pre-treatment (placebo tests)</p></li>
</ul></li>
</ul>
</section>
<section id="applications-of-rdd" class="level2">
<h2 class="anchored" data-anchor-id="applications-of-rdd">Applications of RDD</h2>
<ul>
<li><p><a href="https://www.nber.org/papers/w8441" target="_blank">Lee (2001)</a> Does incumbency create electoral advantage</p></li>
<li><p><a href="https://journals.sagepub.com/doi/full/10.1177/0010414014534199" target="_blank">Eggers (2014)</a> Does proportional representatoin increase turnout?</p></li>
<li><p><a href="https://onlinelibrary.wiley.com/doi/full/10.1111/ajps.12427" target="_blank">Velez and Newman (2019)</a> What’s the effect of ethnic television on political participation</p></li>
</ul>
<p>class: inverse, center, middle # 💡 ## Instrumental Variables</p>
</section>
<section id="instrumental-variables" class="level2">
<h2 class="anchored" data-anchor-id="instrumental-variables">Instrumental Variables</h2>
<p>Instrumental variables are an economists favorite tool for dealing with <strong>omitted variable bias</strong></p>
<ul>
<li>We have some non random treatment whose effects we’d like to assess</li>
<li>We’re worried that these effects are <strong>confounded</strong> by some unobserved, omitted variable, that influences both the treatment and the outcome</li>
<li>We find an <strong>instrumental variable</strong> that satisfies the following:
<ul>
<li>Randomization</li>
<li>Excludability</li>
<li>First-stage relationship</li>
<li>Monotonicity</li>
</ul></li>
<li>Allowing us estimate a Local Average Treatment Effect (LATE) using the only the variation in our treatment is <strong>exogenous</strong> (uncorrelated with ommitted variables)</li>
</ul>
</section>
<section id="iv-assumption-randomization" class="level2">
<h2 class="anchored" data-anchor-id="iv-assumption-randomization">IV Assumption: Randomization</h2>
<p>.left-column[ - No path from <span class="math inline">\(U\)</span> to <span class="math inline">\(Z\)</span>] .right-column[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://book.declaredesign.org/figures/figure_16.7.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables" target="_blank">Source</a></p>
<p>]</p>
<p>class: center ## IV Assumption: Excludability</p>
<p>.left-column[ - No path from <span class="math inline">\(Z\)</span> to <span class="math inline">\(Y\)</span>]</p>
<p>.right-column[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://book.declaredesign.org/figures/figure_16.7.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables" target="_blank">Source</a></p>
<p>]</p>
<p>class: center ## IV Assumption: First Stage</p>
<p>.left-column[ - Path from <span class="math inline">\(Z\)</span> to <span class="math inline">\(D\)</span>] .right-column[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://book.declaredesign.org/figures/figure_16.7.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables" target="_blank">Source</a></p>
<p>]</p>
<p>class: center ## IV Assumption: Monotonicity</p>
<p>.left-column[</p>
<ul>
<li><span class="math inline">\(D_i(Z=1)\geq D_i(Z=0)\)</span></li>
<li>“No Defiers”</li>
</ul>
<p>]</p>
<p>.right-column[</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://book.declaredesign.org/figures/figure_16.7.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://book.declaredesign.org/observational-causal.html?q=instrumental#instrumental-variables" target="_blank">Source</a> ]</p>
<p>class: center ## Compliance</p>
<p>With a binary treatment, <span class="math inline">\(D\)</span> and binary instrument <span class="math inline">\(Z\)</span> there are four types of compliance</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Type</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">$D_i(Z=1)$</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">$D_i(Z=0)$</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Always Takers</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Never Takers</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Compliers</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Defiers</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>


</div>
</div>
<ul>
<li>Assuming Monotonicity means there are “No Defiers”</li>
</ul>
</section>
<section id="estimating-the-local-average-treatment-effect" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-local-average-treatment-effect">Estimating the Local Average Treatment Effect</h2>
<p>If we believe our assumptions of:</p>
<ul>
<li>Randomization</li>
<li>Excludability</li>
<li>First-stage relationship</li>
<li>Monotonicity</li>
</ul>
<p>Then we can estimate Local Average Treatment Effect (LATE) sometimes called the Complier Average Treatment Effect CATE)</p>
</section>
<section id="estimating-the-local-average-treatment-effect-1" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-local-average-treatment-effect-1">Estimating the Local Average Treatment Effect</h2>
<p>It can be <a href="https://www.mattblackwell.org/files/teaching/s10-iv-handout.pdf" target="_blank">shown</a> that the LATE:</p>
<p><span class="math display">\[LATE = \frac{E[Y|Z=1] - E[Y|Z=0]}{E[D|Z=1]-E[D|Z=0]}= \frac{ATE_{Z\to Y}}{ATE_{Z\to D}}\]</span></p>
</section>
<section id="example-earnings-and-military-service" class="level2">
<h2 class="anchored" data-anchor-id="example-earnings-and-military-service">Example: Earnings and Military Service</h2>
<p>Adapted from <a href="https://raw.githack.com/edrubin/EC421W19/master/LectureNotes/11InstrumentalVariables/11_instrumental_variables.html#42" target="_blank">Edward Rubin</a></p>
<p><em>Example:</em> If we want to estimate the effect of veteran status on earnings, <span class="math display">\[\begin{align}
  \text{Earnings}_i = \beta_0 + \beta_1 \text{Veteran}_i + u_i \tag{1}
\end{align}\]</span></p>
<p>–</p>
<p>We would love to calculate <span class="math inline">\(\color{#e64173}{\text{Earnings}_{1i}} - \color{#6A5ACD}{\text{Earnings}_{0i}}\)</span>, but we can’t.</p>
<p>–</p>
<p>And OLS will likely be biased for <span class="math inline">\((1)\)</span> due to selection/omitted-variable bias.</p>
</section>
<section id="introductory-example" class="level2">
<h2 class="anchored" data-anchor-id="introductory-example">Introductory example</h2>
<p>Imagine that we can split veteran status into an exogenous (as-if random, unbiased) part and an endogenous (non-random, biased) part…</p>
<p>–</p>
<p><span class="math display">\[\begin{align}
  \text{Earnings}_i
  &amp;= \beta_0 + \beta_1 \text{Veteran}_i + u_i \tag{1} \\
  &amp;= \beta_0 + \beta_1 \left(\text{Veteran}_i^{\text{Exog.}} + \text{Veteran}_i^{\text{Endog.}}\right) + u_i \\
  &amp;= \beta_0 + \beta_1 \text{Veteran}_i^{\text{Exog.}} + \underbrace{\beta_1 \text{Veteran}_i^{\text{Endog.}} + u_i}_{w_i} \\
  &amp;= \beta_0 + \beta_1 \text{Veteran}_i^{\text{Exog.}} + w_i
\end{align}\]</span></p>
<p>–</p>
<p>We could use this exogenous variation in veteran status to consistently estimate <span class="math inline">\(\beta_1\)</span>.</p>
<p>–</p>
<p><strong>Q:</strong> What would exogenous variation in veteran status mean?</p>
</section>
<section id="introductory-example-1" class="level2">
<h2 class="anchored" data-anchor-id="introductory-example-1">Introductory example</h2>
<p><strong>Q:</strong> What would exogenous variation in veteran status mean?</p>
<p>–</p>
<p><strong>A.sub[1]:</strong> Choices to enlist in the military that are essentially random—or at least uncorrelated with omitted variables and the disturbance.</p>
<p>–</p>
<p><strong>A.sub[2]:</strong> .No selection bias: <span class="math display">\[\begin{align}
  \color{#e64173}{\mathop{E}\left(\text{Earnings}_{0i}\mid\text{Veteran}_i = 1\right)} - \color{#6A5ACD}{\mathop{E}\left( \text{Earnings}_{0i} \mid \text{Veteran}_i = 0 \right)} = 0
\end{align}\]</span></p>
</section>
<section id="instruments" class="level2">
<h2 class="anchored" data-anchor-id="instruments">Instruments</h2>
</section>
<section id="q-how-do-we-isolate-this-exogenous-variation-in-our-explanatory-variable" class="level2">
<h2 class="anchored" data-anchor-id="q-how-do-we-isolate-this-exogenous-variation-in-our-explanatory-variable"><strong>Q:</strong> How do we isolate this <em>exogenous variation</em> in our explanatory variable?</h2>
<p><br><strong>A:</strong> Find an instrument (an instrumental variable).</p>
<p>–</p>
</section>
<section id="q-whats-an-instrument" class="level2">
<h2 class="anchored" data-anchor-id="q-whats-an-instrument"><strong>Q:</strong> What’s an instrument?</h2>
<p><br><strong>A:</strong> An <strong>instrument</strong> is a variable that is</p>
<ol type="1">
<li><strong>correlated</strong> with the <strong>explanatory variable</strong> of interest (<em>relevant</em>),</li>
<li><strong>uncorrelated</strong> with the <strong>error</strong> term (<em>exogenous</em>).</li>
</ol>
</section>
<section id="instruments-1" class="level2">
<h2 class="anchored" data-anchor-id="instruments-1">Instruments</h2>
<p>So if we want an instrument <span class="math inline">\(z_i\)</span> for endogenous veteran status in</p>
<p><span class="math display">\[\begin{align}
  \text{Earnings}_i = \beta_0 + \beta_1 \text{Veteran}_i + u_i
\end{align}\]</span></p>
<ol type="1">
<li><strong>Relevant:</strong> <span class="math inline">\(\mathop{\text{Cov}} \left( \text{Veteran}_i,\, z_i \right) \neq 0\)</span></li>
<li><strong>Exogenous:</strong> <span class="math inline">\(\mathop{\text{Cov}} \left( z_i,\, u_i \right) = 0\)</span></li>
</ol>
</section>
<section id="instruments-relevance" class="level2">
<h2 class="anchored" data-anchor-id="instruments-relevance">Instruments: Relevance</h2>
<p><strong>Relevance:</strong> We need the instrument to cause a change in (correlate with) our endogenous explanatory variable.</p>
<p>We can actually test this requirement using regression and a <em>t</em> test.</p>
<p>–</p>
<p><strong><em>Example:</em></strong> For the veteran status, consider three potential instruments:</p>
<p>.pull-left[ 1. Social security number</p>
<ol start="2" type="1">
<li><p>Physical fitness</p></li>
<li><p>Vietnam War draft ]</p></li>
</ol>
<p>–</p>
<p>.pull-right[ - <strong>Probably not relevant</strong> uncorrelated with military service</p>
<ul>
<li><p><em>Potentially relevant</em> service may correlate with fitness</p></li>
<li><p><strong>Relevant</strong> being drafted led to service ]</p></li>
</ul>
</section>
<section id="instruments-exogeneity" class="level2">
<h2 class="anchored" data-anchor-id="instruments-exogeneity">Instruments: Exogeneity</h2>
<p>.hi[Exogeneity:] The instrument to be independent of omitted factors that affect our outcome variable—as good as randomly assigned.</p>
<p><span class="math inline">\(z_i\)</span> must be uncorrelated with our disturbance <span class="math inline">\(u_i\)</span>. .hi[Not testable.]</p>
<p>–</p>
<p><strong><em>Example:</em></strong> For the .pink[veteran status], consider three potential instruments:</p>
<p>.pull-left[ 1. Social security number</p>
<ol start="2" type="1">
<li><p>Physical fitness</p></li>
<li><p>Vietnam War draft ]</p></li>
</ol>
<p>–</p>
<p>.pull-right[ - <strong>Exogenous</strong> SSN essentially random</p>
<ul>
<li><p><em>Not Exogenous</em> fitness correlated with many things</p></li>
<li><p><strong>Exogenous</strong> draft via lottery ]</p></li>
</ul>
</section>
<section id="relevant-and-exogenous" class="level2">
<h2 class="anchored" data-anchor-id="relevant-and-exogenous">Relevant and Exogenous</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/venn_iv-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="relevant-not-exogenous" class="level2">
<h2 class="anchored" data-anchor-id="relevant-not-exogenous">Relevant, Not Exogenous</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/venn_iv_endog-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="not-relevant-and-not-exogenous" class="level2">
<h2 class="anchored" data-anchor-id="not-relevant-and-not-exogenous">Not Relevant and Not Exogenous</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/venn_iv_irrelevant-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="relevant-not-exogenous-1" class="level2">
<h2 class="anchored" data-anchor-id="relevant-not-exogenous-1">Relevant, Not Exogenous</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-slides_files/figure-revealjs/venn_iv_endog2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="venn-diagram-explanation" class="level1">
<h1>Venn diagram explanation</h1>
<p>In these figures (Venn diagrams)</p>
<ul>
<li>Each circle illustrates a variable.</li>
<li>Overlap gives the share of correlatation between two variables.</li>
<li>Dotted borders denote <em>omitted</em> variables.</li>
</ul>
<p>Take-aways</p>
<ul>
<li>Figure 1: .hi-pink[Valid instrument] (relevant; exogenous)</li>
<li>Figure 2: .hi-slate[Invalid instrument] (relevant; not exogenous)</li>
<li>Figure 3: .hi-slate[Invalid instrument] (not relevant; not exogenous)</li>
<li>Figure 4: .hi-slate[Invalid instrument] (relevant; not exogenous)</li>
</ul>
<section id="iv-applications" class="level2">
<h2 class="anchored" data-anchor-id="iv-applications">IV Applications</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://pbs.twimg.com/media/EJGyHnyUYAA-yhM?format=jpg&amp;name=large.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><a href="https://twitter.com/andrewheiss/status/1193931226865901569?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1193931226865901569%7Ctwgr%5E%7Ctwcon%5Es1_&amp;ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2Fandrewheiss2Fstatus2F1193931226865901569widget%3DTweet" target="_blank">@AndrewHeiss</a></p>
</section>
<section id="iv-summary" class="level2">
<h2 class="anchored" data-anchor-id="iv-summary">IV Summary</h2>
<p>Instrumental variables require a number of assumptions to yield credible causal claims:</p>
<ul>
<li>Randomization</li>
<li>Excludability</li>
<li>First-stage relationship</li>
<li>Monotonicity</li>
</ul>
<p>Estimation and inference of IVs is beyond the scope of this course.</p>
<ul>
<li><p>See Edward Rubin’s excellent <a href="https://raw.githack.com/edrubin/EC421W19/master/LectureNotes/11InstrumentalVariables/11_instrumental_variables.html#85" target="_blank">slides</a></p></li>
<li><p>And Matt Blackwells <a href="https://www.mattblackwell.org/files/teaching/s10-iv-handout.pdf" target="_blank">notes</a></p></li>
<li><p>Understanding the identifying assumptions of IV can help you critique a study (even if the you don’t fully understand the math)</p></li>
</ul>
<p>class: inverse, middle, center # 💡 ## Summary</p>
</section>
<section id="what-you-need-to-know" class="level2">
<h2 class="anchored" data-anchor-id="what-you-need-to-know">What you need to know</h2>
<ul>
<li>Causal inference in observational and experimental studies is about counterfactual comparisons</li>
<li>In observational studies, to make causal claims we generally make some assumption of conditional independence:</li>
</ul>
<p><span class="math display">\[
Y_i(1),Y_i(0), \perp D_i |X_i
\]</span></p>
<ul>
<li>The credibility of this assumption depends less on the data, and more on how the data were generated.</li>
<li><strong>Selection on Observables</strong> is rarely a credible assumption</li>
<li>Observational designs that produce credible causal inference, leverage aspects of the world that create <em>natural experiments</em></li>
<li>You should be able to describe the logic and assumptions of common designs in social science
<ul>
<li><strong>Difference-in-Differences:</strong> <em>Parallel Trends</em></li>
<li><strong>Regression Discontinuity:</strong> <em>Continuity at the cutoff</em></li>
<li><strong>Instrumental Variables:</strong> Instruments need to be <em>Relevant and Exogenous</em></li>
</ul></li>
</ul>


</section>
</section>

</main> <!-- /main -->

<script>
  // htmlwidgets need to know to resize themselves when slides are shown/hidden.
  // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
  // slide changes (different for each slide format).
  (function () {
    // dispatch for htmlwidgets
    function fireSlideEnter() {
      const event = window.document.createEvent("Event");
      event.initEvent("slideenter", true, true);
      window.document.dispatchEvent(event);
    }

    function fireSlideChanged(previousSlide, currentSlide) {
      fireSlideEnter();

      // dispatch for shiny
      if (window.jQuery) {
        if (previousSlide) {
          window.jQuery(previousSlide).trigger("hidden");
        }
        if (currentSlide) {
          window.jQuery(currentSlide).trigger("shown");
        }
      }
    }

    // hookup for slidy
    if (window.w3c_slidy) {
      window.w3c_slidy.add_observer(function (slide_num) {
        // slide_num starts at position 1
        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
      });
    }

  })();
</script>

<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>